-- seed.sql -- GENERATED. Ports SettingsSeeder / LanguageSeeder /
-- BlogCategorySeeder / BootcampCategorySeeder + the language_phrases corpus.
-- Idempotent: safe to re-run.

-- settings (25 rows)
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (1, 'system_title', 'EZiL Certify', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (2, 'system_email', 'admin@example.com', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (3, 'timezone', 'UTC', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (4, 'language', 'english', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (5, 'theme', 'classic', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (6, 'system_currency', 'USD', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (7, 'currency_position', 'left', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (8, 'protocol', 'smtp', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (9, 'smtp_host', 'mailpit', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (10, 'smtp_port', '1025', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (11, 'smtp_crypto', '', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (12, 'smtp_user', '', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (13, 'smtp_pass', '', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (14, 'smtp_from_email', 'hello@example.com', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (15, 'footer_text', 'EZiL Certify - Learning Management System', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (16, 'footer_link', '/', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (17, 'instructor_can_publish_course', '1', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (18, 'instructor_application', '1', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (19, 'student_email_verification', '0', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (20, 'paypal_active', '0', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (21, 'stripe_active', '0', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (22, 'razorpay_active', '0', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (23, 'meta_title', 'EZiL Certify - Online Learning Platform', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (24, 'meta_description', 'Learn from expert instructors with our comprehensive online courses', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."settings" ("id", "type", "description", "created_at", "updated_at") VALUES (25, 'meta_keywords', 'online courses, e-learning, education, lms', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;

-- languages (4 rows)
INSERT INTO public."languages" ("id", "name", "direction", "created_at", "updated_at") VALUES (1, 'English', 'ltr', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."languages" ("id", "name", "direction", "created_at", "updated_at") VALUES (2, 'Arabic', 'rtl', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."languages" ("id", "name", "direction", "created_at", "updated_at") VALUES (3, 'Spanish', 'ltr', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."languages" ("id", "name", "direction", "created_at", "updated_at") VALUES (4, 'French', 'ltr', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;

-- language_phrases (404 rows)
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (1, 1, 'Log In', 'Log In', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (2, 1, 'Sign in to continue', 'Sign in to continue', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (3, 1, 'Email Address', 'Email Address', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (4, 1, 'Enter your email', 'Enter your email', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (5, 1, 'Password', 'Password', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (6, 1, 'Enter your password', 'Enter your password', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (7, 1, 'Remember me', 'Remember me', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (8, 1, 'Forgot password?', 'Forgot password?', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (9, 1, 'Sign In', 'Sign In', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (10, 1, 'Don''t have an account?', 'Don''t have an account?', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (11, 1, 'Sign Up', 'Sign Up', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (12, 1, '404 not found', '404 not found', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (13, 1, 'The page you requested could not be found', 'The page you requested could not be found', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (14, 1, 'Please try the following', 'Please try the following', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (15, 1, 'Check the spelling of the url', 'Check the spelling of the url', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (16, 1, 'If you are still puzzled, click on the home link below', 'If you are still puzzled, click on the home link below', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (17, 1, 'Back to home', 'Back to home', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (18, 1, 'Close', 'Close', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (19, 1, 'Are you sure?', 'Are you sure?', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (20, 1, 'You can''t bring it back!', 'You can''t bring it back!', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (21, 1, 'Cancel', 'Cancel', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (22, 1, 'Yes, I''m sure', 'Yes, I''m sure', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (23, 1, 'Just Now', 'Just Now', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (24, 1, 'Success !', 'Success !', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (25, 1, 'Attention !', 'Attention !', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (26, 1, 'An Error Occurred !', 'An Error Occurred !', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (27, 1, 'Remove from wishlist', 'Remove from wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (28, 1, 'This course added to your wishlist', 'This course added to your wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (29, 1, 'Add to wishlist', 'Add to wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (30, 1, 'This course removed from your wishlist', 'This course removed from your wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (31, 1, 'Enter your keywords', 'Enter your keywords', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (32, 1, 'Show less', 'Show less', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (33, 1, 'Show more', 'Show more', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (34, 1, 'See your growth and get consulting support! ', 'See your growth and get consulting support! ', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (35, 1, 'Name', 'Name', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (36, 1, 'Email', 'Email', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (37, 1, 'Already have account?', 'Already have account?', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (38, 1, 'Sign in', 'Sign in', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (39, 1, 'Home', 'Home', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (40, 1, 'View All Courses', 'View All Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (41, 1, 'Online Courses', 'Online Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (42, 1, 'Active Students', 'Active Students', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (43, 1, 'Expert Instructors', 'Expert Instructors', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (44, 1, 'Course Enrollments', 'Course Enrollments', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (45, 1, 'Browse Categories', 'Browse Categories', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (46, 1, 'Explore our diverse range of course categories', 'Explore our diverse range of course categories', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (47, 1, 'Why Choose Us?', 'Why Choose Us?', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (48, 1, 'Discover the advantages of learning with us', 'Discover the advantages of learning with us', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (49, 1, 'Learn Anywhere', 'Learn Anywhere', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (50, 1, 'Access your courses from any device, anytime, anywhere in the world.', 'Access your courses from any device, anytime, anywhere in the world.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (51, 1, 'Learn from industry professionals with real-world experience.', 'Learn from industry professionals with real-world experience.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (52, 1, 'Get Certified', 'Get Certified', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (53, 1, 'Earn certificates upon completion to showcase your achievements.', 'Earn certificates upon completion to showcase your achievements.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (54, 1, '24/7 Support', '24/7 Support', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (55, 1, 'Get help whenever you need it with our dedicated support team.', 'Get help whenever you need it with our dedicated support team.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (56, 1, 'Ready to Start Learning?', 'Ready to Start Learning?', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (57, 1, 'Join thousands of learners and unlock your potential today', 'Join thousands of learners and unlock your potential today', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (58, 1, 'Get Started Free', 'Get Started Free', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (59, 1, 'Remove from Wishlist', 'Remove from Wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (60, 1, 'Added to wishlist', 'Added to wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (61, 1, 'Add to Wishlist', 'Add to Wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (62, 1, 'Removed from wishlist', 'Removed from wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (63, 1, 'Something went wrong', 'Something went wrong', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (64, 1, 'Courses', 'Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (65, 1, 'All Courses', 'All Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (66, 1, 'Showing', 'Showing', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (67, 1, 'of', 'of', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (68, 1, 'data', 'data', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (69, 1, 'Grid', 'Grid', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (70, 1, 'List', 'List', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (71, 1, 'Filter', 'Filter', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (72, 1, 'Search...', 'Search...', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (73, 1, 'Categories', 'Categories', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (74, 1, 'Price', 'Price', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (75, 1, 'Paid', 'Paid', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (76, 1, 'Discount', 'Discount', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (77, 1, 'Free', 'Free', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (78, 1, 'Level', 'Level', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (79, 1, 'Beginner', 'Beginner', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (80, 1, 'Intermediate', 'Intermediate', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (81, 1, 'Advanced', 'Advanced', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (82, 1, 'language', 'language', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (83, 1, 'English', 'English', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (84, 1, 'Arabic', 'Arabic', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (85, 1, 'Spanish', 'Spanish', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (86, 1, 'French', 'French', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (87, 1, 'Ratings', 'Ratings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (88, 1, 'Show Less', 'Show Less', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (89, 1, 'Show More', 'Show More', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (90, 1, 'No data found !', 'No data found !', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (91, 1, 'Please attempt utilizing the suitable keywords in your search query to obtain more precise results.', 'Please attempt utilizing the suitable keywords in your search query to obtain more precise results.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (92, 1, 'Back', 'Back', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (93, 1, 'Clear', 'Clear', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (94, 1, 'Email Verification', 'Email Verification', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (95, 1, 'Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn''t receive the email, we will gladly send you another.', 'Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn''t receive the email, we will gladly send you another.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (96, 1, 'Resend Verification Email', 'Resend Verification Email', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (97, 1, 'Workshop', 'Workshop', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (98, 1, 'Search courses', 'Search courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (99, 1, 'Cart', 'Cart', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (100, 1, 'Wishlist', 'Wishlist', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (101, 1, 'My Courses', 'My Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (102, 1, 'My Profile', 'My Profile', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (103, 1, 'My Workshops', 'My Workshops', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (104, 1, 'Message', 'Message', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (105, 1, 'Purchase History', 'Purchase History', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (106, 1, 'Log Out', 'Log Out', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (107, 1, 'Logout', 'Logout', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (108, 1, 'My profile', 'My profile', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (109, 1, 'It is a long established fact that a reader will be the distract by the read content of a page layout', 'It is a long established fact that a reader will be the distract by the read content of a page layout', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (110, 1, 'Contact with Us', 'Contact with Us', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (111, 1, 'Top Categories', 'Top Categories', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (112, 1, 'Useful links', 'Useful links', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (113, 1, 'Course', 'Course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (114, 1, 'Blog', 'Blog', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (115, 1, 'Knowledge Base', 'Knowledge Base', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (116, 1, 'Company', 'Company', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (117, 1, 'Phone : ', 'Phone : ', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (118, 1, 'Email : ', 'Email : ', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (119, 1, 'Newsletter', 'Newsletter', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (120, 1, 'Subscribe to stay tuned for new web design and latest updates. Let''s do it!', 'Subscribe to stay tuned for new web design and latest updates. Let''s do it!', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (121, 1, 'Email address', 'Email address', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (122, 1, 'Submit', 'Submit', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (123, 1, 'About Us', 'About Us', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (124, 1, 'Privacy Policy', 'Privacy Policy', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (125, 1, 'Terms And Use', 'Terms And Use', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (126, 1, 'Sales and Refunds', 'Sales and Refunds', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (127, 1, 'Cookie Policy', 'Cookie Policy', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (128, 1, 'FAQ', 'FAQ', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (129, 1, '© 2024 All Rights Reserved', '© 2024 All Rights Reserved', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (130, 1, 'You need to confirm that you want to login from this device', 'You need to confirm that you want to login from this device', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (131, 1, 'Please note that if you login from this device, your previously logged in device will be logged out.', 'Please note that if you login from this device, your previously logged in device will be logged out.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (132, 1, 'Got it, login now', 'Got it, login now', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (133, 1, 'Enrolled Courses', 'Enrolled Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (134, 1, 'In Progress', 'In Progress', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (135, 1, 'Completed', 'Completed', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (136, 1, 'Avg. Progress', 'Avg. Progress', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (137, 1, 'Continue Learning', 'Continue Learning', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (138, 1, 'Browse More Courses', 'Browse More Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (139, 1, 'No Courses Yet', 'No Courses Yet', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (140, 1, 'You haven''t enrolled in any courses yet. Start your learning journey today!', 'You haven''t enrolled in any courses yet. Start your learning journey today!', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (141, 1, 'Browse Courses', 'Browse Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (142, 1, 'Upload picture', 'Upload picture', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (143, 1, 'Learning', 'Learning', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (144, 1, 'My Classrooms', 'My Classrooms', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (145, 1, 'Account', 'Account', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (146, 1, 'Messages', 'Messages', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (147, 1, 'Code IDE', 'Code IDE', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (148, 1, 'Other', 'Other', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (149, 1, 'Back to Home', 'Back to Home', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (150, 1, 'Search courses...', 'Search courses...', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (151, 1, 'Upload', 'Upload', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (152, 1, 'Explore Courses', 'Explore Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (153, 1, 'Workshops', 'Workshops', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (154, 1, 'All Workshops', 'All Workshops', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (155, 1, 'Dashboard', 'Dashboard', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (156, 1, 'Welcome to Dashboard', 'Welcome to Dashboard', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (157, 1, 'Overview of your learning management system', 'Overview of your learning management system', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (158, 1, 'Total Revenue', 'Total Revenue', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (159, 1, 'Admin Revenue', 'Admin Revenue', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (160, 1, 'Instructor Revenue', 'Instructor Revenue', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (161, 1, 'This Month', 'This Month', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (162, 1, 'Total Courses', 'Total Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (163, 1, 'Total Lessons', 'Total Lessons', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (164, 1, 'Enrollments', 'Enrollments', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (165, 1, 'Students', 'Students', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (166, 1, 'Instructors', 'Instructors', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (167, 1, 'Admin Revenue This Year', 'Admin Revenue This Year', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (168, 1, 'View All', 'View All', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (169, 1, 'Course Status', 'Course Status', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (170, 1, 'Manage', 'Manage', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (171, 1, 'Active', 'Active', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (172, 1, 'Upcoming', 'Upcoming', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (173, 1, 'Pending', 'Pending', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (174, 1, 'Private', 'Private', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (175, 1, 'Draft', 'Draft', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (176, 1, 'Inactive', 'Inactive', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (177, 1, 'Recent Enrollments', 'Recent Enrollments', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (178, 1, 'No enrollments yet', 'No enrollments yet', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (179, 1, 'Top Courses', 'Top Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (180, 1, 'No courses yet', 'No courses yet', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (181, 1, 'Quick Actions', 'Quick Actions', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (182, 1, 'Add New Course', 'Add New Course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (183, 1, 'Manage Students', 'Manage Students', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (184, 1, 'Manage Instructors', 'Manage Instructors', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (185, 1, 'Manage Categories', 'Manage Categories', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (186, 1, 'Admin revenue', 'Admin revenue', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (187, 1, 'Main Menu', 'Main Menu', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (188, 1, 'Category', 'Category', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (189, 1, 'Manage Courses', 'Manage Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (190, 1, 'Coupons', 'Coupons', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (191, 1, 'Manage Workshops', 'Manage Workshops', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (192, 1, 'Add New Workshop', 'Add New Workshop', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (193, 1, 'Student enrollment', 'Student enrollment', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (194, 1, 'Course enrollment', 'Course enrollment', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (195, 1, 'Enrollment History', 'Enrollment History', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (196, 1, 'Enroll student', 'Enroll student', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (197, 1, 'Issued Certificates', 'Issued Certificates', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (198, 1, 'Payment Report', 'Payment Report', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (199, 1, 'Offline payments', 'Offline payments', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (200, 1, 'Payment History', 'Payment History', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (201, 1, 'Users', 'Users', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (202, 1, 'Admin', 'Admin', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (203, 1, 'Manage Admin', 'Manage Admin', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (204, 1, 'Add New Admin', 'Add New Admin', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (205, 1, 'Instructor', 'Instructor', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (206, 1, 'Add new Instructor', 'Add new Instructor', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (207, 1, 'Instructor Payout', 'Instructor Payout', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (208, 1, 'Instructor Setting', 'Instructor Setting', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (209, 1, 'Application', 'Application', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (210, 1, 'Student', 'Student', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (211, 1, 'Add new Student', 'Add new Student', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (212, 1, 'Manage Newsletters', 'Manage Newsletters', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (213, 1, 'Subscribed User', 'Subscribed User', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (214, 1, 'Contacts', 'Contacts', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (215, 1, 'Blogs', 'Blogs', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (216, 1, 'Manage Blogs', 'Manage Blogs', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (217, 1, 'Pending Blogs', 'Pending Blogs', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (218, 1, 'Settings', 'Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (219, 1, 'System Settings', 'System Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (220, 1, 'Website Settings', 'Website Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (221, 1, 'Payment Settings', 'Payment Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (222, 1, 'Manage Language', 'Manage Language', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (223, 1, 'Live Class Settings', 'Live Class Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (224, 1, 'SMTP Settings', 'SMTP Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (225, 1, 'Certificate Settings', 'Certificate Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (226, 1, 'Player Settings', 'Player Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (227, 1, 'Open AI Settings', 'Open AI Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (228, 1, 'Home Page Builder', 'Home Page Builder', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (229, 1, 'SEO Settings', 'SEO Settings', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (230, 1, 'About', 'About', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (231, 1, 'Admin Panel', 'Admin Panel', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (232, 1, 'View site', 'View site', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (233, 1, 'Sign Out', 'Sign Out', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (234, 1, 'Confirm', 'Confirm', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (235, 1, 'Loading', 'Loading', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (236, 1, 'AI Assistant', 'AI Assistant', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (237, 1, 'Select your service', 'Select your service', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (238, 1, 'Course title', 'Course title', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (239, 1, 'Course short description', 'Course short description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (240, 1, 'Course long description', 'Course long description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (241, 1, 'Course requirements', 'Course requirements', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (242, 1, 'Course outcomes', 'Course outcomes', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (243, 1, 'Course faq', 'Course faq', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (244, 1, 'Course seo tags', 'Course seo tags', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (245, 1, 'Course lesson text', 'Course lesson text', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (246, 1, 'Course certificate text', 'Course certificate text', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (247, 1, 'Course quiz text', 'Course quiz text', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (248, 1, 'Course blog title', 'Course blog title', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (249, 1, 'Course blog post', 'Course blog post', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (250, 1, 'Course thumbnail', 'Course thumbnail', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (251, 1, 'Enter your keyword', 'Enter your keyword', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (252, 1, 'Language', 'Language', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (253, 1, 'Generate', 'Generate', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (254, 1, 'Generating', 'Generating', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (255, 1, 'Your images', 'Your images', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (256, 1, 'Generated text', 'Generated text', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (257, 1, 'Copy', 'Copy', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (258, 1, 'Copied', 'Copied', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (259, 1, 'Create course', 'Create course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (260, 1, 'Add new Course', 'Add new Course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (261, 1, 'Basic Info', 'Basic Info', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (262, 1, 'Pricing', 'Pricing', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (263, 1, 'Media', 'Media', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (264, 1, 'Basic Information', 'Basic Information', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (265, 1, 'Enter Course Title', 'Enter Course Title', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (266, 1, 'Title', 'Title', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (267, 1, 'Enter Short Description', 'Enter Short Description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (268, 1, 'Short Description', 'Short Description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (269, 1, 'Description', 'Description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (270, 1, 'Enter Description', 'Enter Description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (271, 1, 'Select a category', 'Select a category', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (272, 1, 'Course level', 'Course level', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (273, 1, 'Select your course level', 'Select your course level', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (274, 1, 'Select language', 'Select language', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (275, 1, 'Status', 'Status', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (276, 1, 'Next', 'Next', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (277, 1, 'Pricing & Expiry', 'Pricing & Expiry', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (278, 1, 'Pricing type', 'Pricing type', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (279, 1, 'Enter price', 'Enter price', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (280, 1, 'Has Discount', 'Has Discount', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (281, 1, 'Enter discounted price', 'Enter discounted price', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (282, 1, 'Discounted price', 'Discounted price', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (283, 1, 'Expiry period', 'Expiry period', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (284, 1, 'Lifetime', 'Lifetime', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (285, 1, 'Limited time', 'Limited time', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (286, 1, 'Enter number of months', 'Enter number of months', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (287, 1, 'Number of months', 'Number of months', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (288, 1, 'Previous', 'Previous', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (289, 1, 'Course Thumbnail', 'Course Thumbnail', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (290, 1, 'Supported files: jpg, jpeg, png', 'Supported files: jpg, jpeg, png', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (291, 1, 'Drip Content', 'Drip Content', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (292, 1, 'Disable', 'Disable', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (293, 1, 'Enable', 'Enable', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (294, 1, 'All Category', 'All Category', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (295, 1, 'Add new category', 'Add new category', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (296, 1, 'Category Name', 'Category Name', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (297, 1, 'Enter your category name', 'Enter your category name', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (298, 1, 'Enter your unique category name', 'Enter your unique category name', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (299, 1, 'Pick Your Icon', 'Pick Your Icon', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (300, 1, 'Pick your category icon', 'Pick your category icon', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (301, 1, 'Keywords', 'Keywords', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (302, 1, 'optional', 'optional', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (303, 1, 'Enter your Keywords', 'Enter your Keywords', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (304, 1, 'Category Description', 'Category Description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (305, 1, 'Enter your description', 'Enter your description', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (306, 1, 'Thumbnail', 'Thumbnail', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (307, 1, 'Category logo', 'Category logo', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (308, 1, 'Category added successfully', 'Category added successfully', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (309, 1, 'Add', 'Add', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (310, 1, 'Edit category', 'Edit category', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (311, 1, 'Edit', 'Edit', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (312, 1, 'Delete', 'Delete', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (313, 1, 'Course added successfully', 'Course added successfully', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (314, 1, 'Edit course', 'Edit course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (315, 1, 'Editing', 'Editing', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (316, 1, 'Help', 'Help', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (317, 1, 'Frontend View', 'Frontend View', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (318, 1, 'Course Player', 'Course Player', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (319, 1, 'Save Changes', 'Save Changes', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (320, 1, 'Curriculum', 'Curriculum', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (321, 1, 'Basic', 'Basic', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (322, 1, 'Live Class', 'Live Class', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (323, 1, 'Info', 'Info', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (324, 1, 'SEO', 'SEO', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (325, 1, 'Add new section', 'Add new section', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (326, 1, 'Add section', 'Add section', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (327, 1, 'Add a new Section', 'Add a new Section', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (328, 1, 'Course Details', 'Course Details', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (329, 1, 'Certificate Course', 'Certificate Course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (330, 1, 'Overview', 'Overview', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (331, 1, 'Details', 'Details', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (332, 1, 'Reviews', 'Reviews', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (333, 1, 'Course Overview', 'Course Overview', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (334, 1, 'See more', 'See more', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (335, 1, 'FAQ area empty', 'FAQ area empty', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (336, 1, 'Course curriculum', 'Course curriculum', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (337, 1, 'Course curriculum Empty', 'Course curriculum Empty', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (338, 1, 'Requirment', 'Requirment', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (339, 1, 'Outcomes', 'Outcomes', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (340, 1, 'review', 'review', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (341, 1, 'View Details', 'View Details', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (342, 1, 'Rate this course : ', 'Rate this course : ', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (343, 1, 'Remove all', 'Remove all', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (344, 1, 'Write a reveiw ...', 'Write a reveiw ...', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (345, 1, 'Enroll Now', 'Enroll Now', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (346, 1, 'Duration', 'Duration', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (347, 1, 'Certificate', 'Certificate', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (348, 1, 'yes', 'yes', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (349, 1, 'Share', 'Share', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (350, 1, 'Share on Facebook', 'Share on Facebook', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (351, 1, 'Share on Twitter', 'Share on Twitter', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (352, 1, 'Share on Whatsapp', 'Share on Whatsapp', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (353, 1, 'Share on Linkedin', 'Share on Linkedin', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (354, 1, 'Your Course', 'Your Course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (355, 1, 'Lessons', 'Lessons', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (356, 1, 'by', 'by', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (357, 1, 'lesson', 'lesson', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (358, 1, 'Learn more', 'Learn more', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (359, 1, 'Instructor details', 'Instructor details', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (360, 1, 'Instructor Details', 'Instructor Details', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (361, 1, 'Hi, I’m', 'Hi, I’m', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (362, 1, 'Experience', 'Experience', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (363, 1, 'Recently appointed', 'Recently appointed', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (364, 1, 'New', 'New', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (365, 1, 'Progress', 'Progress', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (366, 1, 'Access', 'Access', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (367, 1, 'Not Started', 'Not Started', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (368, 1, 'Start Learning', 'Start Learning', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (369, 1, 'Course Playing Page', 'Course Playing Page', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (370, 1, 'Back to My Courses', 'Back to My Courses', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (371, 1, 'Complete', 'Complete', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (372, 1, 'lessons', 'lessons', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (373, 1, 'Summary', 'Summary', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (374, 1, 'Forum', 'Forum', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (375, 1, 'Class Schedules', 'Class Schedules', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (376, 1, 'Topic', 'Topic', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (377, 1, 'Date & time', 'Date & time', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (378, 1, 'Action', 'Action', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (379, 1, 'Keep up the great work!', 'Keep up the great work!', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (380, 1, 'Your dedication to ongoing progress is inspiring.', 'Your dedication to ongoing progress is inspiring.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (381, 1, 'Every step forward is a testament to your commitment to growth and excellence.', 'Every step forward is a testament to your commitment to growth and excellence.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (382, 1, 'Stay focused, stay determined, and continue to push yourself to new heights.', 'Stay focused, stay determined, and continue to push yourself to new heights.', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (383, 1, 'You have got this!', 'You have got this!', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (384, 1, 'Search answers here', 'Search answers here', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (385, 1, 'Questions in this course', 'Questions in this course', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (386, 1, 'Ask question', 'Ask question', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (387, 1, 'Course Content', 'Course Content', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (388, 1, 'Start Now', 'Start Now', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (389, 1, 'Coupon', 'Coupon', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (390, 1, 'Add Coupon', 'Add Coupon', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (391, 1, 'Export', 'Export', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (392, 1, 'PDF', 'PDF', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (393, 1, 'Print', 'Print', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (394, 1, 'Search coupon', 'Search coupon', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (395, 1, 'Search', 'Search', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (396, 1, 'No data found', 'No data found', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (397, 1, 'Code', 'Code', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (398, 1, 'Enter coupon code', 'Enter coupon code', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (399, 1, 'Discount (%)', 'Discount (%)', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (400, 1, 'Enter coupon discount', 'Enter coupon discount', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (401, 1, 'Expiry', 'Expiry', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (402, 1, 'Enter coupon expiry', 'Enter coupon expiry', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (403, 1, 'Choose status ...', 'Choose status ...', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."language_phrases" ("id", "language_id", "phrase", "translated", "created_at", "updated_at") VALUES (404, 1, 'Add coupon', 'Add coupon', NULL, NULL) ON CONFLICT DO NOTHING;

-- categories (1 rows)
INSERT INTO public."categories" ("id", "parent_id", "title", "slug", "icon", "sort", "status", "keywords", "description", "thumbnail", "category_logo", "created_at", "updated_at") VALUES (1, 0, 'Technology & AI', 'technology--ai', 'fab fa-microchip', 0, NULL, NULL, NULL, NULL, NULL, '2026-01-07 13:51:14', '2026-01-07 13:51:14') ON CONFLICT DO NOTHING;

-- blog_categories (4 rows)
INSERT INTO public."blog_categories" ("id", "title", "subtitle", "slug", "created_at", "updated_at") VALUES (1, 'Announcements', 'Product updates', 'announcements', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."blog_categories" ("id", "title", "subtitle", "slug", "created_at", "updated_at") VALUES (2, 'Guides', 'How-to articles', 'guides', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."blog_categories" ("id", "title", "subtitle", "slug", "created_at", "updated_at") VALUES (3, 'Insights', 'Industry trends', 'insights', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."blog_categories" ("id", "title", "subtitle", "slug", "created_at", "updated_at") VALUES (4, 'Events', 'Webinars and talks', 'events', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;

-- bootcamp_categories (4 rows)
INSERT INTO public."bootcamp_categories" ("id", "title", "slug", "created_at", "updated_at") VALUES (1, 'Development', 'development', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."bootcamp_categories" ("id", "title", "slug", "created_at", "updated_at") VALUES (2, 'Design', 'design', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."bootcamp_categories" ("id", "title", "slug", "created_at", "updated_at") VALUES (3, 'Marketing', 'marketing', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;
INSERT INTO public."bootcamp_categories" ("id", "title", "slug", "created_at", "updated_at") VALUES (4, 'Business', 'business', '2026-01-06 18:58:29', '2026-01-06 18:58:29') ON CONFLICT DO NOTHING;

-- Re-sync identity sequences after explicit-id inserts.
SELECT setval(pg_get_serial_sequence('public.settings','id'), COALESCE((SELECT MAX(id) FROM public.settings), 1), true);
SELECT setval(pg_get_serial_sequence('public.languages','id'), COALESCE((SELECT MAX(id) FROM public.languages), 1), true);
SELECT setval(pg_get_serial_sequence('public.language_phrases','id'), COALESCE((SELECT MAX(id) FROM public.language_phrases), 1), true);
SELECT setval(pg_get_serial_sequence('public.categories','id'), COALESCE((SELECT MAX(id) FROM public.categories), 1), true);
SELECT setval(pg_get_serial_sequence('public.blog_categories','id'), COALESCE((SELECT MAX(id) FROM public.blog_categories), 1), true);
SELECT setval(pg_get_serial_sequence('public.bootcamp_categories','id'), COALESCE((SELECT MAX(id) FROM public.bootcamp_categories), 1), true);
