-- Onyx 0001_tenancy.sql -- F-01 / F-02 / F-04 / F-05 (CMP-05).
--
-- The foundation of the whole platform: every Onyx table is tenant-scoped from
-- the first migration, so nothing built later has to be retrofitted.
--
-- Onyx tables live in `public` behind an `onyx_` prefix rather than in their own
-- schema. PostgREST only serves schemas the project is configured to expose,
-- and changing that setting on a live project the Laravel port also depends on
-- is not a change to make unilaterally. The prefix keeps the two products
-- unmistakably separate, and moving to a dedicated schema later is a rename
-- plus one dashboard setting. See docs/ADR-006-onyx-foundation.md.

-- ---------------------------------------------------------------------------
-- Claim helpers
--
-- These sit beside onyx.current_user_id() from the port. Reading the tenant
-- from the JWT rather than from a request parameter is what makes tenant
-- isolation enforceable in the database instead of hoped for in the API.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION onyx.current_tenant_id() RETURNS bigint
  LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'tenant_id', '')::bigint
  $$;

-- ---------------------------------------------------------------------------
-- Tenants
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_tenants" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(255) NOT NULL,
    "slug"        varchar(255) NOT NULL,
    "status"      smallint NOT NULL DEFAULT 1,
    "plan"        varchar(50),
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_tenants_slug_unique UNIQUE ("slug")
);

-- ---------------------------------------------------------------------------
-- People
--
-- `users` is the identity; `memberships` is what someone IS inside a tenant.
-- Roles are per membership, not per user, so the same person can be a student
-- at one institution and faculty at another without either leaking.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_users" (
    "id"                bigint GENERATED BY DEFAULT AS IDENTITY,
    "email"             varchar(255) NOT NULL,
    "name"              varchar(255) NOT NULL,
    "password"          varchar(255),
    "phone"             varchar(50),
    "photo"             varchar(255),
    "status"            smallint NOT NULL DEFAULT 1,
    "email_verified_at" timestamptz,
    "created_at"        timestamptz NOT NULL DEFAULT now(),
    "updated_at"        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_users_email_unique UNIQUE ("email")
);

CREATE TABLE IF NOT EXISTS public."onyx_memberships" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"    bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- student | faculty | exams | placement | employer | admin
    -- (employer arrived with O05; the column is varchar, so no DDL was needed)
    "role"       varchar(50) NOT NULL,
    "status"     smallint NOT NULL DEFAULT 1,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- One role per person per tenant. Holding two would make "what can they do
    -- here" ambiguous, and every guard would have to guess.
    CONSTRAINT onyx_memberships_unique UNIQUE ("tenant_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_memberships_tenant_idx ON public."onyx_memberships" ("tenant_id");
CREATE INDEX IF NOT EXISTS onyx_memberships_user_idx ON public."onyx_memberships" ("user_id");

-- ---------------------------------------------------------------------------
-- Audit log (F-05)
--
-- Sensitive actions across academics, assessment and finance. `before` and
-- `after` are jsonb because unlike the ported tables there is no PHP writing
-- here, so there is no reason to keep JSON as text.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_audit_logs" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "actor_id"    bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "action"      varchar(100) NOT NULL,
    "entity_type" varchar(100) NOT NULL,
    "entity_id"   bigint,
    "before"      jsonb,
    "after"       jsonb,
    "ip"          varchar(64),
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_audit_logs_tenant_idx ON public."onyx_audit_logs" ("tenant_id", "id" DESC);
CREATE INDEX IF NOT EXISTS onyx_audit_logs_entity_idx ON public."onyx_audit_logs" ("entity_type", "entity_id");

-- ---------------------------------------------------------------------------
-- Row level security
--
-- Deny-all baseline, FORCEd so even the table owner obeys it. Writes go through
-- the API on the service-role key, which bypasses RLS; these policies govern
-- what a tenant's own token may READ directly (PostgREST and Realtime).
--
-- auth.uid() is never used: it casts `sub` to uuid and these ids are bigint.
-- ---------------------------------------------------------------------------

ALTER TABLE public."onyx_tenants"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."onyx_tenants"     FORCE  ROW LEVEL SECURITY;
ALTER TABLE public."onyx_users"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."onyx_users"       FORCE  ROW LEVEL SECURITY;
ALTER TABLE public."onyx_memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."onyx_memberships" FORCE  ROW LEVEL SECURITY;
ALTER TABLE public."onyx_audit_logs"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."onyx_audit_logs"  FORCE  ROW LEVEL SECURITY;

-- A tenant may see itself, and nothing about any other institution.
CREATE POLICY "tenants_self_read" ON public."onyx_tenants"
  FOR SELECT TO authenticated
  USING ("id" = onyx.current_tenant_id());

-- Membership of the caller's own tenant only.
CREATE POLICY "memberships_tenant_read" ON public."onyx_memberships"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id());

-- A person is visible only through a membership of the caller's tenant. This is
-- the join that stops one institution enumerating another's people via the
-- shared identity table.
CREATE POLICY "users_same_tenant_read" ON public."onyx_users"
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public."onyx_memberships" m
    WHERE m."user_id" = public."onyx_users"."id"
      AND m."tenant_id" = onyx.current_tenant_id()
  ));

-- Audit logs are deliberately NOT readable by `authenticated`. They record who
-- changed a grade or a fee, so they are served through the API to admins only.

-- ---------------------------------------------------------------------------
-- Guard: every future Onyx table must be tenant-scoped.
--
-- The rule is easy to state and easy to forget on the fortieth table, so it is
-- checked rather than remembered.
--
-- Only Onyx tables are checked, identified by the prefix. Three exemptions:
-- `onyx_tenants` IS the tenant, `onyx_users` is the cross-tenant identity
-- reached through memberships, and `onyx_schema_migrations` is the migration
-- ledger rather than anybody's data.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION onyx.assert_tenant_scoped() RETURNS TABLE(missing text)
  LANGUAGE sql STABLE AS $$
    SELECT c.relname::text
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND c.relname LIKE 'onyx\_%'
      AND c.relname NOT IN ('onyx_tenants', 'onyx_users', 'onyx_schema_migrations')
      AND NOT EXISTS (
        SELECT 1 FROM pg_attribute a
        WHERE a.attrelid = c.oid AND a.attname = 'tenant_id' AND a.attnum > 0
          AND NOT a.attisdropped
      )
  $$;

NOTIFY pgrst, 'reload schema';
