-- Onyx 0002_learn.sql -- LRN-01, LRN-02, LRN-03, LRN-04.
--
-- "The student learning core. Courses, structured content, attendance and
-- assignments in one continuous flow -- so every learner always knows what to
-- do next."
--
-- Every table carries tenant_id from the start; onyx.assert_tenant_scoped()
-- fails the runner otherwise. See docs/ADR-006-onyx-foundation.md.

-- ---------------------------------------------------------------------------
-- LRN-01a: academic structure
--
-- This is what makes the catalog institutional rather than a marketplace. A
-- course is not a product someone buys; it sits in a semester of a programme,
-- and a learner reaches it by belonging to a batch.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_programs" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "name"        varchar(255) NOT NULL,
    "code"        varchar(50) NOT NULL,
    "description" text,
    "duration_semesters" smallint NOT NULL DEFAULT 1,
    "status"      smallint NOT NULL DEFAULT 1,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- Codes are how an institution refers to a programme internally, so they
    -- are unique within it -- and only within it.
    CONSTRAINT onyx_programs_code_unique UNIQUE ("tenant_id", "code")
);

CREATE TABLE IF NOT EXISTS public."onyx_semesters" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "program_id" bigint NOT NULL REFERENCES public."onyx_programs"("id") ON DELETE CASCADE,
    "name"       varchar(255) NOT NULL,
    "number"     smallint NOT NULL,
    "starts_on"  date,
    "ends_on"    date,
    "status"     smallint NOT NULL DEFAULT 1,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_semesters_number_unique UNIQUE ("program_id", "number")
);

CREATE TABLE IF NOT EXISTS public."onyx_batches" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "program_id" bigint NOT NULL REFERENCES public."onyx_programs"("id") ON DELETE CASCADE,
    "name"       varchar(255) NOT NULL,
    "code"       varchar(50) NOT NULL,
    "year"       smallint,
    "status"     smallint NOT NULL DEFAULT 1,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_batches_code_unique UNIQUE ("tenant_id", "code")
);

CREATE TABLE IF NOT EXISTS public."onyx_batch_members" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "batch_id"   bigint NOT NULL REFERENCES public."onyx_batches"("id") ON DELETE CASCADE,
    "user_id"    bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_batch_members_unique UNIQUE ("batch_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_semesters_program_idx ON public."onyx_semesters" ("program_id");
CREATE INDEX IF NOT EXISTS onyx_batches_program_idx ON public."onyx_batches" ("program_id");
CREATE INDEX IF NOT EXISTS onyx_batch_members_user_idx ON public."onyx_batch_members" ("user_id");

-- ---------------------------------------------------------------------------
-- LRN-01b: the catalog and enrolment
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_courses" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "program_id"  bigint REFERENCES public."onyx_programs"("id") ON DELETE SET NULL,
    "semester_id" bigint REFERENCES public."onyx_semesters"("id") ON DELETE SET NULL,
    "code"        varchar(50) NOT NULL,
    "title"       varchar(255) NOT NULL,
    "slug"        varchar(255) NOT NULL,
    "description" text,
    "credits"     smallint NOT NULL DEFAULT 0,
    -- Whether a learner may enrol themselves, or only an administrator can.
    "self_enroll" smallint NOT NULL DEFAULT 0,
    "status"      smallint NOT NULL DEFAULT 0,
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_courses_code_unique UNIQUE ("tenant_id", "code"),
    CONSTRAINT onyx_courses_slug_unique UNIQUE ("tenant_id", "slug")
);

-- A course is taught by people, usually more than one, so this is its own table
-- rather than a column that would need rewriting the first time it is two.
CREATE TABLE IF NOT EXISTS public."onyx_course_faculty" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"  bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "user_id"    bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_course_faculty_unique UNIQUE ("course_id", "user_id")
);

CREATE TABLE IF NOT EXISTS public."onyx_enrollments" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"   bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- Set when the enrolment came from a bulk batch enrolment, so a cohort can
    -- be traced back to the decision that created it.
    "batch_id"    bigint REFERENCES public."onyx_batches"("id") ON DELETE SET NULL,
    "status"      smallint NOT NULL DEFAULT 1,
    "enrolled_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- Enrolling twice is not a second enrolment, it is the same one.
    CONSTRAINT onyx_enrollments_unique UNIQUE ("course_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_courses_tenant_idx ON public."onyx_courses" ("tenant_id", "status");
CREATE INDEX IF NOT EXISTS onyx_courses_semester_idx ON public."onyx_courses" ("semester_id");
CREATE INDEX IF NOT EXISTS onyx_enrollments_user_idx ON public."onyx_enrollments" ("user_id");
CREATE INDEX IF NOT EXISTS onyx_enrollments_course_idx ON public."onyx_enrollments" ("course_id");

-- ---------------------------------------------------------------------------
-- LRN-02: content, progress and resources
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_modules" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"  bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "title"      varchar(255) NOT NULL,
    "summary"    text,
    "sort"       integer NOT NULL DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_lessons" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    -- Denormalised from the module so every access check is one read, not two.
    "course_id"   bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "module_id"   bigint NOT NULL REFERENCES public."onyx_modules"("id") ON DELETE CASCADE,
    "title"       varchar(255) NOT NULL,
    -- video | document | text | link
    "type"        varchar(20) NOT NULL DEFAULT 'video',
    "path"        varchar(500),
    "body"        text,
    "duration_seconds" integer NOT NULL DEFAULT 0,
    "sort"        integer NOT NULL DEFAULT 0,
    -- A preview lesson is readable without enrolment, so the catalog can show
    -- what a course actually contains.
    "is_preview"  smallint NOT NULL DEFAULT 0,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Resumable playback. One row per learner per lesson, updated in place: a
-- history of positions is not what "resume where I left off" needs.
CREATE TABLE IF NOT EXISTS public."onyx_lesson_progress" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"   bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "lesson_id"   bigint NOT NULL REFERENCES public."onyx_lessons"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "position_seconds" integer NOT NULL DEFAULT 0,
    "completed_at" timestamptz,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_lesson_progress_unique UNIQUE ("lesson_id", "user_id")
);

-- LRN-02b. Files live in the shared bucket under onyx/<tenant>/..., and are
-- only ever handed out as short-lived signed URLs by the API.
CREATE TABLE IF NOT EXISTS public."onyx_resources" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"  bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "lesson_id"  bigint REFERENCES public."onyx_lessons"("id") ON DELETE CASCADE,
    "title"      varchar(255) NOT NULL,
    "path"       varchar(500) NOT NULL,
    "mime"       varchar(120),
    "size_bytes" bigint,
    "created_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_modules_course_idx ON public."onyx_modules" ("course_id", "sort");
CREATE INDEX IF NOT EXISTS onyx_lessons_module_idx ON public."onyx_lessons" ("module_id", "sort");
CREATE INDEX IF NOT EXISTS onyx_lesson_progress_user_idx ON public."onyx_lesson_progress" ("user_id", "course_id");
CREATE INDEX IF NOT EXISTS onyx_resources_course_idx ON public."onyx_resources" ("course_id");

-- ---------------------------------------------------------------------------
-- LRN-03: attendance
--
-- A session is one meeting of a course. Marking can be manual (faculty walk the
-- roster) or by QR (the learner marks themselves), and the record says which --
-- an attendance figure that cannot say how it was captured is not evidence.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_attendance_sessions" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"    bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "title"        varchar(255) NOT NULL,
    "scheduled_at" timestamptz NOT NULL,
    "duration_minutes" integer NOT NULL DEFAULT 60,
    -- open: self check-in accepted. closed: marking is faculty-only.
    "status"       varchar(20) NOT NULL DEFAULT 'open',
    -- The QR code is derived, never stored: a rotating HMAC of this secret and
    -- the current time window. Storing codes would make a leak permanent.
    "qr_secret"    varchar(64),
    "qr_window_seconds" integer NOT NULL DEFAULT 30,
    "created_by"   bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_attendance_records" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "session_id" bigint NOT NULL REFERENCES public."onyx_attendance_sessions"("id") ON DELETE CASCADE,
    "user_id"    bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- present | absent | late | excused
    "status"     varchar(20) NOT NULL,
    -- manual | qr
    "method"     varchar(20) NOT NULL DEFAULT 'manual',
    "note"       varchar(500),
    -- Who marked it. For QR this is the learner themselves, and saying so is
    -- the difference between a record and an assertion.
    "marked_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "marked_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- One row per learner per session. A second marking amends the first.
    CONSTRAINT onyx_attendance_records_unique UNIQUE ("session_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_attendance_sessions_course_idx
  ON public."onyx_attendance_sessions" ("course_id", "scheduled_at" DESC);
CREATE INDEX IF NOT EXISTS onyx_attendance_records_user_idx
  ON public."onyx_attendance_records" ("user_id");

-- ---------------------------------------------------------------------------
-- LRN-04: assignments, rubrics and submissions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_assignments" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"    bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "title"        varchar(255) NOT NULL,
    "instructions" text,
    "attachment_path" varchar(500),
    "due_at"       timestamptz,
    "total_points" integer NOT NULL DEFAULT 100,
    -- reject: nothing after the deadline. accept: late but flagged.
    -- penalty: accepted, flagged, and scored down by late_penalty_percent.
    "late_policy"  varchar(20) NOT NULL DEFAULT 'accept',
    "late_penalty_percent" smallint NOT NULL DEFAULT 0,
    "allow_resubmission" smallint NOT NULL DEFAULT 1,
    -- draft | published
    "status"       varchar(20) NOT NULL DEFAULT 'draft',
    "created_by"   bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- A rubric is its criteria. The service enforces that their points sum to the
-- assignment total, because a rubric that does not is a grading dispute waiting
-- to happen.
CREATE TABLE IF NOT EXISTS public."onyx_rubric_criteria" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "assignment_id" bigint NOT NULL REFERENCES public."onyx_assignments"("id") ON DELETE CASCADE,
    "title"         varchar(255) NOT NULL,
    "description"   text,
    "points"        integer NOT NULL,
    "sort"          integer NOT NULL DEFAULT 0,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_assignment_submissions" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "assignment_id" bigint NOT NULL REFERENCES public."onyx_assignments"("id") ON DELETE CASCADE,
    "user_id"       bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "body"          text,
    "file_path"     varchar(500),
    -- draft | submitted | graded | returned
    "status"        varchar(20) NOT NULL DEFAULT 'draft',
    "attempt"       smallint NOT NULL DEFAULT 1,
    "submitted_at"  timestamptz,
    "is_late"       smallint NOT NULL DEFAULT 0,
    "score"         numeric(8,2),
    "feedback"      text,
    "graded_by"     bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "graded_at"     timestamptz,
    -- Grading and returning are separate acts: a whole cohort is usually graded
    -- before anybody is told, so a score is not visible until it is returned.
    "returned_at"   timestamptz,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    "updated_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- One live submission per learner per assignment; resubmission raises the
    -- attempt rather than adding a row, so "their submission" is unambiguous.
    CONSTRAINT onyx_assignment_submissions_unique UNIQUE ("assignment_id", "user_id")
);

CREATE TABLE IF NOT EXISTS public."onyx_submission_scores" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "submission_id" bigint NOT NULL REFERENCES public."onyx_assignment_submissions"("id") ON DELETE CASCADE,
    "criterion_id"  bigint NOT NULL REFERENCES public."onyx_rubric_criteria"("id") ON DELETE CASCADE,
    "points"        numeric(8,2) NOT NULL,
    "comment"       text,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_submission_scores_unique UNIQUE ("submission_id", "criterion_id")
);

CREATE INDEX IF NOT EXISTS onyx_assignments_course_idx ON public."onyx_assignments" ("course_id", "due_at");
CREATE INDEX IF NOT EXISTS onyx_rubric_criteria_assignment_idx
  ON public."onyx_rubric_criteria" ("assignment_id", "sort");
CREATE INDEX IF NOT EXISTS onyx_assignment_submissions_user_idx
  ON public."onyx_assignment_submissions" ("user_id");

-- ---------------------------------------------------------------------------
-- Row level security
--
-- Deny-all baseline, FORCEd. Writes go through the API on the service-role key.
-- These policies govern what a tenant's own token may READ directly.
--
-- Two shapes:
--   * shared structure (programmes, courses, content) -- readable by anyone in
--     the tenant, because a catalog nobody can see is not a catalog;
--   * personal records (progress, attendance, submissions) -- readable only by
--     the person they are about. Faculty read them through the API, which
--     checks that they teach the course.
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_programs', 'onyx_semesters', 'onyx_batches', 'onyx_batch_members',
    'onyx_courses', 'onyx_course_faculty', 'onyx_enrollments',
    'onyx_modules', 'onyx_lessons', 'onyx_lesson_progress', 'onyx_resources',
    'onyx_attendance_sessions', 'onyx_attendance_records',
    'onyx_assignments', 'onyx_rubric_criteria',
    'onyx_assignment_submissions', 'onyx_submission_scores'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- Structure: this institution's, and only this institution's.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_programs', 'onyx_semesters', 'onyx_batches', 'onyx_batch_members',
    'onyx_courses', 'onyx_course_faculty',
    'onyx_modules', 'onyx_lessons',
    'onyx_attendance_sessions', 'onyx_assignments', 'onyx_rubric_criteria'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated '
      || 'USING ("tenant_id" = onyx.current_tenant_id())', t || '_tenant_read', t);
  END LOOP;
END $$;

-- Personal records: the tenant AND the person. The tenant predicate is not
-- redundant -- user ids are global across institutions, so without it a token
-- would read its holder's rows from every institution at once.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_enrollments', 'onyx_lesson_progress', 'onyx_attendance_records'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated '
      || 'USING ("tenant_id" = onyx.current_tenant_id() '
      || 'AND "user_id" = onyx.current_user_id())', t || '_owner_read', t);
  END LOOP;
END $$;

-- A submission carries a grade, so it is readable directly only by its author,
-- and only once it has been returned. Faculty read it through the API.
CREATE POLICY "onyx_assignment_submissions_owner_read"
  ON public."onyx_assignment_submissions"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND "user_id" = onyx.current_user_id());

-- Deliberately no select policy on onyx_resources or onyx_submission_scores.
-- A resource is reached through a signed URL the API issues after checking
-- enrolment; a rubric breakdown is served with the submission it belongs to.

NOTIFY pgrst, 'reload schema';
