-- Onyx 0003_codelab.sql -- LAB-01 .. LAB-05.
--
-- "A browser IDE, guided practice and project workspaces backed by a sandboxed,
-- auto-grading evaluator built for real skill-building."
--
-- Two things here are unlike anything in O01/O02:
--
--   * **A job queue.** The proposal puts grading behind queues, and everything
--     built so far is synchronous. A class of 200 submitting at once must
--     degrade in latency, not in correctness -- so runs are rows, not requests.
--   * **Hidden test cases.** The stdin and expected output of a hidden test are
--     the answer key. They live here and are never selected into any response.

-- ---------------------------------------------------------------------------
-- LAB-02b: the queue
--
-- Postgres rather than Redis: the durability guarantee is the point, and a row
-- that survives a restart is worth more than one that is fast. Workers claim
-- with FOR UPDATE SKIP LOCKED, which is what makes "none are double-graded"
-- true under concurrency rather than merely likely.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_jobs" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    -- code.run | code.grade | (later: proctor.review, notify.send)
    "kind"         varchar(50) NOT NULL,
    "payload"      jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- queued | running | done | failed
    "status"       varchar(20) NOT NULL DEFAULT 'queued',
    "attempts"     smallint NOT NULL DEFAULT 0,
    "max_attempts" smallint NOT NULL DEFAULT 3,
    -- When this becomes eligible. Retries push it forward; nothing else does.
    "run_after"    timestamptz NOT NULL DEFAULT now(),
    "locked_at"    timestamptz,
    "locked_by"    varchar(100),
    "last_error"   text,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- The claim query's index: eligible work, oldest first.
CREATE INDEX IF NOT EXISTS onyx_jobs_claim_idx
  ON public."onyx_jobs" ("status", "run_after", "id");
CREATE INDEX IF NOT EXISTS onyx_jobs_tenant_idx ON public."onyx_jobs" ("tenant_id", "kind");

-- ---------------------------------------------------------------------------
-- LAB-04: the problem bank
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_problems" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    -- A problem may belong to a course or stand alone in the bank.
    "course_id"   bigint REFERENCES public."onyx_courses"("id") ON DELETE SET NULL,
    "title"       varchar(255) NOT NULL,
    "slug"        varchar(255) NOT NULL,
    "statement"   text,
    -- easy | medium | hard
    "difficulty"  varchar(20) NOT NULL DEFAULT 'easy',
    "topic"       varchar(100),
    "tags"        jsonb NOT NULL DEFAULT '[]'::jsonb,
    -- Which languages this problem accepts. Empty means all configured ones.
    "languages"   jsonb NOT NULL DEFAULT '[]'::jsonb,
    "starter_code" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "time_limit_ms"   integer NOT NULL DEFAULT 2000,
    "memory_limit_kb" integer NOT NULL DEFAULT 262144,
    -- The worked solution, and when a learner is allowed to see it.
    "solution"    text,
    -- never | after_solve | after_attempts | after_date
    "solution_rule" varchar(30) NOT NULL DEFAULT 'after_solve',
    "solution_after_attempts" smallint NOT NULL DEFAULT 3,
    "solution_after"          timestamptz,
    -- draft | published
    "status"      varchar(20) NOT NULL DEFAULT 'draft',
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_problems_slug_unique UNIQUE ("tenant_id", "slug")
);

CREATE INDEX IF NOT EXISTS onyx_problems_bank_idx
  ON public."onyx_problems" ("tenant_id", "status", "difficulty");

-- The answer key. `stdin` and `expected_stdout` of a hidden case are exactly
-- what a learner must not be able to read, so nothing selects them into a
-- learner-facing response and there is no RLS policy on this table at all.
CREATE TABLE IF NOT EXISTS public."onyx_problem_tests" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "problem_id"  bigint NOT NULL REFERENCES public."onyx_problems"("id") ON DELETE CASCADE,
    "name"        varchar(255) NOT NULL DEFAULT 'Case',
    "stdin"       text,
    "expected_stdout" text,
    "is_hidden"   smallint NOT NULL DEFAULT 1,
    -- Partial scoring: a case is worth this many points of the problem total.
    "weight"      integer NOT NULL DEFAULT 1,
    "sort"        integer NOT NULL DEFAULT 0,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_problem_tests_problem_idx
  ON public."onyx_problem_tests" ("problem_id", "sort");

-- Progressive hints. Revealing one is recorded, so a hint can cost something
-- and so "progressive" means something other than "all of them at once".
CREATE TABLE IF NOT EXISTS public."onyx_hints" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "problem_id"  bigint NOT NULL REFERENCES public."onyx_problems"("id") ON DELETE CASCADE,
    "body"        text NOT NULL,
    "sort"        integer NOT NULL DEFAULT 0,
    "penalty_percent" smallint NOT NULL DEFAULT 0,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_hint_reveals" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "hint_id"     bigint NOT NULL REFERENCES public."onyx_hints"("id") ON DELETE CASCADE,
    "problem_id"  bigint NOT NULL REFERENCES public."onyx_problems"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_hint_reveals_unique UNIQUE ("hint_id", "user_id")
);

-- ---------------------------------------------------------------------------
-- LAB-03: submissions and per-case results
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_code_submissions" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "problem_id"  bigint NOT NULL REFERENCES public."onyx_problems"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "language"    varchar(50) NOT NULL,
    "source"      text NOT NULL,
    -- run: the learner pressed Run against the visible cases only.
    -- submit: graded against every case, hidden ones included.
    "mode"        varchar(20) NOT NULL DEFAULT 'submit',
    -- queued | running | done | failed
    "status"      varchar(20) NOT NULL DEFAULT 'queued',
    "score"       integer NOT NULL DEFAULT 0,
    "max_score"   integer NOT NULL DEFAULT 0,
    "passed"      integer NOT NULL DEFAULT 0,
    "total"       integer NOT NULL DEFAULT 0,
    -- Compile errors belong to the learner's own code, so they are shown.
    "compile_output" text,
    "error"       text,
    "runtime_ms"  integer,
    "memory_kb"   integer,
    "queued_at"   timestamptz NOT NULL DEFAULT now(),
    "graded_at"   timestamptz,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_code_submissions_user_idx
  ON public."onyx_code_submissions" ("user_id", "problem_id", "id" DESC);
CREATE INDEX IF NOT EXISTS onyx_code_submissions_problem_idx
  ON public."onyx_code_submissions" ("problem_id", "status");

-- One row per case per submission. `stdout` is kept for VISIBLE cases only --
-- storing a hidden case's actual output would put the answer one query away.
CREATE TABLE IF NOT EXISTS public."onyx_submission_cases" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "submission_id" bigint NOT NULL REFERENCES public."onyx_code_submissions"("id") ON DELETE CASCADE,
    "test_id"       bigint REFERENCES public."onyx_problem_tests"("id") ON DELETE SET NULL,
    "name"          varchar(255) NOT NULL DEFAULT 'Case',
    "is_hidden"     smallint NOT NULL DEFAULT 1,
    "passed"        smallint NOT NULL DEFAULT 0,
    "weight"        integer NOT NULL DEFAULT 1,
    "runtime_ms"    integer,
    "memory_kb"     integer,
    -- Only ever populated for a visible case.
    "stdout"        text,
    "error"         text,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_submission_cases_submission_idx
  ON public."onyx_submission_cases" ("submission_id");

-- ---------------------------------------------------------------------------
-- LAB-05: project workspaces
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_workspaces" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"   bigint REFERENCES public."onyx_courses"("id") ON DELETE SET NULL,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "title"       varchar(255) NOT NULL,
    "language"    varchar(50) NOT NULL DEFAULT 'python',
    "entry_path"  varchar(500) NOT NULL DEFAULT 'main.py',
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_workspace_files" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "workspace_id" bigint NOT NULL REFERENCES public."onyx_workspaces"("id") ON DELETE CASCADE,
    "path"         varchar(500) NOT NULL,
    "content"      text NOT NULL DEFAULT '',
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_workspace_files_unique UNIQUE ("workspace_id", "path")
);

-- The whole tree, captured. Stored as one jsonb document rather than copied
-- rows: a snapshot has to restore EXACTLY what it captured, and a set of rows
-- that can be edited afterwards would not.
CREATE TABLE IF NOT EXISTS public."onyx_workspace_snapshots" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "workspace_id" bigint NOT NULL REFERENCES public."onyx_workspaces"("id") ON DELETE CASCADE,
    "label"        varchar(255) NOT NULL,
    "files"        jsonb NOT NULL,
    "created_by"   bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_workspace_comments" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "workspace_id" bigint NOT NULL REFERENCES public."onyx_workspaces"("id") ON DELETE CASCADE,
    "snapshot_id"  bigint REFERENCES public."onyx_workspace_snapshots"("id") ON DELETE SET NULL,
    "file_path"    varchar(500),
    "line"         integer,
    "body"         text NOT NULL,
    "author_id"    bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "resolved_at"  timestamptz,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_workspaces_user_idx ON public."onyx_workspaces" ("user_id");
CREATE INDEX IF NOT EXISTS onyx_workspace_files_ws_idx ON public."onyx_workspace_files" ("workspace_id");
CREATE INDEX IF NOT EXISTS onyx_workspace_snapshots_ws_idx
  ON public."onyx_workspace_snapshots" ("workspace_id", "id" DESC);
CREATE INDEX IF NOT EXISTS onyx_workspace_comments_ws_idx
  ON public."onyx_workspace_comments" ("workspace_id");

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_jobs', 'onyx_problems', 'onyx_problem_tests', 'onyx_hints',
    'onyx_hint_reveals', 'onyx_code_submissions', 'onyx_submission_cases',
    'onyx_workspaces', 'onyx_workspace_files', 'onyx_workspace_snapshots',
    'onyx_workspace_comments'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- A published problem is readable by the institution. Its STATEMENT is; its
-- tests and its solution are separate tables, and neither is readable at all.
CREATE POLICY "onyx_problems_tenant_read" ON public."onyx_problems"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id() AND "status" = 'published');

-- Deliberately NO policy on onyx_problem_tests: hidden stdin and expected
-- output are the answer key. The API selects them with the service role and
-- never puts a hidden one in a response.
-- Deliberately NO policy on onyx_hints either -- a hint a learner has not
-- asked for is a hint they have not spent anything on.

-- Own submissions only, in the caller's own tenant.
CREATE POLICY "onyx_code_submissions_owner_read" ON public."onyx_code_submissions"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND "user_id" = onyx.current_user_id());

CREATE POLICY "onyx_hint_reveals_owner_read" ON public."onyx_hint_reveals"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND "user_id" = onyx.current_user_id());

-- Per-case results are served with the submission they belong to, after the
-- API has stripped everything belonging to a hidden case. No direct policy.

-- A workspace is the learner's own. Mentor review goes through the API, which
-- checks that the reviewer teaches the course it belongs to.
CREATE POLICY "onyx_workspaces_owner_read" ON public."onyx_workspaces"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND "user_id" = onyx.current_user_id());

CREATE POLICY "onyx_workspace_files_owner_read" ON public."onyx_workspace_files"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id() AND EXISTS (
    SELECT 1 FROM public."onyx_workspaces" w
    WHERE w."id" = public."onyx_workspace_files"."workspace_id"
      AND w."user_id" = onyx.current_user_id()
  ));

-- onyx_jobs has no read policy: a queued grading job carries the submission it
-- is about, and the queue is the server's business rather than anyone's data.

NOTIFY pgrst, 'reload schema';
