-- Onyx 0004_assess.sql -- ASS-01 .. ASS-04.
--
-- "Timed tests, remote proctoring and rich results analytics that give faculty
-- confidence in every score and cohort insight."
--
-- Assessment is the part of the platform where being wrong is expensive: a
-- score decides something. Three things in this schema exist for that reason
-- and not for tidiness.
--
--   * **Questions are versioned.** An attempt records the version it was sat
--     against, so editing a question afterwards cannot change a paper somebody
--     already answered. Without this, "the marks were wrong" becomes
--     unanswerable.
--   * **The paper is frozen into the attempt.** Randomised selection happens
--     once, at start, and is stored -- otherwise a refresh would deal a new
--     hand and a resumed attempt would be a different test.
--   * **Time is the server's.** `started_at`, `expires_at` and `submitted_at`
--     are all written here. Nothing a client says about the clock is trusted.

-- ---------------------------------------------------------------------------
-- ASS-01a: question banks
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_question_banks" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"  bigint REFERENCES public."onyx_courses"("id") ON DELETE SET NULL,
    "name"       varchar(255) NOT NULL,
    "description" text,
    "created_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_questions" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "bank_id"     bigint NOT NULL REFERENCES public."onyx_question_banks"("id") ON DELETE CASCADE,
    -- single | multiple | truefalse | short | essay
    "type"        varchar(20) NOT NULL DEFAULT 'single',
    "prompt"      text NOT NULL,
    -- [{ id, text }] for choice types; empty otherwise.
    "options"     jsonb NOT NULL DEFAULT '[]'::jsonb,
    -- The answer key. Never selected into a candidate-facing response.
    "answer"      jsonb,
    "explanation" text,
    "points"      integer NOT NULL DEFAULT 1,
    "difficulty"  varchar(20) NOT NULL DEFAULT 'medium',
    "tags"        jsonb NOT NULL DEFAULT '[]'::jsonb,
    -- Bumped on every edit. An attempt stores the version it saw, so a later
    -- edit cannot retroactively change what was asked or what was right.
    "version"     integer NOT NULL DEFAULT 1,
    "status"      varchar(20) NOT NULL DEFAULT 'active',
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_questions_bank_idx
  ON public."onyx_questions" ("bank_id", "status");

-- Every version a question has ever had, immutable once written.
--
-- `onyx_questions` holds the current text for authoring; this holds what was
-- actually asked. An attempt records the version it was sat against and
-- grading reads the answer key from HERE, so editing a question afterwards
-- cannot change either the paper or what counted as right on it. Keeping only
-- a version NUMBER on the attempt would prove nothing -- the content has to
-- survive too.
CREATE TABLE IF NOT EXISTS public."onyx_question_versions" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "question_id" bigint NOT NULL REFERENCES public."onyx_questions"("id") ON DELETE CASCADE,
    "version"     integer NOT NULL,
    "type"        varchar(20) NOT NULL,
    "prompt"      text NOT NULL,
    "options"     jsonb NOT NULL DEFAULT '[]'::jsonb,
    "answer"      jsonb,
    "explanation" text,
    "points"      integer NOT NULL DEFAULT 1,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_question_versions_unique UNIQUE ("question_id", "version")
);
CREATE INDEX IF NOT EXISTS onyx_questions_tags_idx
  ON public."onyx_questions" USING gin ("tags");

-- ---------------------------------------------------------------------------
-- ASS-01b: assessments
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_assessments" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"    bigint REFERENCES public."onyx_courses"("id") ON DELETE SET NULL,
    "title"        varchar(255) NOT NULL,
    "instructions" text,
    -- The window in which it may be started, and how long an attempt lasts.
    "opens_at"     timestamptz,
    "closes_at"    timestamptz,
    "duration_minutes" integer NOT NULL DEFAULT 60,
    "attempts_allowed" smallint NOT NULL DEFAULT 1,
    -- Sections: [{ id, title, bank_id, take, shuffle }]. `take` is how many
    -- questions are drawn from that bank, which is what "randomised banks"
    -- means in practice.
    "sections"     jsonb NOT NULL DEFAULT '[]'::jsonb,
    "shuffle_questions" smallint NOT NULL DEFAULT 1,
    "shuffle_options"   smallint NOT NULL DEFAULT 1,
    -- Proctoring is opt-in per assessment, and consent is per attempt.
    "proctoring"   smallint NOT NULL DEFAULT 0,
    "require_camera" smallint NOT NULL DEFAULT 0,
    "require_screen" smallint NOT NULL DEFAULT 0,
    -- Marking without seeing whose paper it is.
    "anonymous_marking" smallint NOT NULL DEFAULT 1,
    -- Second marking before anything can be published.
    "moderation_required" smallint NOT NULL DEFAULT 0,
    "pass_mark"    integer,
    -- draft | published | closed
    "status"       varchar(20) NOT NULL DEFAULT 'draft',
    -- Set when results are released. Until then a learner sees nothing.
    "results_published_at" timestamptz,
    "created_by"   bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_assessments_course_idx
  ON public."onyx_assessments" ("course_id", "status");

CREATE TABLE IF NOT EXISTS public."onyx_assessment_attempts" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "assessment_id" bigint NOT NULL REFERENCES public."onyx_assessments"("id") ON DELETE CASCADE,
    "user_id"       bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "attempt"       smallint NOT NULL DEFAULT 1,
    -- The paper, dealt once and kept: [{ question_id, version, section_id,
    -- points, order, option_order }]. A refresh must not deal a new hand.
    "paper"         jsonb NOT NULL DEFAULT '[]'::jsonb,
    -- in_progress | submitted | expired | graded | moderated | published
    "status"        varchar(20) NOT NULL DEFAULT 'in_progress',
    -- All three written by the server. Nothing a client says about the clock
    -- is trusted, so a changed system clock cannot extend an attempt.
    "started_at"    timestamptz NOT NULL DEFAULT now(),
    "expires_at"    timestamptz NOT NULL,
    "submitted_at"  timestamptz,
    -- Auto-scored total, rubric total, and the sum the learner is told.
    "auto_score"    numeric(8,2),
    "manual_score"  numeric(8,2),
    "score"         numeric(8,2),
    "max_score"     numeric(8,2) NOT NULL DEFAULT 0,
    -- Proctoring consent, recorded at start.
    "consented_at"  timestamptz,
    "integrity_flags" integer NOT NULL DEFAULT 0,
    -- clean | review | flagged | cleared | upheld
    "integrity_status" varchar(20) NOT NULL DEFAULT 'clean',
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    "updated_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_assessment_attempts_unique UNIQUE ("assessment_id", "user_id", "attempt")
);

CREATE INDEX IF NOT EXISTS onyx_assessment_attempts_assessment_idx
  ON public."onyx_assessment_attempts" ("assessment_id", "status");
CREATE INDEX IF NOT EXISTS onyx_assessment_attempts_user_idx
  ON public."onyx_assessment_attempts" ("user_id");

-- ASS-01c. One row per question per attempt, updated in place as the candidate
-- answers. A history of keystrokes is not what "resume where I left off" needs.
CREATE TABLE IF NOT EXISTS public."onyx_assessment_answers" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "attempt_id"  bigint NOT NULL REFERENCES public."onyx_assessment_attempts"("id") ON DELETE CASCADE,
    "question_id" bigint NOT NULL REFERENCES public."onyx_questions"("id") ON DELETE CASCADE,
    -- The version the candidate actually saw.
    "version"     integer NOT NULL DEFAULT 1,
    "response"    jsonb,
    -- Auto-scoring fills these; subjective types leave them null for a marker.
    "auto_points" numeric(8,2),
    "manual_points" numeric(8,2),
    "marker_comment" text,
    "flagged_for_review" smallint NOT NULL DEFAULT 0,
    "answered_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_assessment_answers_unique UNIQUE ("attempt_id", "question_id")
);

-- ---------------------------------------------------------------------------
-- ASS-02: proctoring
--
-- Events, not recordings. Storing video of a learner's room is a decision with
-- consequences the proposal does not ask for; what it asks for is
-- "reviewable integrity flags for each attempt", which is this table. Capture
-- of camera and screen is consented to and observed client-side; what reaches
-- the server is the event and, where it helps a human decide, a still.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_proctor_events" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "attempt_id"  bigint NOT NULL REFERENCES public."onyx_assessment_attempts"("id") ON DELETE CASCADE,
    -- consent | camera_on | camera_off | screen_on | screen_off |
    -- tab_blur | tab_focus | paste | copy | fullscreen_exit |
    -- multiple_faces | no_face | snapshot
    "kind"        varchar(40) NOT NULL,
    -- 0 for informational, higher for things an invigilator should look at.
    "weight"      smallint NOT NULL DEFAULT 0,
    "detail"      jsonb,
    -- A still, stored under onyx/<tenant>/proctor/. Never required.
    "media_path"  varchar(500),
    -- The server's clock, and the offset the client claimed, so a divergence
    -- is itself visible rather than silently trusted.
    "at"          timestamptz NOT NULL DEFAULT now(),
    "client_at"   timestamptz,
    -- open | dismissed | upheld
    "review"      varchar(20) NOT NULL DEFAULT 'open',
    "reviewed_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "reviewed_at" timestamptz,
    "review_note" text,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_proctor_events_attempt_idx
  ON public."onyx_proctor_events" ("attempt_id", "at");
CREATE INDEX IF NOT EXISTS onyx_proctor_events_review_idx
  ON public."onyx_proctor_events" ("tenant_id", "review");

-- ---------------------------------------------------------------------------
-- ASS-03: grading and moderation
--
-- A grade is a record of who decided what, not a number on the attempt. Second
-- marking means two rows, and moderation is a third -- which is the only way
-- "the moderator changed it" can be answered later.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_assessment_grades" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "attempt_id"  bigint NOT NULL REFERENCES public."onyx_assessment_attempts"("id") ON DELETE CASCADE,
    -- first | second | moderation
    "role"        varchar(20) NOT NULL DEFAULT 'first',
    "marker_id"   bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "manual_score" numeric(8,2) NOT NULL DEFAULT 0,
    "comment"     text,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- One mark per role per attempt. A second first-mark is an amendment of
    -- the first, not another opinion.
    CONSTRAINT onyx_assessment_grades_unique UNIQUE ("attempt_id", "role")
);

CREATE INDEX IF NOT EXISTS onyx_assessment_grades_attempt_idx
  ON public."onyx_assessment_grades" ("attempt_id");

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_question_banks', 'onyx_questions', 'onyx_question_versions', 'onyx_assessments',
    'onyx_assessment_attempts', 'onyx_assessment_answers',
    'onyx_proctor_events', 'onyx_assessment_grades'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- A published assessment is visible to the institution: candidates need to know
-- it exists and when it opens. Its questions are a different table.
CREATE POLICY "onyx_assessments_tenant_read" ON public."onyx_assessments"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id() AND "status" = 'published');

-- An attempt is the candidate's own.
CREATE POLICY "onyx_assessment_attempts_owner_read" ON public."onyx_assessment_attempts"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND "user_id" = onyx.current_user_id());

-- Deliberately NO policy on onyx_questions, onyx_question_versions,
-- onyx_question_banks,
-- onyx_assessment_answers, onyx_proctor_events or onyx_assessment_grades.
--
-- `onyx_questions.answer` is the answer key for every paper drawn from the
-- bank; `onyx_assessment_answers` carries per-question marks before results are
-- published; the proctor log and the mark sheet are an invigilator's and a
-- marker's business. All five are served through the API, which knows whether
-- results have been published and whether marking is anonymous.

NOTIFY pgrst, 'reload schema';
