-- Onyx 0005_career.sql -- CAR-01 .. CAR-05.
--
-- "From learning to employability -- hackathons, mock interviews, verifiable
-- certificates and a placement portal that turn skills into measurable job
-- readiness."
--
-- Career is where the platform starts making claims to people outside the
-- institution, and that changes what the schema has to guarantee.
--
--   * **A credential is checked by a stranger.** The verification page is
--     public, so a credential id is a capability: unguessable, and carrying
--     only what a stranger is entitled to see.
--   * **A skill is a claim about somebody.** Every one records the evidence
--     that produced it, so "why does this profile say they can do that" always
--     has an answer.
--   * **An employer is an outsider with an account.** They see exactly what
--     was shared with them and nothing else -- not the roster, not a cohort,
--     not another employer's pipeline.
--   * **A readiness score is arithmetic on a person.** The inputs are stored
--     with the score so it can be explained rather than asserted.

-- ---------------------------------------------------------------------------
-- CAR-03: verifiable certificates
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_certificates" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"      bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- course | assessment | contest | program
    "kind"         varchar(20) NOT NULL DEFAULT 'course',
    "course_id"    bigint REFERENCES public."onyx_courses"("id") ON DELETE SET NULL,
    "assessment_id" bigint REFERENCES public."onyx_assessments"("id") ON DELETE SET NULL,
    "title"        varchar(255) NOT NULL,
    -- The public identifier. Random and long: the verification page is open to
    -- anyone, so this is a capability rather than a serial number, and a
    -- guessable one would let a stranger enumerate an institution's graduates.
    "credential_id" varchar(64) NOT NULL,
    "issued_at"    timestamptz NOT NULL DEFAULT now(),
    "expires_at"   timestamptz,
    "revoked_at"   timestamptz,
    "revoked_reason" varchar(500),
    "issued_by"    bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    -- What the certificate says: score, grade, hours. Shown on the public page,
    -- so nothing personal beyond the holder's name ever goes in here.
    "detail"       jsonb NOT NULL DEFAULT '{}'::jsonb,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- Globally unique, not per tenant: a credential is presented to strangers
    -- who have no idea which institution issued it.
    CONSTRAINT onyx_certificates_credential_unique UNIQUE ("credential_id")
);

CREATE INDEX IF NOT EXISTS onyx_certificates_user_idx
  ON public."onyx_certificates" ("tenant_id", "user_id");

-- ---------------------------------------------------------------------------
-- CAR-05: the skills passport
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_skills" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "name"       varchar(255) NOT NULL,
    "slug"       varchar(255) NOT NULL,
    "category"   varchar(100),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_skills_slug_unique UNIQUE ("tenant_id", "slug")
);

-- One row per skill per learner per piece of evidence.
--
-- Not one row per skill with a "level" column: the acceptance criterion is that
-- every skill links to what earned it, and a single row would have to throw
-- away everything but the last thing that did.
CREATE TABLE IF NOT EXISTS public."onyx_learner_skills" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "skill_id"    bigint NOT NULL REFERENCES public."onyx_skills"("id") ON DELETE CASCADE,
    -- course | assessment | problem | workspace | certificate | contest
    "source_type" varchar(30) NOT NULL,
    "source_id"   bigint,
    -- What the evidence was worth, 0..100. Averaged into a level per skill.
    "strength"    smallint NOT NULL DEFAULT 50,
    "evidence"    jsonb NOT NULL DEFAULT '{}'::jsonb,
    "earned_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- The same piece of evidence cannot count twice for the same skill.
    CONSTRAINT onyx_learner_skills_unique UNIQUE ("user_id", "skill_id", "source_type", "source_id")
);

CREATE INDEX IF NOT EXISTS onyx_learner_skills_user_idx
  ON public."onyx_learner_skills" ("tenant_id", "user_id");

-- A readiness score, with the numbers it was computed from stored beside it.
--
-- A score nobody can explain is a score nobody should act on, and CAR-05b's
-- acceptance criterion is that the learner can see exactly why it is what it is.
CREATE TABLE IF NOT EXISTS public."onyx_readiness_scores" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "score"       numeric(5,2) NOT NULL DEFAULT 0,
    -- [{ key, label, weight, raw, points, detail }] -- every component, its
    -- weight, and what it contributed.
    "breakdown"   jsonb NOT NULL DEFAULT '[]'::jsonb,
    -- The weights in force when this was computed, so an old score still makes
    -- sense after the formula is changed.
    "formula"     jsonb NOT NULL DEFAULT '{}'::jsonb,
    "computed_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- Corrected in 0006: keyed by tenant as well, because one person can be a
    -- candidate at two institutions and has a score at each.
    CONSTRAINT onyx_readiness_scores_unique UNIQUE ("tenant_id", "user_id")
);

-- ---------------------------------------------------------------------------
-- CAR-04: employers, jobs and drives
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_employers" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "name"        varchar(255) NOT NULL,
    "website"     varchar(255),
    "about"       text,
    "contact_name"  varchar(255),
    "contact_email" varchar(255),
    -- The membership an employer contact signs in with. They are a member of
    -- the institution with the `employer` role, which is what scopes them.
    "user_id"     bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "status"      smallint NOT NULL DEFAULT 1,
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_jobs_posted" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "employer_id" bigint NOT NULL REFERENCES public."onyx_employers"("id") ON DELETE CASCADE,
    "title"       varchar(255) NOT NULL,
    "description" text,
    "location"    varchar(255),
    -- Stored as text: a salary is a negotiation, not a number the platform
    -- should pretend to compare across currencies.
    "compensation" varchar(255),
    "openings"    smallint NOT NULL DEFAULT 1,
    -- Eligibility is COMPUTED, never typed. These are the thresholds; whether
    -- somebody meets them is worked out from their record.
    "min_readiness"  smallint,
    "min_attendance" smallint,
    "required_skills" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "program_ids"    jsonb NOT NULL DEFAULT '[]'::jsonb,
    "batch_ids"      jsonb NOT NULL DEFAULT '[]'::jsonb,
    "closes_at"   timestamptz,
    -- draft | open | closed
    "status"      varchar(20) NOT NULL DEFAULT 'draft',
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_jobs_posted_employer_idx
  ON public."onyx_jobs_posted" ("tenant_id", "employer_id", "status");

CREATE TABLE IF NOT EXISTS public."onyx_job_applications" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "job_id"      bigint NOT NULL REFERENCES public."onyx_jobs_posted"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- applied | shortlisted | interviewing | offered | hired | rejected | withdrawn
    "status"      varchar(20) NOT NULL DEFAULT 'applied',
    "note"        text,
    -- What the platform computed at the moment of applying, kept so a later
    -- change to their record cannot rewrite whether they were eligible then.
    "readiness_at_apply" numeric(5,2),
    "decided_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "decided_at"  timestamptz,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_job_applications_unique UNIQUE ("job_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_job_applications_user_idx
  ON public."onyx_job_applications" ("tenant_id", "user_id");

CREATE TABLE IF NOT EXISTS public."onyx_drives" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "employer_id" bigint NOT NULL REFERENCES public."onyx_employers"("id") ON DELETE CASCADE,
    "job_id"      bigint REFERENCES public."onyx_jobs_posted"("id") ON DELETE SET NULL,
    "title"       varchar(255) NOT NULL,
    "scheduled_at" timestamptz,
    "venue"       varchar(255),
    -- planned | running | complete | cancelled
    "status"      varchar(20) NOT NULL DEFAULT 'planned',
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_drive_rounds" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "drive_id"    bigint NOT NULL REFERENCES public."onyx_drives"("id") ON DELETE CASCADE,
    "name"        varchar(255) NOT NULL,
    "sort"        integer NOT NULL DEFAULT 0,
    "scheduled_at" timestamptz,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- One learner in one round. The drive's outcome is the sum of these, which is
-- what makes "rounds and outcomes reconcile" checkable rather than asserted.
CREATE TABLE IF NOT EXISTS public."onyx_drive_results" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "round_id"    bigint NOT NULL REFERENCES public."onyx_drive_rounds"("id") ON DELETE CASCADE,
    "drive_id"    bigint NOT NULL REFERENCES public."onyx_drives"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- attended | absent | passed | failed
    "outcome"     varchar(20) NOT NULL,
    "note"        varchar(500),
    "recorded_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "recorded_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_drive_results_unique UNIQUE ("round_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_drive_results_drive_idx
  ON public."onyx_drive_results" ("drive_id");

-- ---------------------------------------------------------------------------
-- CAR-01: contests
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_contests" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "title"       varchar(255) NOT NULL,
    "description" text,
    "starts_at"   timestamptz NOT NULL,
    "ends_at"     timestamptz NOT NULL,
    -- Problems from the Code Lab bank: [{ problem_id, points }].
    "problems"    jsonb NOT NULL DEFAULT '[]'::jsonb,
    "team_size"   smallint NOT NULL DEFAULT 1,
    -- Minutes added to a team's total per wrong submission on a problem they
    -- eventually solve. Standard ICPC-style scoring, and stated so nobody has
    -- to reverse-engineer the leaderboard.
    "penalty_minutes" smallint NOT NULL DEFAULT 20,
    -- draft | published | judged
    "status"      varchar(20) NOT NULL DEFAULT 'draft',
    -- Hidden near the end so the final standings are a surprise.
    "freeze_minutes" smallint NOT NULL DEFAULT 0,
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_contest_teams" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "contest_id"  bigint NOT NULL REFERENCES public."onyx_contests"("id") ON DELETE CASCADE,
    "name"        varchar(255) NOT NULL,
    "created_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_contest_teams_name_unique UNIQUE ("contest_id", "name")
);

CREATE TABLE IF NOT EXISTS public."onyx_contest_members" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "team_id"     bigint NOT NULL REFERENCES public."onyx_contest_teams"("id") ON DELETE CASCADE,
    "contest_id"  bigint NOT NULL REFERENCES public."onyx_contests"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- One team per person per contest. Two would make the leaderboard a lie.
    CONSTRAINT onyx_contest_members_unique UNIQUE ("contest_id", "user_id")
);

-- A contest submission points at a Code Lab submission rather than repeating
-- it: the evaluator is the same one, and duplicating the source would let the
-- two disagree.
CREATE TABLE IF NOT EXISTS public."onyx_contest_submissions" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "contest_id"    bigint NOT NULL REFERENCES public."onyx_contests"("id") ON DELETE CASCADE,
    "team_id"       bigint NOT NULL REFERENCES public."onyx_contest_teams"("id") ON DELETE CASCADE,
    "user_id"       bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "problem_id"    bigint NOT NULL REFERENCES public."onyx_problems"("id") ON DELETE CASCADE,
    "submission_id" bigint REFERENCES public."onyx_code_submissions"("id") ON DELETE SET NULL,
    "solved"        smallint NOT NULL DEFAULT 0,
    "points"        integer NOT NULL DEFAULT 0,
    -- Minutes from the contest start. The tie-break, and the reason a
    -- leaderboard is stable rather than ordered by whoever was written last.
    "at_minute"     integer NOT NULL DEFAULT 0,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_contest_submissions_board_idx
  ON public."onyx_contest_submissions" ("contest_id", "team_id", "problem_id");

-- ---------------------------------------------------------------------------
-- CAR-02: mock interviews
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_mock_interviews" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"      bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "interviewer_id" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "title"        varchar(255) NOT NULL,
    "scheduled_at" timestamptz NOT NULL,
    "duration_minutes" integer NOT NULL DEFAULT 45,
    "join_url"     varchar(500),
    -- scheduled | completed | cancelled | no_show
    "status"       varchar(20) NOT NULL DEFAULT 'scheduled',
    -- [{ criterion, score, of, comment }] -- structured, not a free-text blob,
    -- so feedback can be compared across interviews.
    "feedback"     jsonb,
    "overall"      smallint,
    "notes"        text,
    -- Optional, and consented to at the time. Absent by default.
    "recording_path" varchar(500),
    "recording_consented_at" timestamptz,
    -- Feedback is written for the learner but not shown until the interviewer
    -- releases it, so a half-written note is never read as a verdict.
    "released_at"  timestamptz,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_mock_interviews_user_idx
  ON public."onyx_mock_interviews" ("tenant_id", "user_id");

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_certificates', 'onyx_skills', 'onyx_learner_skills', 'onyx_readiness_scores',
    'onyx_employers', 'onyx_jobs_posted', 'onyx_job_applications',
    'onyx_drives', 'onyx_drive_rounds', 'onyx_drive_results',
    'onyx_contests', 'onyx_contest_teams', 'onyx_contest_members',
    'onyx_contest_submissions', 'onyx_mock_interviews'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- Shared structure, readable inside the institution.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_skills', 'onyx_contests', 'onyx_contest_teams', 'onyx_contest_members',
    'onyx_drives', 'onyx_drive_rounds'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated '
      || 'USING ("tenant_id" = onyx.current_tenant_id())', t || '_tenant_read', t);
  END LOOP;
END $$;

-- A person's own record.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_certificates', 'onyx_learner_skills', 'onyx_readiness_scores',
    'onyx_job_applications', 'onyx_drive_results', 'onyx_mock_interviews'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated '
      || 'USING ("tenant_id" = onyx.current_tenant_id() '
      || 'AND "user_id" = onyx.current_user_id())', t || '_owner_read', t);
  END LOOP;
END $$;

-- An open job post is meant to be seen -- that is what a job board is.
CREATE POLICY "onyx_jobs_posted_open_read" ON public."onyx_jobs_posted"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id() AND "status" = 'open');

-- Deliberately NO policy on onyx_employers: an employer record carries a named
-- contact and their email, which is a real person's details and belongs to the
-- placement office rather than to everyone with a login.
--
-- Deliberately NO policy on onyx_contest_submissions: a live leaderboard is
-- served through the API, which knows whether the board is frozen. Reading the
-- rows directly would be a way round the freeze.

NOTIFY pgrst, 'reload schema';
