-- Onyx 0007_engage.sql -- LRN-05 and LRN-06.
--
-- "Personalised progress and nudges" and "discussion and doubt resolution, so
-- no learner is stuck alone."
--
-- Two things worth stating before the tables, because both shaped them:
--
--   * **LRN-05 gets no table at all.** A nudge is an opinion about a signal,
--     and the moment it is stored it starts disagreeing with the signal it came
--     from. The acceptance criterion is "the nudge changes when the underlying
--     signal changes", which a stored nudge fails by construction. Progress,
--     streaks and nudges are all derived at read time from lesson progress,
--     submissions, attendance and attempts -- rows that already exist.
--   * **A vote is a set of people, not a number.** The port's forum stores
--     likes as a JSON array of user ids, and that is the one thing about it
--     worth copying: a counter lets a single account click forever. The same
--     shape is used here, for the same reason.

-- ---------------------------------------------------------------------------
-- LRN-06a: threaded course Q&A
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_discussions" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "course_id"   bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    -- A question asked while watching a particular lesson keeps that context.
    -- Nullable: a course-wide question belongs to no lesson.
    "lesson_id"   bigint REFERENCES public."onyx_lessons"("id") ON DELETE SET NULL,
    "author_id"   bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "title"       varchar(255) NOT NULL,
    "body"        text NOT NULL,
    -- open | resolved | closed. Resolved is not closed: the acceptance
    -- criterion is that a resolved thread is "visibly resolved and still
    -- searchable", so resolving hides nothing.
    "status"      varchar(20) NOT NULL DEFAULT 'open',
    "resolved_at" timestamptz,
    "resolved_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    -- Which reply answered it. The answer is a post, so the thread keeps its
    -- shape rather than the answer being copied up here and drifting.
    "answer_post_id" bigint,
    -- Denormalised so a list of threads is one query rather than one per row.
    -- Maintained by the service; the tests assert it against the real count.
    "reply_count" integer NOT NULL DEFAULT 0,
    "last_post_at" timestamptz,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_discussions_course_idx
  ON public."onyx_discussions" ("tenant_id", "course_id", "last_post_at" DESC);

CREATE TABLE IF NOT EXISTS public."onyx_discussion_posts" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "discussion_id" bigint NOT NULL REFERENCES public."onyx_discussions"("id") ON DELETE CASCADE,
    -- One level of nesting: a reply, or a reply to a reply. Deeper threading
    -- reads worse than it sounds and makes "what is the answer" harder to see.
    "parent_id"     bigint REFERENCES public."onyx_discussion_posts"("id") ON DELETE CASCADE,
    "author_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "body"          text NOT NULL,
    -- Who voted, not how many. See the header.
    "votes"         jsonb NOT NULL DEFAULT '[]'::jsonb,
    "is_answer"     boolean NOT NULL DEFAULT false,
    "edited_at"     timestamptz,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_discussion_posts_thread_idx
  ON public."onyx_discussion_posts" ("tenant_id", "discussion_id", "created_at");

-- A mention is a row rather than a substring search, because "what was I
-- mentioned in" is a question the learner asks and a LIKE over every post body
-- is the wrong way to answer it.
CREATE TABLE IF NOT EXISTS public."onyx_discussion_mentions" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "discussion_id" bigint NOT NULL REFERENCES public."onyx_discussions"("id") ON DELETE CASCADE,
    "post_id"       bigint REFERENCES public."onyx_discussion_posts"("id") ON DELETE CASCADE,
    "user_id"       bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "read_at"       timestamptz,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_discussion_mentions_user_idx
  ON public."onyx_discussion_mentions" ("tenant_id", "user_id", "read_at");

-- ---------------------------------------------------------------------------
-- LRN-06b: escalation to a mentor, and tickets with an SLA
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_tickets" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    -- Where it came from. A ticket raised directly has no thread.
    "discussion_id" bigint REFERENCES public."onyx_discussions"("id") ON DELETE SET NULL,
    "course_id"     bigint REFERENCES public."onyx_courses"("id") ON DELETE SET NULL,
    "raised_by"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- The acceptance criterion is that an escalated question "reaches a NAMED
    -- owner". Nullable only between raising and triage, and the unowned queue
    -- is the first thing the mentor view shows.
    "owner_id"      bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "subject"       varchar(255) NOT NULL,
    "body"          text NOT NULL,
    -- low | normal | high | urgent -- drives the SLA below.
    "priority"      varchar(20) NOT NULL DEFAULT 'normal',
    -- open | assigned | answered | resolved | closed
    "status"        varchar(20) NOT NULL DEFAULT 'open',
    -- Stored on the ticket rather than looked up from settings, so changing the
    -- policy tomorrow does not silently re-date every ticket raised yesterday.
    "sla_minutes"   integer NOT NULL DEFAULT 1440,
    "due_at"        timestamptz NOT NULL,
    "first_response_at" timestamptz,
    "resolved_at"   timestamptz,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    "updated_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_tickets_queue_idx
  ON public."onyx_tickets" ("tenant_id", "status", "due_at");
CREATE INDEX IF NOT EXISTS onyx_tickets_owner_idx
  ON public."onyx_tickets" ("tenant_id", "owner_id", "status");

-- Every hand-off, in order. "Who was it with when it went past its SLA" is the
-- question an escalation path exists to answer, and a status column alone
-- cannot answer it.
CREATE TABLE IF NOT EXISTS public."onyx_ticket_events" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "ticket_id"   bigint NOT NULL REFERENCES public."onyx_tickets"("id") ON DELETE CASCADE,
    "actor_id"    bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    -- raised | assigned | responded | escalated | resolved | reopened | commented
    "kind"        varchar(30) NOT NULL,
    "note"        text,
    "detail"      jsonb NOT NULL DEFAULT '{}'::jsonb,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_ticket_events_ticket_idx
  ON public."onyx_ticket_events" ("tenant_id", "ticket_id", "created_at");

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_discussions', 'onyx_discussion_posts', 'onyx_discussion_mentions',
    'onyx_tickets', 'onyx_ticket_events'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- A course discussion is meant to be read by the course. The API is what knows
-- whether the reader is enrolled; this is the tenant floor beneath it.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['onyx_discussions', 'onyx_discussion_posts'] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated '
      || 'USING ("tenant_id" = onyx.current_tenant_id())', t || '_tenant_read', t);
  END LOOP;
END $$;

-- A mention is addressed to one person, and a ticket is somebody's problem
-- rather than the cohort's. Both are readable by whoever they belong to.
CREATE POLICY "onyx_discussion_mentions_owner_read" ON public."onyx_discussion_mentions"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id() AND "user_id" = onyx.current_user_id());

CREATE POLICY "onyx_tickets_owner_read" ON public."onyx_tickets"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND ("raised_by" = onyx.current_user_id() OR "owner_id" = onyx.current_user_id()));

-- Deliberately NO policy on onyx_ticket_events: the trail includes triage notes
-- written between staff about a learner's problem, which is not the learner's
-- to read even though the ticket is theirs.

NOTIFY pgrst, 'reload schema';
