-- Onyx 0008_campus.sql -- CMP-01 .. CMP-04.
--
-- "Run the institution, not just the courses: academic administration,
-- examinations, fees and a window for parents."
--
-- This is the sprint where the software starts producing documents people act
-- on outside it -- a seating plan pinned to a hall door, a transcript sent to
-- an employer, an invoice somebody pays. That changes what the schema owes:
--
--   * **A clash is a constraint, not a warning.** A double-booked room and a
--     learner sitting two exams at once are both refused, and the refusal names
--     what it collided with. Uniqueness that can be expressed in the database
--     is expressed there, because a check that lives only in a service is one
--     import away from being bypassed.
--   * **A transcript is a snapshot with a checksum.** It is issued once and
--     read later, possibly after the marks behind it have been moderated. It
--     stores what it said and a hash of it, so "does this reconcile with the
--     marks" is a question with an answer rather than an assumption.
--   * **Money is idempotent or it is wrong.** A gateway replays webhooks; that
--     is normal operation, not an attack. The unique key on the gateway
--     reference is what makes a replay a no-op.
--   * **Consent is a column.** A guardian sees what the learner has agreed to
--     share, per category, and the default is nothing.

-- ---------------------------------------------------------------------------
-- CMP-01a: faculty allocation
--
-- onyx_course_faculty (O02) already says who teaches a course. This is the
-- other question -- what is this person's load this term -- which the timetable
-- and the console both need and neither can derive from a join table.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_faculty_allocations" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "semester_id" bigint NOT NULL REFERENCES public."onyx_semesters"("id") ON DELETE CASCADE,
    "course_id"   bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "batch_id"    bigint REFERENCES public."onyx_batches"("id") ON DELETE SET NULL,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- lead | assistant | lab
    "kind"        varchar(20) NOT NULL DEFAULT 'lead',
    "hours_per_week" integer NOT NULL DEFAULT 0,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_faculty_allocations_unique
      UNIQUE ("tenant_id", "semester_id", "course_id", "batch_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_faculty_allocations_person_idx
  ON public."onyx_faculty_allocations" ("tenant_id", "user_id", "semester_id");

-- ---------------------------------------------------------------------------
-- CMP-01b: rooms and timetables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_rooms" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "code"       varchar(40) NOT NULL,
    "name"       varchar(255) NOT NULL,
    "capacity"   integer NOT NULL DEFAULT 0,
    -- lecture | lab | seminar | hall
    "kind"       varchar(20) NOT NULL DEFAULT 'lecture',
    "building"   varchar(120),
    "status"     smallint NOT NULL DEFAULT 1,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_rooms_code_unique UNIQUE ("tenant_id", "code")
);

CREATE TABLE IF NOT EXISTS public."onyx_timetable_slots" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "semester_id" bigint NOT NULL REFERENCES public."onyx_semesters"("id") ON DELETE CASCADE,
    "course_id"   bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    "batch_id"    bigint NOT NULL REFERENCES public."onyx_batches"("id") ON DELETE CASCADE,
    "room_id"     bigint NOT NULL REFERENCES public."onyx_rooms"("id") ON DELETE CASCADE,
    "faculty_id"  bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- 1 = Monday .. 7 = Sunday, ISO. Stored as a number because a timetable
    -- repeats weekly; a date would make every week its own row.
    "day_of_week" smallint NOT NULL,
    -- Local wall-clock time at the institution. A timetable is read off a wall,
    -- and a room does not move between time zones.
    "starts_at"   time NOT NULL,
    "ends_at"     time NOT NULL,
    -- draft | published. Clashes are checked on both, but only a published
    -- timetable is shown to learners.
    "status"      varchar(20) NOT NULL DEFAULT 'draft',
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_timetable_slots_day CHECK ("day_of_week" BETWEEN 1 AND 7),
    CONSTRAINT onyx_timetable_slots_order CHECK ("ends_at" > "starts_at")
);

CREATE INDEX IF NOT EXISTS onyx_timetable_slots_room_idx
  ON public."onyx_timetable_slots" ("tenant_id", "semester_id", "room_id", "day_of_week");
CREATE INDEX IF NOT EXISTS onyx_timetable_slots_faculty_idx
  ON public."onyx_timetable_slots" ("tenant_id", "semester_id", "faculty_id", "day_of_week");
CREATE INDEX IF NOT EXISTS onyx_timetable_slots_batch_idx
  ON public."onyx_timetable_slots" ("tenant_id", "semester_id", "batch_id", "day_of_week");

-- ---------------------------------------------------------------------------
-- CMP-02a: the exam calendar
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_exams" (
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"     bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "semester_id"   bigint NOT NULL REFERENCES public."onyx_semesters"("id") ON DELETE CASCADE,
    "course_id"     bigint NOT NULL REFERENCES public."onyx_courses"("id") ON DELETE CASCADE,
    -- An on-screen paper from O04, when the exam is sat in the product rather
    -- than on paper in a hall. Nullable: most terminal exams are not.
    "assessment_id" bigint REFERENCES public."onyx_assessments"("id") ON DELETE SET NULL,
    "title"         varchar(255) NOT NULL,
    "starts_at"     timestamptz NOT NULL,
    "duration_minutes" integer NOT NULL DEFAULT 180,
    "max_marks"     integer NOT NULL DEFAULT 100,
    "pass_marks"    integer NOT NULL DEFAULT 40,
    -- draft | scheduled | completed | cancelled
    "status"        varchar(20) NOT NULL DEFAULT 'draft',
    "created_by"    bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at"    timestamptz NOT NULL DEFAULT now(),
    "updated_at"    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_exams_calendar_idx
  ON public."onyx_exams" ("tenant_id", "semester_id", "starts_at");

-- ---------------------------------------------------------------------------
-- CMP-02b: halls and seating
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_halls" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "code"       varchar(40) NOT NULL,
    "name"       varchar(255) NOT NULL,
    -- The grid a seat label is built from: R3C7 is row 3, column 7.
    "row_count"  integer NOT NULL DEFAULT 1,
    "col_count"  integer NOT NULL DEFAULT 1,
    -- Usable seats, which is not rows x columns once a hall leaves gaps for
    -- invigilators to walk. Allocation stops at this number.
    "capacity"   integer NOT NULL DEFAULT 0,
    "status"     smallint NOT NULL DEFAULT 1,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_halls_code_unique UNIQUE ("tenant_id", "code")
);

CREATE TABLE IF NOT EXISTS public."onyx_seat_allocations" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "exam_id"    bigint NOT NULL REFERENCES public."onyx_exams"("id") ON DELETE CASCADE,
    "hall_id"    bigint NOT NULL REFERENCES public."onyx_halls"("id") ON DELETE CASCADE,
    "user_id"    bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "seat_label" varchar(20) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- The acceptance criterion, in two constraints: "every candidate has
    -- exactly one seat and no seat is double-allocated". Both are in the
    -- database because a seating plan is printed and then trusted.
    CONSTRAINT onyx_seat_allocations_one_seat_per_person
      UNIQUE ("tenant_id", "exam_id", "user_id"),
    CONSTRAINT onyx_seat_allocations_one_person_per_seat
      UNIQUE ("tenant_id", "exam_id", "hall_id", "seat_label")
);

CREATE INDEX IF NOT EXISTS onyx_seat_allocations_hall_idx
  ON public."onyx_seat_allocations" ("tenant_id", "exam_id", "hall_id");

-- ---------------------------------------------------------------------------
-- CMP-02c: marks, moderation and transcripts
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_exam_marks" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "exam_id"     bigint NOT NULL REFERENCES public."onyx_exams"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- What the marker put down, before anybody moderated it. Kept separate from
    -- the delta so a moderated paper can always show both numbers.
    "raw_marks"   numeric(6,2) NOT NULL DEFAULT 0,
    "moderation_delta" numeric(6,2) NOT NULL DEFAULT 0,
    -- raw + delta, written by the service so a transcript is one read.
    "final_marks" numeric(6,2) NOT NULL DEFAULT 0,
    "grade"       varchar(4),
    "grade_points" numeric(4,2),
    -- entered | moderated | published. A learner sees nothing until published.
    "status"      varchar(20) NOT NULL DEFAULT 'entered',
    "entered_by"  bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "moderated_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "moderated_at" timestamptz,
    "published_at" timestamptz,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_exam_marks_unique UNIQUE ("tenant_id", "exam_id", "user_id")
);

CREATE INDEX IF NOT EXISTS onyx_exam_marks_person_idx
  ON public."onyx_exam_marks" ("tenant_id", "user_id", "status");

CREATE TABLE IF NOT EXISTS public."onyx_transcripts" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "program_id"  bigint REFERENCES public."onyx_programs"("id") ON DELETE SET NULL,
    "serial"      varchar(64) NOT NULL,
    -- The marks as they stood when it was issued. A transcript that recomputed
    -- itself would quietly disagree with the copy already in someone's hands.
    "payload"     jsonb NOT NULL DEFAULT '{}'::jsonb,
    "gpa"         numeric(4,2),
    "credits_earned" integer NOT NULL DEFAULT 0,
    -- SHA-256 over the canonicalised payload. This is what makes "reconciles
    -- with the marks behind it" checkable rather than asserted.
    "checksum"    varchar(64) NOT NULL,
    "issued_by"   bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "issued_at"   timestamptz NOT NULL DEFAULT now(),
    "revoked_at"  timestamptz,
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_transcripts_serial_unique UNIQUE ("serial")
);

CREATE INDEX IF NOT EXISTS onyx_transcripts_person_idx
  ON public."onyx_transcripts" ("tenant_id", "user_id", "issued_at" DESC);

-- ---------------------------------------------------------------------------
-- CMP-03a: fee heads, structures and invoices
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_fee_heads" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "code"       varchar(40) NOT NULL,
    "name"       varchar(255) NOT NULL,
    -- tuition | exam | hostel | transport | library | misc
    "category"   varchar(30) NOT NULL DEFAULT 'tuition',
    -- Whether a waiver may be applied to this head at all. Some heads are
    -- statutory and are not the institution's to discount.
    "refundable" boolean NOT NULL DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_fee_heads_code_unique UNIQUE ("tenant_id", "code")
);

CREATE TABLE IF NOT EXISTS public."onyx_fee_structures" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "program_id"  bigint REFERENCES public."onyx_programs"("id") ON DELETE CASCADE,
    "semester_id" bigint REFERENCES public."onyx_semesters"("id") ON DELETE CASCADE,
    "name"        varchar(255) NOT NULL,
    "currency"    varchar(3) NOT NULL DEFAULT 'INR',
    -- Instalments the total is split across. One means pay it all at once.
    "instalments" integer NOT NULL DEFAULT 1,
    -- draft | published. Publishing freezes it: an invoice already raised must
    -- keep reconciling to the lines that produced it.
    "status"      varchar(20) NOT NULL DEFAULT 'draft',
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    "updated_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."onyx_fee_structure_lines" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "structure_id" bigint NOT NULL REFERENCES public."onyx_fee_structures"("id") ON DELETE CASCADE,
    "head_id"      bigint NOT NULL REFERENCES public."onyx_fee_heads"("id") ON DELETE RESTRICT,
    -- Money in minor units (paise), as an integer. A rupee amount in a float
    -- is a rounding error waiting for a reconciliation report to find it.
    "amount_minor" bigint NOT NULL DEFAULT 0,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_fee_structure_lines_unique UNIQUE ("tenant_id", "structure_id", "head_id")
);

CREATE TABLE IF NOT EXISTS public."onyx_invoices" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"      bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "structure_id" bigint REFERENCES public."onyx_fee_structures"("id") ON DELETE SET NULL,
    "number"       varchar(64) NOT NULL,
    "instalment_no" integer NOT NULL DEFAULT 1,
    "currency"     varchar(3) NOT NULL DEFAULT 'INR',
    "total_minor"  bigint NOT NULL DEFAULT 0,
    "paid_minor"   bigint NOT NULL DEFAULT 0,
    -- issued | part_paid | paid | void
    "status"       varchar(20) NOT NULL DEFAULT 'issued',
    "due_at"       timestamptz,
    "issued_at"    timestamptz NOT NULL DEFAULT now(),
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_invoices_number_unique UNIQUE ("tenant_id", "number")
);

CREATE INDEX IF NOT EXISTS onyx_invoices_person_idx
  ON public."onyx_invoices" ("tenant_id", "user_id", "status");

-- The lines are copied from the structure at issue time rather than joined at
-- read time. This is what "an invoice's lines reconcile to the fee structure
-- that produced it" means once the structure is allowed to change.
CREATE TABLE IF NOT EXISTS public."onyx_invoice_lines" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "invoice_id"  bigint NOT NULL REFERENCES public."onyx_invoices"("id") ON DELETE CASCADE,
    "head_id"     bigint REFERENCES public."onyx_fee_heads"("id") ON DELETE SET NULL,
    "description" varchar(255) NOT NULL,
    "amount_minor" bigint NOT NULL DEFAULT 0,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_invoice_lines_invoice_idx
  ON public."onyx_invoice_lines" ("tenant_id", "invoice_id");

-- ---------------------------------------------------------------------------
-- CMP-03b: payment and reconciliation
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_payments" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"   bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "invoice_id"  bigint NOT NULL REFERENCES public."onyx_invoices"("id") ON DELETE CASCADE,
    "user_id"     bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "gateway"     varchar(30) NOT NULL DEFAULT 'manual',
    -- The gateway's own id for the transaction. UNIQUE per tenant, and that
    -- constraint is the whole of "a replayed webhook never double-credits an
    -- invoice" -- a second insert with the same reference cannot happen, so a
    -- replay is a lookup rather than a credit.
    "reference"   varchar(191) NOT NULL,
    "amount_minor" bigint NOT NULL DEFAULT 0,
    "currency"    varchar(3) NOT NULL DEFAULT 'INR',
    -- pending | captured | failed | refunded
    "status"      varchar(20) NOT NULL DEFAULT 'pending',
    "method"      varchar(30),
    -- The webhook body as received. Reconciliation reads this, not our summary
    -- of it, when the two disagree.
    "raw"         jsonb NOT NULL DEFAULT '{}'::jsonb,
    "captured_at" timestamptz,
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_payments_reference_unique UNIQUE ("tenant_id", "gateway", "reference")
);

CREATE INDEX IF NOT EXISTS onyx_payments_invoice_idx
  ON public."onyx_payments" ("tenant_id", "invoice_id", "status");

-- ---------------------------------------------------------------------------
-- CMP-04a: guardians
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public."onyx_guardians" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"    bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    -- The guardian's own account, with a `guardian` membership. They log in as
    -- themselves; a shared login with the learner would make consent meaningless.
    "guardian_user_id" bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "student_user_id"  bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "relationship" varchar(40) NOT NULL DEFAULT 'guardian',
    -- Consent, per category, granted by the learner. Default false throughout:
    -- linking a guardian shows them nothing until the learner says otherwise.
    "can_view_attendance" boolean NOT NULL DEFAULT false,
    "can_view_results"    boolean NOT NULL DEFAULT false,
    "can_view_fees"       boolean NOT NULL DEFAULT false,
    -- Set when the learner accepts the link. An unverified link is a request.
    "verified_at"  timestamptz,
    "created_at"   timestamptz NOT NULL DEFAULT now(),
    "updated_at"   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_guardians_unique
      UNIQUE ("tenant_id", "guardian_user_id", "student_user_id"),
    CONSTRAINT onyx_guardians_not_self CHECK ("guardian_user_id" <> "student_user_id")
);

CREATE INDEX IF NOT EXISTS onyx_guardians_student_idx
  ON public."onyx_guardians" ("tenant_id", "student_user_id");

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_faculty_allocations', 'onyx_rooms', 'onyx_timetable_slots',
    'onyx_exams', 'onyx_halls', 'onyx_seat_allocations',
    'onyx_exam_marks', 'onyx_transcripts',
    'onyx_fee_heads', 'onyx_fee_structures', 'onyx_fee_structure_lines',
    'onyx_invoices', 'onyx_invoice_lines', 'onyx_payments', 'onyx_guardians'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- Institutional furniture: which rooms and halls exist, and what is scheduled.
-- Knowing the timetable is the point of publishing it.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['onyx_rooms', 'onyx_halls', 'onyx_exams'] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated '
      || 'USING ("tenant_id" = onyx.current_tenant_id())', t || '_tenant_read', t);
  END LOOP;
END $$;

CREATE POLICY "onyx_timetable_slots_published_read" ON public."onyx_timetable_slots"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id() AND "status" = 'published');

-- A person's own record. Marks only once published -- an entered mark is a
-- draft, and a moderated one is under discussion.
CREATE POLICY "onyx_exam_marks_owner_read" ON public."onyx_exam_marks"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND "user_id" = onyx.current_user_id()
     AND "status" = 'published');

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'onyx_transcripts', 'onyx_invoices', 'onyx_payments', 'onyx_seat_allocations'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated '
      || 'USING ("tenant_id" = onyx.current_tenant_id() '
      || 'AND "user_id" = onyx.current_user_id())', t || '_owner_read', t);
  END LOOP;
END $$;

-- Both sides of a guardian link may see the link itself. What the link GRANTS
-- is decided by the API against the consent columns, not here -- a guardian
-- reading their child's marks goes through a check this policy cannot express.
CREATE POLICY "onyx_guardians_party_read" ON public."onyx_guardians"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id()
     AND ("guardian_user_id" = onyx.current_user_id()
       OR "student_user_id" = onyx.current_user_id()));

-- Deliberately NO policy on onyx_fee_heads, onyx_fee_structures,
-- onyx_fee_structure_lines, onyx_invoice_lines, onyx_faculty_allocations:
-- what an institution charges, what it waives and what it pays its staff are
-- the finance and registry offices' business, served through the API to the
-- roles that hold it. A learner reads their own invoice, not the price list.

NOTIFY pgrst, 'reload schema';
