-- Onyx 0009_platform.sql -- the operator who sits above every institution.
--
-- Every table so far is tenant-scoped by design (0001's whole point). A
-- platform admin is the one deliberate exception: someone who did not sign up
-- to run one institution, but to run the service every institution sits on --
-- creating tenants without going through public signup, suspending one that
-- has stopped paying or started misbehaving, and being able to look at all of
-- them without pretending to be a member of each.
--
-- Three things keep that power from being the isolation model's weak point:
--
--   * **It is a grant, not a flag.** `onyx_platform_admins` is a table with a
--     row per admin and who granted it, not a boolean on onyx_users. A row
--     can be listed, audited and revoked; a column can only be toggled.
--   * **The token is a different shape, not a wider one.** A platform token
--     carries no tenant_id at all -- see onyx/auth.ts. requireOnyx() rejects a
--     token with no tenant_id outright, so a platform token is *structurally*
--     unable to pass as a tenant token. There is no claim to widen, because
--     the two never share a code path.
--   * **RLS still denies by default.** Platform routes read through the
--     service-role client, the same as tenant creation already does -- not
--     through a policy that grants "everything to platform admins", which
--     would be one bug away from granting everything to everyone.

CREATE TABLE IF NOT EXISTS public."onyx_platform_admins" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id"    bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    "granted_by" bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_platform_admins_user_unique UNIQUE ("user_id")
);

-- A trail of what happened at the platform level -- a tenant created outside
-- self-service, suspended, or reactivated; an admin granted or revoked. Kept
-- apart from onyx_audit_logs because that table's tenant_id is NOT NULL by
-- design (0001): an audit row is always one institution's history, and
-- "grant Dana platform admin" is nobody's institution's history.
CREATE TABLE IF NOT EXISTS public."onyx_platform_audit_logs" (
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "actor_id"    bigint REFERENCES public."onyx_users"("id") ON DELETE SET NULL,
    "action"      varchar(100) NOT NULL,
    "entity_type" varchar(50) NOT NULL,
    "entity_id"   bigint,
    "before"      jsonb,
    "after"       jsonb,
    "ip"          varchar(64),
    "created_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS onyx_platform_audit_logs_created_idx
  ON public."onyx_platform_audit_logs" ("created_at" DESC);

-- Both are exempt from tenant scoping for the same reason onyx_tenants and
-- onyx_users are: they exist ABOVE the tenant boundary, not inside one.
-- Redefined here (CREATE OR REPLACE) rather than left for these two tables to
-- fail assert_tenant_scoped() and look like a bug every run after this one.
CREATE OR REPLACE FUNCTION onyx.assert_tenant_scoped() RETURNS TABLE(missing text)
  LANGUAGE sql STABLE AS $$
    SELECT c.relname::text
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND c.relname LIKE 'onyx\_%'
      AND c.relname NOT IN (
        'onyx_tenants', 'onyx_users', 'onyx_schema_migrations',
        'onyx_platform_admins', 'onyx_platform_audit_logs'
      )
      AND NOT EXISTS (
        SELECT 1 FROM pg_attribute a
        WHERE a.attrelid = c.oid AND a.attname = 'tenant_id' AND a.attnum > 0
          AND NOT a.attisdropped
      )
  $$;

-- ---------------------------------------------------------------------------
-- Row level security -- deny-all. Every read here goes through the
-- service-role client behind requirePlatformAdmin(), never through a caller's
-- own token: there is no tenant claim a platform token could be checked
-- against, so a permissive policy here would have to trust the JWT's own
-- unverified say-so that it is a platform token, which is exactly the kind of
-- policy that becomes "trust the client" the first time someone forges one.
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['onyx_platform_admins', 'onyx_platform_audit_logs'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';
