-- Onyx 0010_gateways.sql -- CMP-03b, paying an invoice online.
--
-- The ledger side of finance was already right: `onyx_payments` is unique on
-- (tenant_id, gateway, reference), so a replayed webhook is a lookup rather
-- than a second credit. What was missing was everything before that row
-- exists -- a learner could be invoiced and had no way to pay, because nothing
-- could start a checkout and no gateway credentials existed to start one with.
--
-- **Why not the port's `payment_gateways` table.** It is one row per gateway
-- for the whole deployment, which is right for a single storefront and wrong
-- here: two institutions on the same Onyx are two different merchants, with
-- two different settlement accounts, and sending Alpha University's fees to
-- Beta College's Razorpay account is not a bug anyone gets to explain twice.
-- So credentials are tenant-scoped, like everything else in Onyx.
--
-- **The keys column holds secrets.** It is never selected by a read path that
-- serves a caller: `GATEWAY_PUBLIC_COLUMNS` in finance.service.ts omits it,
-- and the admin screen shows only whether a key is set. RLS is deny-all with
-- no SELECT policy at all, so even a tenant's own token reading PostgREST
-- directly gets nothing -- the same treatment `onyx_audit_logs` gets, and for
-- the same reason.

CREATE TABLE IF NOT EXISTS public."onyx_payment_gateways" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    -- Matches the port's provider registry key: razorpay, stripe, paypal,
    -- paystack, flutterwave, sslcommerz, aamarpay, doku, maxicash.
    "identifier" varchar(30) NOT NULL,
    "title"      varchar(120) NOT NULL,
    -- Provider credentials as { "key": "value" }. Test and live pairs both
    -- live here; `test_mode` chooses, exactly as the port's models did.
    "keys"       jsonb NOT NULL DEFAULT '{}'::jsonb,
    "currency"   varchar(3) NOT NULL DEFAULT 'INR',
    "test_mode"  smallint NOT NULL DEFAULT 1,
    -- 0 disabled, 1 enabled. A disabled gateway keeps its credentials so
    -- turning it back on is not a re-entry of secrets.
    "status"     smallint NOT NULL DEFAULT 1,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    -- One configuration per gateway per institution. Two rows for the same
    -- provider would make "which credentials" a question with no answer.
    CONSTRAINT onyx_payment_gateways_unique UNIQUE ("tenant_id", "identifier")
);

CREATE INDEX IF NOT EXISTS onyx_payment_gateways_tenant_idx
  ON public."onyx_payment_gateways" ("tenant_id", "status");

-- ---------------------------------------------------------------------------
-- Row level security -- deny-all, and deliberately no read policy.
--
-- Every other tenant-scoped table gets a read policy so a learner's own token
-- can see their own rows. This one gets none: there is no row here a learner
-- has any business reading, and the column that matters holds live merchant
-- credentials. Reads go through the service-role client behind an admin guard.
-- ---------------------------------------------------------------------------

ALTER TABLE public."onyx_payment_gateways" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."onyx_payment_gateways" FORCE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
