-- Onyx 0011_notifications.sql -- telling people things.
--
-- Onyx had no way to tell anybody anything. Not a bug in one feature: there was
-- no outbound channel at all, and four requirement descriptions quietly assume
-- one --
--
--   * F-06  "create a tenant, seed its roles, INVITE the first admin"
--   * CAR-04a "employer records with contacts and an INVITATION flow"
--   * CMP-04a "guardian accounts ... plus NOTIFICATIONS on key events"
--   * LRN-06b "an escalated question REACHES A NAMED OWNER and its age is visible"
--
-- Each of those was, in practice, somebody being told out of band.
--
-- **Why a table and not just email.** Email is a delivery channel that fails --
-- an institution with no SMTP configured, a bounced address, a spam filter. The
-- record of "this person was told X" belongs in the database either way, so the
-- in-app inbox is the notification and email is a copy of it. That also means a
-- learner who never gets the mail still sees the thing when they next sign in,
-- which is the difference between a notification system and a mailing list.
--
-- **Read state is per person, not per notification.** One row per recipient
-- rather than one row plus a join table: a notification to forty guardians is
-- forty different things, each read or not, each possibly about a different
-- child. Fanning out at write time is the simpler half of that trade.

CREATE TABLE IF NOT EXISTS public."onyx_notifications" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    "user_id"    bigint NOT NULL REFERENCES public."onyx_users"("id") ON DELETE CASCADE,
    -- A closed vocabulary, like onyx_audit_logs.action, so the inbox can group
    -- and an operator can search. Enforced in the service, not by a constraint:
    -- a new kind should be a code change, not a migration.
    "kind"       varchar(50) NOT NULL,
    "title"      varchar(255) NOT NULL,
    "body"       text,
    -- Where this notification goes when clicked. Relative, always: an absolute
    -- URL in a notification is a redirect somebody else gets to choose.
    "link"       varchar(500),
    "read_at"    timestamptz,
    -- Whether a copy went out by email, and what happened. Null means it was
    -- never attempted; false means it was and did not land.
    "emailed"    smallint NOT NULL DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- The two reads this table gets: "my unread count" on every page load, and
-- "my inbox, newest first". Both are (tenant, user) with read_at deciding.
CREATE INDEX IF NOT EXISTS onyx_notifications_user_idx
  ON public."onyx_notifications" ("tenant_id", "user_id", "read_at", "created_at" DESC);

-- ---------------------------------------------------------------------------
-- Row level security.
--
-- Unlike most Onyx tables this one gets a read policy, because a notification
-- is the one kind of row whose whole purpose is to be read by exactly one
-- person -- and `user_id = onyx.current_user_id()` says that precisely. Writes
-- still go through the service role: nobody notifies themselves.
-- ---------------------------------------------------------------------------

ALTER TABLE public."onyx_notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."onyx_notifications" FORCE ROW LEVEL SECURITY;

CREATE POLICY "onyx_notifications_own_read" ON public."onyx_notifications"
  FOR SELECT TO authenticated
  USING ("tenant_id" = onyx.current_tenant_id() AND "user_id" = onyx.current_user_id());

NOTIFY pgrst, 'reload schema';
