-- Onyx 0013_auth_uuid_columns.sql -- GENERATED by tools/onyx/gen_uuid_migration.mjs
--
-- Supabase Auth migration, step 1/3 (additive, zero behavior change).
-- See docs/ADR-011-supabase-auth-migration.md.
--
-- Adds a uuid twin next to onyx_users' bigint id and every bigint column
-- that references it, so real auth.users rows can be provisioned and
-- backfilled (tools/onyx/provision-auth-users.mjs) and validated
-- (tools/onyx/validate-uuid-backfill.mjs) before anything old is touched.

ALTER TABLE public."onyx_users" ADD COLUMN IF NOT EXISTS "auth_id" uuid;
CREATE UNIQUE INDEX IF NOT EXISTS onyx_users_auth_id_unique
  ON public."onyx_users" ("auth_id") WHERE "auth_id" IS NOT NULL;

-- One uuid twin per bigint column that identifies a person (69 total).
ALTER TABLE public."onyx_assessment_attempts" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_assessment_grades" ADD COLUMN IF NOT EXISTS "marker_id_uuid" uuid;
ALTER TABLE public."onyx_assessments" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_assignment_submissions" ADD COLUMN IF NOT EXISTS "graded_by_uuid" uuid;
ALTER TABLE public."onyx_assignment_submissions" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_assignments" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_attendance_records" ADD COLUMN IF NOT EXISTS "marked_by_uuid" uuid;
ALTER TABLE public."onyx_attendance_records" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_attendance_sessions" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_audit_logs" ADD COLUMN IF NOT EXISTS "actor_id_uuid" uuid;
ALTER TABLE public."onyx_batch_members" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_certificates" ADD COLUMN IF NOT EXISTS "issued_by_uuid" uuid;
ALTER TABLE public."onyx_certificates" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_code_submissions" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_contest_members" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_contest_submissions" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_contest_teams" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_contests" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_course_faculty" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_courses" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_discussion_mentions" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_discussion_posts" ADD COLUMN IF NOT EXISTS "author_id_uuid" uuid;
ALTER TABLE public."onyx_discussions" ADD COLUMN IF NOT EXISTS "author_id_uuid" uuid;
ALTER TABLE public."onyx_discussions" ADD COLUMN IF NOT EXISTS "resolved_by_uuid" uuid;
ALTER TABLE public."onyx_drive_results" ADD COLUMN IF NOT EXISTS "recorded_by_uuid" uuid;
ALTER TABLE public."onyx_drive_results" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_drives" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_employers" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_employers" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_enrollments" ADD COLUMN IF NOT EXISTS "enrolled_by_uuid" uuid;
ALTER TABLE public."onyx_enrollments" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_exam_marks" ADD COLUMN IF NOT EXISTS "entered_by_uuid" uuid;
ALTER TABLE public."onyx_exam_marks" ADD COLUMN IF NOT EXISTS "moderated_by_uuid" uuid;
ALTER TABLE public."onyx_exam_marks" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_exams" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_faculty_allocations" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_guardians" ADD COLUMN IF NOT EXISTS "guardian_user_id_uuid" uuid;
ALTER TABLE public."onyx_guardians" ADD COLUMN IF NOT EXISTS "student_user_id_uuid" uuid;
ALTER TABLE public."onyx_hint_reveals" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_invoices" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_job_applications" ADD COLUMN IF NOT EXISTS "decided_by_uuid" uuid;
ALTER TABLE public."onyx_job_applications" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_jobs_posted" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_learner_skills" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_lesson_progress" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_memberships" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_mock_interviews" ADD COLUMN IF NOT EXISTS "interviewer_id_uuid" uuid;
ALTER TABLE public."onyx_mock_interviews" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_notifications" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_payments" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_platform_admins" ADD COLUMN IF NOT EXISTS "granted_by_uuid" uuid;
ALTER TABLE public."onyx_platform_admins" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_platform_audit_logs" ADD COLUMN IF NOT EXISTS "actor_id_uuid" uuid;
ALTER TABLE public."onyx_problems" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_proctor_events" ADD COLUMN IF NOT EXISTS "reviewed_by_uuid" uuid;
ALTER TABLE public."onyx_question_banks" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_questions" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_readiness_scores" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_resources" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_seat_allocations" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_ticket_events" ADD COLUMN IF NOT EXISTS "actor_id_uuid" uuid;
ALTER TABLE public."onyx_tickets" ADD COLUMN IF NOT EXISTS "owner_id_uuid" uuid;
ALTER TABLE public."onyx_tickets" ADD COLUMN IF NOT EXISTS "raised_by_uuid" uuid;
ALTER TABLE public."onyx_timetable_slots" ADD COLUMN IF NOT EXISTS "faculty_id_uuid" uuid;
ALTER TABLE public."onyx_transcripts" ADD COLUMN IF NOT EXISTS "issued_by_uuid" uuid;
ALTER TABLE public."onyx_transcripts" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;
ALTER TABLE public."onyx_workspace_comments" ADD COLUMN IF NOT EXISTS "author_id_uuid" uuid;
ALTER TABLE public."onyx_workspace_snapshots" ADD COLUMN IF NOT EXISTS "created_by_uuid" uuid;
ALTER TABLE public."onyx_workspaces" ADD COLUMN IF NOT EXISTS "user_id_uuid" uuid;

NOTIFY pgrst, 'reload schema';
