-- Onyx 0014_auth_uuid_cutover.sql -- GENERATED by tools/onyx/gen_uuid_migration.mjs
--
-- Supabase Auth migration, step 2/3 (DESTRUCTIVE -- drops the old bigint
-- identity columns). Do not apply until tools/onyx/validate-uuid-backfill.mjs
-- has exited 0 against this database. See docs/ADR-011-supabase-auth-migration.md.
--
-- Column NAMES are unchanged throughout (only types change). Policy BODIES
-- don't need editing either, except the 25 below that Postgres
-- itself refuses to let the column drops proceed past (a policy holds a
-- hard dependency on the exact column it reads, confirmed live against
-- this project) -- those are dropped first and recreated at the end,
-- identically except for the one new helper function.

-- Step 0: drop every policy that depends on a column about to be dropped
-- (Postgres refuses the drop otherwise). Recreated as Step E, once the
-- columns they read exist again under their new type.
DROP POLICY "onyx_assessment_attempts_owner_read" ON public."onyx_assessment_attempts";
DROP POLICY "onyx_assignment_submissions_owner_read" ON public."onyx_assignment_submissions";
DROP POLICY "onyx_attendance_records_owner_read" ON public."onyx_attendance_records";
DROP POLICY "onyx_certificates_owner_read" ON public."onyx_certificates";
DROP POLICY "onyx_code_submissions_owner_read" ON public."onyx_code_submissions";
DROP POLICY "onyx_discussion_mentions_owner_read" ON public."onyx_discussion_mentions";
DROP POLICY "onyx_drive_results_owner_read" ON public."onyx_drive_results";
DROP POLICY "onyx_enrollments_owner_read" ON public."onyx_enrollments";
DROP POLICY "onyx_exam_marks_owner_read" ON public."onyx_exam_marks";
DROP POLICY "onyx_guardians_party_read" ON public."onyx_guardians";
DROP POLICY "onyx_hint_reveals_owner_read" ON public."onyx_hint_reveals";
DROP POLICY "onyx_invoices_owner_read" ON public."onyx_invoices";
DROP POLICY "onyx_job_applications_owner_read" ON public."onyx_job_applications";
DROP POLICY "onyx_learner_skills_owner_read" ON public."onyx_learner_skills";
DROP POLICY "onyx_lesson_progress_owner_read" ON public."onyx_lesson_progress";
DROP POLICY "onyx_mock_interviews_owner_read" ON public."onyx_mock_interviews";
DROP POLICY "onyx_notifications_own_read" ON public."onyx_notifications";
DROP POLICY "onyx_payments_owner_read" ON public."onyx_payments";
DROP POLICY "onyx_readiness_scores_owner_read" ON public."onyx_readiness_scores";
DROP POLICY "onyx_seat_allocations_owner_read" ON public."onyx_seat_allocations";
DROP POLICY "onyx_tickets_owner_read" ON public."onyx_tickets";
DROP POLICY "onyx_transcripts_owner_read" ON public."onyx_transcripts";
DROP POLICY "users_same_tenant_read" ON public."onyx_users";
DROP POLICY "onyx_workspace_files_owner_read" ON public."onyx_workspace_files";
DROP POLICY "onyx_workspaces_owner_read" ON public."onyx_workspaces";

-- Step A: drop every old bigint FK column. This also drops each column's
-- own FK constraint into onyx_users(id), which is what lets onyx_users'
-- own old bigint id be dropped next without a dependency error.
ALTER TABLE public."onyx_assessment_attempts" DROP COLUMN "user_id";
ALTER TABLE public."onyx_assessment_grades" DROP COLUMN "marker_id";
ALTER TABLE public."onyx_assessments" DROP COLUMN "created_by";
ALTER TABLE public."onyx_assignment_submissions" DROP COLUMN "graded_by";
ALTER TABLE public."onyx_assignment_submissions" DROP COLUMN "user_id";
ALTER TABLE public."onyx_assignments" DROP COLUMN "created_by";
ALTER TABLE public."onyx_attendance_records" DROP COLUMN "marked_by";
ALTER TABLE public."onyx_attendance_records" DROP COLUMN "user_id";
ALTER TABLE public."onyx_attendance_sessions" DROP COLUMN "created_by";
ALTER TABLE public."onyx_audit_logs" DROP COLUMN "actor_id";
ALTER TABLE public."onyx_batch_members" DROP COLUMN "user_id";
ALTER TABLE public."onyx_certificates" DROP COLUMN "issued_by";
ALTER TABLE public."onyx_certificates" DROP COLUMN "user_id";
ALTER TABLE public."onyx_code_submissions" DROP COLUMN "user_id";
ALTER TABLE public."onyx_contest_members" DROP COLUMN "user_id";
ALTER TABLE public."onyx_contest_submissions" DROP COLUMN "user_id";
ALTER TABLE public."onyx_contest_teams" DROP COLUMN "created_by";
ALTER TABLE public."onyx_contests" DROP COLUMN "created_by";
ALTER TABLE public."onyx_course_faculty" DROP COLUMN "user_id";
ALTER TABLE public."onyx_courses" DROP COLUMN "created_by";
ALTER TABLE public."onyx_discussion_mentions" DROP COLUMN "user_id";
ALTER TABLE public."onyx_discussion_posts" DROP COLUMN "author_id";
ALTER TABLE public."onyx_discussions" DROP COLUMN "author_id";
ALTER TABLE public."onyx_discussions" DROP COLUMN "resolved_by";
ALTER TABLE public."onyx_drive_results" DROP COLUMN "recorded_by";
ALTER TABLE public."onyx_drive_results" DROP COLUMN "user_id";
ALTER TABLE public."onyx_drives" DROP COLUMN "created_by";
ALTER TABLE public."onyx_employers" DROP COLUMN "created_by";
ALTER TABLE public."onyx_employers" DROP COLUMN "user_id";
ALTER TABLE public."onyx_enrollments" DROP COLUMN "enrolled_by";
ALTER TABLE public."onyx_enrollments" DROP COLUMN "user_id";
ALTER TABLE public."onyx_exam_marks" DROP COLUMN "entered_by";
ALTER TABLE public."onyx_exam_marks" DROP COLUMN "moderated_by";
ALTER TABLE public."onyx_exam_marks" DROP COLUMN "user_id";
ALTER TABLE public."onyx_exams" DROP COLUMN "created_by";
ALTER TABLE public."onyx_faculty_allocations" DROP COLUMN "user_id";
ALTER TABLE public."onyx_guardians" DROP COLUMN "guardian_user_id";
ALTER TABLE public."onyx_guardians" DROP COLUMN "student_user_id";
ALTER TABLE public."onyx_hint_reveals" DROP COLUMN "user_id";
ALTER TABLE public."onyx_invoices" DROP COLUMN "user_id";
ALTER TABLE public."onyx_job_applications" DROP COLUMN "decided_by";
ALTER TABLE public."onyx_job_applications" DROP COLUMN "user_id";
ALTER TABLE public."onyx_jobs_posted" DROP COLUMN "created_by";
ALTER TABLE public."onyx_learner_skills" DROP COLUMN "user_id";
ALTER TABLE public."onyx_lesson_progress" DROP COLUMN "user_id";
ALTER TABLE public."onyx_memberships" DROP COLUMN "user_id";
ALTER TABLE public."onyx_mock_interviews" DROP COLUMN "interviewer_id";
ALTER TABLE public."onyx_mock_interviews" DROP COLUMN "user_id";
ALTER TABLE public."onyx_notifications" DROP COLUMN "user_id";
ALTER TABLE public."onyx_payments" DROP COLUMN "user_id";
ALTER TABLE public."onyx_platform_admins" DROP COLUMN "granted_by";
ALTER TABLE public."onyx_platform_admins" DROP COLUMN "user_id";
ALTER TABLE public."onyx_platform_audit_logs" DROP COLUMN "actor_id";
ALTER TABLE public."onyx_problems" DROP COLUMN "created_by";
ALTER TABLE public."onyx_proctor_events" DROP COLUMN "reviewed_by";
ALTER TABLE public."onyx_question_banks" DROP COLUMN "created_by";
ALTER TABLE public."onyx_questions" DROP COLUMN "created_by";
ALTER TABLE public."onyx_readiness_scores" DROP COLUMN "user_id";
ALTER TABLE public."onyx_resources" DROP COLUMN "created_by";
ALTER TABLE public."onyx_seat_allocations" DROP COLUMN "user_id";
ALTER TABLE public."onyx_ticket_events" DROP COLUMN "actor_id";
ALTER TABLE public."onyx_tickets" DROP COLUMN "owner_id";
ALTER TABLE public."onyx_tickets" DROP COLUMN "raised_by";
ALTER TABLE public."onyx_timetable_slots" DROP COLUMN "faculty_id";
ALTER TABLE public."onyx_transcripts" DROP COLUMN "issued_by";
ALTER TABLE public."onyx_transcripts" DROP COLUMN "user_id";
ALTER TABLE public."onyx_workspace_comments" DROP COLUMN "author_id";
ALTER TABLE public."onyx_workspace_snapshots" DROP COLUMN "created_by";
ALTER TABLE public."onyx_workspaces" DROP COLUMN "user_id";

-- Step B: onyx_users -- auth_id (already populated by provision-auth-users.mjs)
-- becomes the real primary key. Credentials move to auth.users, so
-- password is dropped rather than carried forward.
ALTER TABLE public."onyx_users" DROP CONSTRAINT onyx_users_pkey;
ALTER TABLE public."onyx_users" DROP COLUMN "password";
ALTER TABLE public."onyx_users" DROP COLUMN "id";
ALTER TABLE public."onyx_users" RENAME COLUMN "auth_id" TO "id";
ALTER TABLE public."onyx_users" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE public."onyx_users" ADD PRIMARY KEY ("id");
ALTER TABLE public."onyx_users" ADD CONSTRAINT onyx_users_id_fkey
  FOREIGN KEY ("id") REFERENCES auth.users("id") ON DELETE CASCADE;

-- Step C: promote every uuid twin in place, restoring the nullability,
-- ON DELETE behavior, uniqueness and lookup indexes the old column had.
ALTER TABLE public."onyx_assessment_attempts" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_assessment_attempts" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_assessment_attempts" ADD CONSTRAINT onyx_assessment_attempts_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
CREATE INDEX onyx_assessment_attempts_user_idx ON public."onyx_assessment_attempts" ("user_id");
ALTER TABLE public."onyx_assessment_grades" RENAME COLUMN "marker_id_uuid" TO "marker_id";
ALTER TABLE public."onyx_assessment_grades" ADD CONSTRAINT onyx_assessment_grades_marker_id_fkey FOREIGN KEY ("marker_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_assessments" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_assessments" ADD CONSTRAINT onyx_assessments_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_assignment_submissions" RENAME COLUMN "graded_by_uuid" TO "graded_by";
ALTER TABLE public."onyx_assignment_submissions" ADD CONSTRAINT onyx_assignment_submissions_graded_by_fkey FOREIGN KEY ("graded_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_assignment_submissions" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_assignment_submissions" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_assignment_submissions" ADD CONSTRAINT onyx_assignment_submissions_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
CREATE INDEX onyx_assignment_submissions_user_idx ON public."onyx_assignment_submissions" ("user_id");
ALTER TABLE public."onyx_assignments" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_assignments" ADD CONSTRAINT onyx_assignments_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_attendance_records" RENAME COLUMN "marked_by_uuid" TO "marked_by";
ALTER TABLE public."onyx_attendance_records" ADD CONSTRAINT onyx_attendance_records_marked_by_fkey FOREIGN KEY ("marked_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_attendance_records" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_attendance_records" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_attendance_records" ADD CONSTRAINT onyx_attendance_records_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
CREATE INDEX onyx_attendance_records_user_idx ON public."onyx_attendance_records" ("user_id");
ALTER TABLE public."onyx_attendance_sessions" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_attendance_sessions" ADD CONSTRAINT onyx_attendance_sessions_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_audit_logs" RENAME COLUMN "actor_id_uuid" TO "actor_id";
ALTER TABLE public."onyx_audit_logs" ADD CONSTRAINT onyx_audit_logs_actor_id_fkey FOREIGN KEY ("actor_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_batch_members" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_batch_members" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_batch_members" ADD CONSTRAINT onyx_batch_members_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
CREATE INDEX onyx_batch_members_user_idx ON public."onyx_batch_members" ("user_id");
ALTER TABLE public."onyx_certificates" RENAME COLUMN "issued_by_uuid" TO "issued_by";
ALTER TABLE public."onyx_certificates" ADD CONSTRAINT onyx_certificates_issued_by_fkey FOREIGN KEY ("issued_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_certificates" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_certificates" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_certificates" ADD CONSTRAINT onyx_certificates_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_code_submissions" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_code_submissions" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_code_submissions" ADD CONSTRAINT onyx_code_submissions_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_contest_members" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_contest_members" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_contest_members" ADD CONSTRAINT onyx_contest_members_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_contest_submissions" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_contest_submissions" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_contest_submissions" ADD CONSTRAINT onyx_contest_submissions_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_contest_teams" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_contest_teams" ADD CONSTRAINT onyx_contest_teams_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_contests" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_contests" ADD CONSTRAINT onyx_contests_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_course_faculty" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_course_faculty" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_course_faculty" ADD CONSTRAINT onyx_course_faculty_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_courses" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_courses" ADD CONSTRAINT onyx_courses_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_discussion_mentions" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_discussion_mentions" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_discussion_mentions" ADD CONSTRAINT onyx_discussion_mentions_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_discussion_posts" RENAME COLUMN "author_id_uuid" TO "author_id";
ALTER TABLE public."onyx_discussion_posts" ALTER COLUMN "author_id" SET NOT NULL;
ALTER TABLE public."onyx_discussion_posts" ADD CONSTRAINT onyx_discussion_posts_author_id_fkey FOREIGN KEY ("author_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_discussions" RENAME COLUMN "author_id_uuid" TO "author_id";
ALTER TABLE public."onyx_discussions" ALTER COLUMN "author_id" SET NOT NULL;
ALTER TABLE public."onyx_discussions" ADD CONSTRAINT onyx_discussions_author_id_fkey FOREIGN KEY ("author_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_discussions" RENAME COLUMN "resolved_by_uuid" TO "resolved_by";
ALTER TABLE public."onyx_discussions" ADD CONSTRAINT onyx_discussions_resolved_by_fkey FOREIGN KEY ("resolved_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_drive_results" RENAME COLUMN "recorded_by_uuid" TO "recorded_by";
ALTER TABLE public."onyx_drive_results" ADD CONSTRAINT onyx_drive_results_recorded_by_fkey FOREIGN KEY ("recorded_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_drive_results" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_drive_results" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_drive_results" ADD CONSTRAINT onyx_drive_results_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_drives" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_drives" ADD CONSTRAINT onyx_drives_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_employers" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_employers" ADD CONSTRAINT onyx_employers_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_employers" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_employers" ADD CONSTRAINT onyx_employers_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_enrollments" RENAME COLUMN "enrolled_by_uuid" TO "enrolled_by";
ALTER TABLE public."onyx_enrollments" ADD CONSTRAINT onyx_enrollments_enrolled_by_fkey FOREIGN KEY ("enrolled_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_enrollments" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_enrollments" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_enrollments" ADD CONSTRAINT onyx_enrollments_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
CREATE INDEX onyx_enrollments_user_idx ON public."onyx_enrollments" ("user_id");
ALTER TABLE public."onyx_exam_marks" RENAME COLUMN "entered_by_uuid" TO "entered_by";
ALTER TABLE public."onyx_exam_marks" ADD CONSTRAINT onyx_exam_marks_entered_by_fkey FOREIGN KEY ("entered_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_exam_marks" RENAME COLUMN "moderated_by_uuid" TO "moderated_by";
ALTER TABLE public."onyx_exam_marks" ADD CONSTRAINT onyx_exam_marks_moderated_by_fkey FOREIGN KEY ("moderated_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_exam_marks" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_exam_marks" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_exam_marks" ADD CONSTRAINT onyx_exam_marks_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_exams" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_exams" ADD CONSTRAINT onyx_exams_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_faculty_allocations" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_faculty_allocations" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_faculty_allocations" ADD CONSTRAINT onyx_faculty_allocations_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_guardians" RENAME COLUMN "guardian_user_id_uuid" TO "guardian_user_id";
ALTER TABLE public."onyx_guardians" ALTER COLUMN "guardian_user_id" SET NOT NULL;
ALTER TABLE public."onyx_guardians" ADD CONSTRAINT onyx_guardians_guardian_user_id_fkey FOREIGN KEY ("guardian_user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_guardians" RENAME COLUMN "student_user_id_uuid" TO "student_user_id";
ALTER TABLE public."onyx_guardians" ALTER COLUMN "student_user_id" SET NOT NULL;
ALTER TABLE public."onyx_guardians" ADD CONSTRAINT onyx_guardians_student_user_id_fkey FOREIGN KEY ("student_user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_hint_reveals" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_hint_reveals" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_hint_reveals" ADD CONSTRAINT onyx_hint_reveals_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_invoices" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_invoices" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_invoices" ADD CONSTRAINT onyx_invoices_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_job_applications" RENAME COLUMN "decided_by_uuid" TO "decided_by";
ALTER TABLE public."onyx_job_applications" ADD CONSTRAINT onyx_job_applications_decided_by_fkey FOREIGN KEY ("decided_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_job_applications" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_job_applications" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_job_applications" ADD CONSTRAINT onyx_job_applications_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_jobs_posted" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_jobs_posted" ADD CONSTRAINT onyx_jobs_posted_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_learner_skills" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_learner_skills" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_learner_skills" ADD CONSTRAINT onyx_learner_skills_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_lesson_progress" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_lesson_progress" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_lesson_progress" ADD CONSTRAINT onyx_lesson_progress_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_memberships" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_memberships" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_memberships" ADD CONSTRAINT onyx_memberships_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
CREATE INDEX onyx_memberships_user_idx ON public."onyx_memberships" ("user_id");
ALTER TABLE public."onyx_mock_interviews" RENAME COLUMN "interviewer_id_uuid" TO "interviewer_id";
ALTER TABLE public."onyx_mock_interviews" ADD CONSTRAINT onyx_mock_interviews_interviewer_id_fkey FOREIGN KEY ("interviewer_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_mock_interviews" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_mock_interviews" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_mock_interviews" ADD CONSTRAINT onyx_mock_interviews_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_notifications" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_notifications" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_notifications" ADD CONSTRAINT onyx_notifications_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_payments" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_payments" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_payments" ADD CONSTRAINT onyx_payments_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_platform_admins" RENAME COLUMN "granted_by_uuid" TO "granted_by";
ALTER TABLE public."onyx_platform_admins" ADD CONSTRAINT onyx_platform_admins_granted_by_fkey FOREIGN KEY ("granted_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_platform_admins" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_platform_admins" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_platform_admins" ADD CONSTRAINT onyx_platform_admins_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_platform_admins" ADD CONSTRAINT onyx_platform_admins_user_id_fkey_key UNIQUE ("user_id");
ALTER TABLE public."onyx_platform_audit_logs" RENAME COLUMN "actor_id_uuid" TO "actor_id";
ALTER TABLE public."onyx_platform_audit_logs" ADD CONSTRAINT onyx_platform_audit_logs_actor_id_fkey FOREIGN KEY ("actor_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_problems" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_problems" ADD CONSTRAINT onyx_problems_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_proctor_events" RENAME COLUMN "reviewed_by_uuid" TO "reviewed_by";
ALTER TABLE public."onyx_proctor_events" ADD CONSTRAINT onyx_proctor_events_reviewed_by_fkey FOREIGN KEY ("reviewed_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_question_banks" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_question_banks" ADD CONSTRAINT onyx_question_banks_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_questions" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_questions" ADD CONSTRAINT onyx_questions_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_readiness_scores" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_readiness_scores" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_readiness_scores" ADD CONSTRAINT onyx_readiness_scores_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_resources" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_resources" ADD CONSTRAINT onyx_resources_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_seat_allocations" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_seat_allocations" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_seat_allocations" ADD CONSTRAINT onyx_seat_allocations_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_ticket_events" RENAME COLUMN "actor_id_uuid" TO "actor_id";
ALTER TABLE public."onyx_ticket_events" ADD CONSTRAINT onyx_ticket_events_actor_id_fkey FOREIGN KEY ("actor_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_tickets" RENAME COLUMN "owner_id_uuid" TO "owner_id";
ALTER TABLE public."onyx_tickets" ADD CONSTRAINT onyx_tickets_owner_id_fkey FOREIGN KEY ("owner_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_tickets" RENAME COLUMN "raised_by_uuid" TO "raised_by";
ALTER TABLE public."onyx_tickets" ALTER COLUMN "raised_by" SET NOT NULL;
ALTER TABLE public."onyx_tickets" ADD CONSTRAINT onyx_tickets_raised_by_fkey FOREIGN KEY ("raised_by") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_timetable_slots" RENAME COLUMN "faculty_id_uuid" TO "faculty_id";
ALTER TABLE public."onyx_timetable_slots" ALTER COLUMN "faculty_id" SET NOT NULL;
ALTER TABLE public."onyx_timetable_slots" ADD CONSTRAINT onyx_timetable_slots_faculty_id_fkey FOREIGN KEY ("faculty_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_transcripts" RENAME COLUMN "issued_by_uuid" TO "issued_by";
ALTER TABLE public."onyx_transcripts" ADD CONSTRAINT onyx_transcripts_issued_by_fkey FOREIGN KEY ("issued_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_transcripts" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_transcripts" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_transcripts" ADD CONSTRAINT onyx_transcripts_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
ALTER TABLE public."onyx_workspace_comments" RENAME COLUMN "author_id_uuid" TO "author_id";
ALTER TABLE public."onyx_workspace_comments" ADD CONSTRAINT onyx_workspace_comments_author_id_fkey FOREIGN KEY ("author_id") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_workspace_snapshots" RENAME COLUMN "created_by_uuid" TO "created_by";
ALTER TABLE public."onyx_workspace_snapshots" ADD CONSTRAINT onyx_workspace_snapshots_created_by_fkey FOREIGN KEY ("created_by") REFERENCES public."onyx_users"("id") ON DELETE SET NULL;
ALTER TABLE public."onyx_workspaces" RENAME COLUMN "user_id_uuid" TO "user_id";
ALTER TABLE public."onyx_workspaces" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE public."onyx_workspaces" ADD CONSTRAINT onyx_workspaces_user_id_fkey FOREIGN KEY ("user_id") REFERENCES public."onyx_users"("id") ON DELETE CASCADE;
CREATE INDEX onyx_workspaces_user_idx ON public."onyx_workspaces" ("user_id");

-- Step D: onyx.current_user_id() is shared with the legacy port's own RLS
-- (cart_items, wishlists, messages, etc -- still bigint-keyed, out of
-- scope here) and Postgres refuses to change a function's return type
-- while any policy depends on it, so it is left untouched. A new
-- function carries the uuid semantics instead, for the policies below
-- that used the old one.
CREATE FUNCTION onyx.current_auth_user_id() RETURNS uuid
  LANGUAGE sql STABLE AS $$ SELECT auth.uid() $$;

-- Step E: recreate the 25 policies Step 0 dropped, now that the
-- columns they read exist again (as uuid). Identical to their prior
-- definition except calls to current_user_id() rebind to the new function
-- above -- everything else, including plain column comparisons like
-- users_same_tenant_read's, is byte-for-byte the same text as before.
CREATE POLICY "onyx_assessment_attempts_owner_read" ON public."onyx_assessment_attempts" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_assignment_submissions_owner_read" ON public."onyx_assignment_submissions" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_attendance_records_owner_read" ON public."onyx_attendance_records" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_certificates_owner_read" ON public."onyx_certificates" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_code_submissions_owner_read" ON public."onyx_code_submissions" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_discussion_mentions_owner_read" ON public."onyx_discussion_mentions" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_drive_results_owner_read" ON public."onyx_drive_results" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_enrollments_owner_read" ON public."onyx_enrollments" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_exam_marks_owner_read" ON public."onyx_exam_marks" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id()) AND ((status)::text = 'published'::text)));
CREATE POLICY "onyx_guardians_party_read" ON public."onyx_guardians" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND ((guardian_user_id = onyx.current_auth_user_id()) OR (student_user_id = onyx.current_auth_user_id()))));
CREATE POLICY "onyx_hint_reveals_owner_read" ON public."onyx_hint_reveals" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_invoices_owner_read" ON public."onyx_invoices" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_job_applications_owner_read" ON public."onyx_job_applications" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_learner_skills_owner_read" ON public."onyx_learner_skills" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_lesson_progress_owner_read" ON public."onyx_lesson_progress" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_mock_interviews_owner_read" ON public."onyx_mock_interviews" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_notifications_own_read" ON public."onyx_notifications" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_payments_owner_read" ON public."onyx_payments" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_readiness_scores_owner_read" ON public."onyx_readiness_scores" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_seat_allocations_owner_read" ON public."onyx_seat_allocations" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "onyx_tickets_owner_read" ON public."onyx_tickets" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND ((raised_by = onyx.current_auth_user_id()) OR (owner_id = onyx.current_auth_user_id()))));
CREATE POLICY "onyx_transcripts_owner_read" ON public."onyx_transcripts" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));
CREATE POLICY "users_same_tenant_read" ON public."onyx_users" FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM onyx_memberships m
  WHERE ((m.user_id = onyx_users.id) AND (m.tenant_id = onyx.current_tenant_id())))));
CREATE POLICY "onyx_workspace_files_owner_read" ON public."onyx_workspace_files" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM onyx_workspaces w
  WHERE ((w.id = onyx_workspace_files.workspace_id) AND (w.user_id = onyx.current_auth_user_id()))))));
CREATE POLICY "onyx_workspaces_owner_read" ON public."onyx_workspaces" FOR SELECT TO authenticated USING (((tenant_id = onyx.current_tenant_id()) AND (user_id = onyx.current_auth_user_id())));

NOTIFY pgrst, 'reload schema';
