-- Onyx 0038_sections.sql -- the division a learner is actually taught in.
--
-- Every institution using this product splits a year group into sections and
-- runs them separately: Alpha, Beta and Gamma at Malla Reddy; Section A, B and
-- C nearly everywhere else. Timetables are drawn per section, examinations are
-- sat per section, and "which section is this student in" is the first thing
-- anybody in a programme office asks. The product had no idea the concept
-- existed.
--
-- **Why not batches, which are already here.** `onyx_batches` is a programme
-- cohort -- "B.Tech CSE 2024" -- keyed to a programme and a year, and joined
-- through `onyx_batch_members`. A section is a division WITHIN that: the same
-- batch of three hundred is taught as three sections of a hundred, and a
-- learner belongs to exactly one of them at a time. Modelling sections as
-- batches would make a learner a member of two cohorts with no way to say
-- which one is their teaching group, and would put "Alpha" in a list whose
-- other entries are degree programmes.
--
-- So: a small table per institution, and one nullable column on the membership.
--
-- **Nullable, on purpose, in three places.**
--
--   * `onyx_memberships.section_id` -- staff have no section, and neither does
--     a learner registered before this existed or one whose institution has
--     not set any up. A NOT NULL column would have needed a fabricated
--     "unassigned" row that every query then has to special-case.
--   * `onyx_assessments.section_id` and `onyx_exams.section_id` -- NULL means
--     the whole cohort, which is the common case and must stay the default. A
--     paper for one section names it; a paper for everybody says nothing,
--     exactly as it did before this migration. That way every row already in
--     these tables keeps its current meaning without being rewritten.
--
-- `ON DELETE SET NULL` throughout rather than CASCADE: removing a section must
-- never take a learner's membership or a sat examination with it. A section
-- that is dissolved leaves its people unassigned and its papers open to
-- everybody, both of which are recoverable by hand; the alternative is not.

CREATE TABLE IF NOT EXISTS public."onyx_sections" (
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id"  bigint NOT NULL REFERENCES public."onyx_tenants"("id") ON DELETE CASCADE,
    -- What it is called on screen: "Alpha", "Section A".
    "name"       varchar(80) NOT NULL,
    -- The short form a timetable or a hall ticket prints: "alpha", "a".
    -- Lower-cased by the service so "A" and "a" cannot both exist.
    "code"       varchar(20) NOT NULL,
    -- Teaching order, so Alpha/Beta/Gamma read in that order rather than
    -- alphabetically or by whichever was created first.
    "sort"       smallint NOT NULL DEFAULT 0,
    -- 1 live, 0 retired. Retired rather than deleted, because a section that
    -- has examinations against it is part of the record of who sat what.
    "status"     smallint NOT NULL DEFAULT 1,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    CONSTRAINT onyx_sections_code_unique UNIQUE ("tenant_id", "code")
);

CREATE INDEX IF NOT EXISTS "onyx_sections_tenant_sort"
    ON public."onyx_sections" ("tenant_id", "sort", "id");

ALTER TABLE public."onyx_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."onyx_sections" FORCE ROW LEVEL SECURITY;

-- The learner's own section. One at a time: a person is taught in one group.
ALTER TABLE public."onyx_memberships"
  ADD COLUMN IF NOT EXISTS "section_id" bigint
  REFERENCES public."onyx_sections"("id") ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "onyx_memberships_section"
    ON public."onyx_memberships" ("tenant_id", "section_id");

-- Who a paper is set for. NULL is every section, which is what every existing
-- row means and must keep meaning.
ALTER TABLE public."onyx_assessments"
  ADD COLUMN IF NOT EXISTS "section_id" bigint
  REFERENCES public."onyx_sections"("id") ON DELETE SET NULL;

ALTER TABLE public."onyx_exams"
  ADD COLUMN IF NOT EXISTS "section_id" bigint
  REFERENCES public."onyx_sections"("id") ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "onyx_assessments_section"
    ON public."onyx_assessments" ("tenant_id", "section_id");

CREATE INDEX IF NOT EXISTS "onyx_exams_section"
    ON public."onyx_exams" ("tenant_id", "section_id");

COMMENT ON COLUMN public."onyx_memberships"."section_id" IS
  'The teaching division this person is in. NULL for staff and for anybody not assigned.';
COMMENT ON COLUMN public."onyx_assessments"."section_id" IS
  'The section this paper is set for. NULL means every section.';
COMMENT ON COLUMN public."onyx_exams"."section_id" IS
  'The section this sitting is for. NULL means every section.';
