// database.ts -- GENERATED by tools/gen_types.py. DO NOT EDIT BY HAND.
//
// Shape-compatible with `supabase gen types typescript`, so once the Supabase
// project exists (F-02) this file can be produced by the CLI instead with zero
// changes to consuming code.
//
// NOTE: columns that store JSON as TEXT are typed `string` here on purpose --
// that is their real storage type. Parse them with the Zod schemas in
// ./json-columns.ts, never with a bare JSON.parse.

export type Json = string | number | boolean | null | { [k: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: {
      applications: {
        Row: {
          id: number
          user_id: number | null
          phone: string | null
          description: string | null
          document: string | null
          status: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          phone?: string | null
          description?: string | null
          document?: string | null
          status?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['applications']['Insert']>
        Relationships: []
      }
      blog_categories: {
        Row: {
          id: number
          title: string
          subtitle: string | null
          slug: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          title: string
          subtitle?: string | null
          slug: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['blog_categories']['Insert']>
        Relationships: []
      }
      blog_comments: {
        Row: {
          id: number
          blog_id: number | null
          user_id: number | null
          parent_id: number | null
          check: number | null
          comment: string | null
          likes: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          blog_id?: number | null
          user_id?: number | null
          parent_id?: number | null
          check?: number | null
          comment?: string | null
          likes?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['blog_comments']['Insert']>
        Relationships: []
      }
      blog_likes: {
        Row: {
          id: number
          blog_id: number | null
          user_id: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          blog_id?: number | null
          user_id?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['blog_likes']['Insert']>
        Relationships: []
      }
      blogs: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
          category_id: number | null
          user_id: number | null
          title: string | null
          slug: string | null
          keywords: string | null
          description: string | null
          thumbnail: string | null
          banner: string | null
          is_popular: number
          status: number
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
          category_id?: number | null
          user_id?: number | null
          title?: string | null
          slug?: string | null
          keywords?: string | null
          description?: string | null
          thumbnail?: string | null
          banner?: string | null
          is_popular?: number
          status?: number
        }
        Update: Partial<Database['public']['Tables']['blogs']['Insert']>
        Relationships: []
      }
      bootcamp_categories: {
        Row: {
          id: number
          title: string
          slug: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          title: string
          slug: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['bootcamp_categories']['Insert']>
        Relationships: []
      }
      bootcamp_live_classes: {
        Row: {
          id: number
          module_id: number
          title: string
          slug: string | null
          description: string | null
          start_time: number | null
          end_time: number | null
          sort: number
          status: number
          provider: string | null
          joining_data: string | null  /** JSON-as-text */
          force_stop: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          module_id: number
          title: string
          slug?: string | null
          description?: string | null
          start_time?: number | null
          end_time?: number | null
          sort?: number
          status?: number
          provider?: string | null
          joining_data?: string | null
          force_stop?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['bootcamp_live_classes']['Insert']>
        Relationships: []
      }
      bootcamp_modules: {
        Row: {
          id: number
          bootcamp_id: number
          title: string
          publish_date: number | null
          expiry_date: number | null
          restriction: string | null
          sort: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          bootcamp_id: number
          title: string
          publish_date?: number | null
          expiry_date?: number | null
          restriction?: string | null
          sort?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['bootcamp_modules']['Insert']>
        Relationships: []
      }
      bootcamp_purchases: {
        Row: {
          id: number
          bootcamp_id: number
          user_id: number
          price: number
          admin_revenue: number
          instructor_revenue: number
          payment_type: string | null
          payment_info: string | null
          transaction_id: string | null
          status: number
          created_at: string | null
          updated_at: string | null
          invoice: string | null
          tax: number
          payment_method: string | null
        }
        Insert: {
          id?: number
          bootcamp_id: number
          user_id: number
          price?: number
          admin_revenue?: number
          instructor_revenue?: number
          payment_type?: string | null
          payment_info?: string | null
          transaction_id?: string | null
          status?: number
          created_at?: string | null
          updated_at?: string | null
          invoice?: string | null
          tax?: number
          payment_method?: string | null
        }
        Update: Partial<Database['public']['Tables']['bootcamp_purchases']['Insert']>
        Relationships: []
      }
      bootcamp_resources: {
        Row: {
          id: number
          module_id: number | null
          title: string | null
          upload_type: string | null
          file: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          module_id?: number | null
          title?: string | null
          upload_type?: string | null
          file?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['bootcamp_resources']['Insert']>
        Relationships: []
      }
      bootcamps: {
        Row: {
          id: number
          user_id: number | null
          category_id: number | null
          title: string | null
          slug: string | null
          short_description: string | null
          description: string | null
          is_paid: number
          price: number | null
          discount_flag: number
          discounted_price: number | null
          publish_date: number | null
          thumbnail: string | null
          faqs: string | null
          requirements: string | null
          outcomes: string | null
          meta_keywords: string | null
          meta_description: string | null
          status: number
          pending: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          category_id?: number | null
          title?: string | null
          slug?: string | null
          short_description?: string | null
          description?: string | null
          is_paid?: number
          price?: number | null
          discount_flag?: number
          discounted_price?: number | null
          publish_date?: number | null
          thumbnail?: string | null
          faqs?: string | null
          requirements?: string | null
          outcomes?: string | null
          meta_keywords?: string | null
          meta_description?: string | null
          status?: number
          pending?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['bootcamps']['Insert']>
        Relationships: []
      }
      builder_pages: {
        Row: {
          id: number
          is_permanent: number | null
          edit_home_id: number | null
          identifier: string | null
          name: string | null
          html: string | null
          status: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          is_permanent?: number | null
          edit_home_id?: number | null
          identifier?: string | null
          name?: string | null
          html?: string | null
          status?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['builder_pages']['Insert']>
        Relationships: []
      }
      cart_items: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['cart_items']['Insert']>
        Relationships: []
      }
      categories: {
        Row: {
          id: number
          parent_id: number
          title: string | null
          slug: string | null
          icon: string | null
          sort: number
          status: number | null
          keywords: string | null
          description: string | null
          thumbnail: string | null
          category_logo: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          parent_id?: number
          title?: string | null
          slug?: string | null
          icon?: string | null
          sort?: number
          status?: number | null
          keywords?: string | null
          description?: string | null
          thumbnail?: string | null
          category_logo?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['categories']['Insert']>
        Relationships: []
      }
      certificates: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          identifier: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          identifier: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['certificates']['Insert']>
        Relationships: []
      }
      contacts: {
        Row: {
          id: number
          name: string | null
          email: string | null
          phone: string | null
          address: string | null
          message: string | null
          has_read: number | null
          replied: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          name?: string | null
          email?: string | null
          phone?: string | null
          address?: string | null
          message?: string | null
          has_read?: number | null
          replied?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['contacts']['Insert']>
        Relationships: []
      }
      coupons: {
        Row: {
          id: number
          user_id: number | null
          code: string | null
          discount: number | null
          expiry: string | null
          created_at: string | null
          updated_at: string | null
          status: string
        }
        Insert: {
          id?: number
          user_id?: number | null
          code?: string | null
          discount?: number | null
          expiry?: string | null
          created_at?: string | null
          updated_at?: string | null
          status?: string
        }
        Update: Partial<Database['public']['Tables']['coupons']['Insert']>
        Relationships: []
      }
      course_approval_requests: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          message: string | null
          read_status: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          message?: string | null
          read_status?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['course_approval_requests']['Insert']>
        Relationships: []
      }
      courses: {
        Row: {
          id: number
          title: string | null
          slug: string | null
          short_description: string | null
          user_id: number | null
          category_id: number | null
          course_type: string | null
          status: string | null
          level: string | null
          language: string | null
          is_paid: number | null
          price: number | null
          discount_flag: number | null
          discounted_price: number | null
          meta_keywords: string | null
          meta_description: string | null
          thumbnail: string | null
          banner: string | null
          preview: string | null
          description: string | null
          requirements: string | null
          outcomes: string | null
          faqs: string | null
          instructor_ids: string | null  /** JSON-as-text */
          created_at: string | null
          updated_at: string | null
          enable_drip_content: number
          drip_content_settings: string | null  /** JSON-as-text */
          expiry_period: number | null
        }
        Insert: {
          id?: number
          title?: string | null
          slug?: string | null
          short_description?: string | null
          user_id?: number | null
          category_id?: number | null
          course_type?: string | null
          status?: string | null
          level?: string | null
          language?: string | null
          is_paid?: number | null
          price?: number | null
          discount_flag?: number | null
          discounted_price?: number | null
          meta_keywords?: string | null
          meta_description?: string | null
          thumbnail?: string | null
          banner?: string | null
          preview?: string | null
          description?: string | null
          requirements?: string | null
          outcomes?: string | null
          faqs?: string | null
          instructor_ids?: string | null
          created_at?: string | null
          updated_at?: string | null
          enable_drip_content?: number
          drip_content_settings?: string | null
          expiry_period?: number | null
        }
        Update: Partial<Database['public']['Tables']['courses']['Insert']>
        Relationships: []
      }
      device_ips: {
        Row: {
          id: number
          user_id: number
          ip_address: string | null
          session_id: string | null
          user_agent: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id: number
          ip_address?: string | null
          session_id?: string | null
          user_agent?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['device_ips']['Insert']>
        Relationships: []
      }
      enrollments: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          enrollment_type: string | null
          expiry_date: string | null
          created_at: string | null
          updated_at: string | null
          entry_date: number | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          enrollment_type?: string | null
          expiry_date?: string | null
          created_at?: string | null
          updated_at?: string | null
          entry_date?: number | null
        }
        Update: Partial<Database['public']['Tables']['enrollments']['Insert']>
        Relationships: []
      }
      failed_jobs: {
        Row: {
          id: number
          uuid: string
          connection: string
          queue: string
          payload: string
          exception: string
          failed_at: string
        }
        Insert: {
          id?: number
          uuid: string
          connection: string
          queue: string
          payload: string
          exception: string
          failed_at?: string
        }
        Update: Partial<Database['public']['Tables']['failed_jobs']['Insert']>
        Relationships: []
      }
      forums: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          parent_id: number
          title: string | null
          description: string | null
          likes: string | null
          dislikes: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          parent_id?: number
          title?: string | null
          description?: string | null
          likes?: string | null
          dislikes?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['forums']['Insert']>
        Relationships: []
      }
      instructor_reviews: {
        Row: {
          id: number
          user_id: number | null
          instructor_id: number | null
          rating: string | null
          review: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          instructor_id?: number | null
          rating?: string | null
          review?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['instructor_reviews']['Insert']>
        Relationships: []
      }
      knowledge_base_topicks: {
        Row: {
          id: number
          knowledge_base_id: number
          topic_name: string
          description: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          knowledge_base_id: number
          topic_name: string
          description: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['knowledge_base_topicks']['Insert']>
        Relationships: []
      }
      knowledge_bases: {
        Row: {
          id: number
          title: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          title: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['knowledge_bases']['Insert']>
        Relationships: []
      }
      language_phrases: {
        Row: {
          id: number
          language_id: number | null
          phrase: string | null
          translated: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          language_id?: number | null
          phrase?: string | null
          translated?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['language_phrases']['Insert']>
        Relationships: []
      }
      languages: {
        Row: {
          id: number
          name: string
          direction: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          name: string
          direction: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['languages']['Insert']>
        Relationships: []
      }
      lessons: {
        Row: {
          id: number
          title: string | null
          user_id: number | null
          course_id: number | null
          section_id: number | null
          lesson_type: string | null
          duration: string | null
          lesson_src: string | null
          thumbnail: string | null
          is_free: number | null
          sort: number | null
          description: string | null
          status: number | null
          created_at: string | null
          updated_at: string | null
          summary: string | null
          attachment: string | null
          attachment_type: string | null
          video_type: string | null
          total_mark: number | null
          pass_mark: number | null
          retake: number | null
        }
        Insert: {
          id?: number
          title?: string | null
          user_id?: number | null
          course_id?: number | null
          section_id?: number | null
          lesson_type?: string | null
          duration?: string | null
          lesson_src?: string | null
          thumbnail?: string | null
          is_free?: number | null
          sort?: number | null
          description?: string | null
          status?: number | null
          created_at?: string | null
          updated_at?: string | null
          summary?: string | null
          attachment?: string | null
          attachment_type?: string | null
          video_type?: string | null
          total_mark?: number | null
          pass_mark?: number | null
          retake?: number | null
        }
        Update: Partial<Database['public']['Tables']['lessons']['Insert']>
        Relationships: []
      }
      like_dislike_reviews: {
        Row: {
          id: number
          review_id: number | null
          user_id: number | null
          liked: number
          disliked: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          review_id?: number | null
          user_id?: number | null
          liked?: number
          disliked?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['like_dislike_reviews']['Insert']>
        Relationships: []
      }
      live_classes: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          class_topic: string | null
          provider: string | null
          class_date_and_time: string | null
          additional_info: string | null  /** JSON-as-text */
          note: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          class_topic?: string | null
          provider?: string | null
          class_date_and_time?: string | null
          additional_info?: string | null
          note?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['live_classes']['Insert']>
        Relationships: []
      }
      media_files: {
        Row: {
          id: number
          user_id: number | null
          post_id: number | null
          story_id: number | null
          album_id: number | null
          product_id: number | null
          page_id: number | null
          group_id: number | null
          chat_id: number | null
          file_name: string | null
          file_type: string | null
          privacy: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          post_id?: number | null
          story_id?: number | null
          album_id?: number | null
          product_id?: number | null
          page_id?: number | null
          group_id?: number | null
          chat_id?: number | null
          file_name?: string | null
          file_type?: string | null
          privacy?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['media_files']['Insert']>
        Relationships: []
      }
      message_threads: {
        Row: {
          id: number
          code: string
          contact_one: number
          contact_two: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          code: string
          contact_one: number
          contact_two: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['message_threads']['Insert']>
        Relationships: []
      }
      messages: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
          thread_id: number
          sender_id: number
          receiver_id: number
          message: string | null
          read: number
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
          thread_id: number
          sender_id: number
          receiver_id: number
          message?: string | null
          read?: number
        }
        Update: Partial<Database['public']['Tables']['messages']['Insert']>
        Relationships: []
      }
      migrations: {
        Row: {
          id: number
          migration: string
          batch: number
        }
        Insert: {
          id?: number
          migration: string
          batch: number
        }
        Update: Partial<Database['public']['Tables']['migrations']['Insert']>
        Relationships: []
      }
      newsletter_subscribers: {
        Row: {
          id: number
          email: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          email: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['newsletter_subscribers']['Insert']>
        Relationships: []
      }
      newsletters: {
        Row: {
          id: number
          subject: string | null
          description: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          subject?: string | null
          description?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['newsletters']['Insert']>
        Relationships: []
      }
      notifications: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
        Relationships: []
      }
      offline_payments: {
        Row: {
          id: number
          user_id: number | null
          items: string | null  /** JSON-as-text */
          tax: number | null
          total_amount: number | null
          phone_on: string | null
          bank_no: string | null
          doc: string | null
          status: number
          created_at: string | null
          updated_at: string | null
          item_type: string | null
          coupon: string | null
          payable_amount: number | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          items?: string | null
          tax?: number | null
          total_amount?: number | null
          phone_on?: string | null
          bank_no?: string | null
          doc?: string | null
          status?: number
          created_at?: string | null
          updated_at?: string | null
          item_type?: string | null
          coupon?: string | null
          payable_amount?: number | null
        }
        Update: Partial<Database['public']['Tables']['offline_payments']['Insert']>
        Relationships: []
      }
      password_reset_tokens: {
        Row: {
          email: string
          token: string
          created_at: string | null
        }
        Insert: {
          email?: string
          token: string
          created_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['password_reset_tokens']['Insert']>
        Relationships: []
      }
      payment_gateways: {
        Row: {
          id: number
          identifier: string | null
          title: string | null
          keys: string | null  /** JSON-as-text */
          description: string | null
          status: number
          test_mode: number
          is_addon: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          identifier?: string | null
          title?: string | null
          keys?: string | null
          description?: string | null
          status?: number
          test_mode?: number
          is_addon?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['payment_gateways']['Insert']>
        Relationships: []
      }
      payment_histories: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          payment_type: string | null
          amount: number | null
          admin_revenue: number | null
          instructor_revenue: number | null
          tax: number | null
          coupon: string | null
          invoice: string | null
          instructor_payment_status: number | null
          transaction_id: string | null
          session_id: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          payment_type?: string | null
          amount?: number | null
          admin_revenue?: number | null
          instructor_revenue?: number | null
          tax?: number | null
          coupon?: string | null
          invoice?: string | null
          instructor_payment_status?: number | null
          transaction_id?: string | null
          session_id?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['payment_histories']['Insert']>
        Relationships: []
      }
      payouts: {
        Row: {
          id: number
          user_id: number
          amount: number
          status: number
          payment_method: string | null
          payment_details: string | null  /** JSON-as-text */
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id: number
          amount?: number
          status?: number
          payment_method?: string | null
          payment_details?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['payouts']['Insert']>
        Relationships: []
      }
      permissions: {
        Row: {
          id: number
          admin_id: number
          permissions: string | null  /** JSON-as-text */
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          admin_id: number
          permissions?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['permissions']['Insert']>
        Relationships: []
      }
      personal_access_tokens: {
        Row: {
          id: number
          tokenable_type: string
          tokenable_id: number
          name: string
          token: string
          abilities: string | null
          last_used_at: string | null
          expires_at: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          tokenable_type: string
          tokenable_id: number
          name: string
          token: string
          abilities?: string | null
          last_used_at?: string | null
          expires_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['personal_access_tokens']['Insert']>
        Relationships: []
      }
      player_settings: {
        Row: {
          id: number
          title: string
          description: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          title: string
          description?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['player_settings']['Insert']>
        Relationships: []
      }
      questions: {
        Row: {
          id: number
          quiz_id: number | null
          title: string | null
          type: string | null
          answer: string | null  /** JSON-as-text */
          options: string | null  /** JSON-as-text */
          sort: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          quiz_id?: number | null
          title?: string | null
          type?: string | null
          answer?: string | null
          options?: string | null
          sort?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['questions']['Insert']>
        Relationships: []
      }
      quiz_submissions: {
        Row: {
          id: number
          quiz_id: number | null
          user_id: number | null
          correct_answer: string | null
          wrong_answer: string | null
          submits: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          quiz_id?: number | null
          user_id?: number | null
          correct_answer?: string | null
          wrong_answer?: string | null
          submits?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['quiz_submissions']['Insert']>
        Relationships: []
      }
      quizzes: {
        Row: {
          id: number
          course_id: number
          section_id: string | null
          duration: number | null
          num_questions: number | null
          total_mark: number | null
          pass_mark: number | null
          drip_rule: number | null
          summary: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          course_id: number
          section_id?: string | null
          duration?: number | null
          num_questions?: number | null
          total_mark?: number | null
          pass_mark?: number | null
          drip_rule?: number | null
          summary?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['quizzes']['Insert']>
        Relationships: []
      }
      reviews: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
          user_id: number | null
          course_id: number | null
          rating: number | null
          review_type: string | null
          review: string | null
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
          user_id?: number | null
          course_id?: number | null
          rating?: number | null
          review_type?: string | null
          review?: string | null
        }
        Update: Partial<Database['public']['Tables']['reviews']['Insert']>
        Relationships: []
      }
      sections: {
        Row: {
          id: number
          user_id: number | null
          course_id: number | null
          title: string | null
          sort: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          course_id?: number | null
          title?: string | null
          sort?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['sections']['Insert']>
        Relationships: []
      }
      seo_fields: {
        Row: {
          id: number
          route: string | null
          name_route: string | null
          meta_title: string | null
          meta_keywords: string | null
          meta_description: string | null
          meta_robot: string | null
          canonical_url: string | null
          custom_url: string | null
          json_ld: string | null  /** JSON-as-text */
          og_title: string | null
          og_description: string | null
          og_image: string | null
          created_at: string | null
          updated_at: string | null
          course_id: number | null
          blog_id: number | null
          bootcamp_id: number | null
        }
        Insert: {
          id?: number
          route?: string | null
          name_route?: string | null
          meta_title?: string | null
          meta_keywords?: string | null
          meta_description?: string | null
          meta_robot?: string | null
          canonical_url?: string | null
          custom_url?: string | null
          json_ld?: string | null
          og_title?: string | null
          og_description?: string | null
          og_image?: string | null
          created_at?: string | null
          updated_at?: string | null
          course_id?: number | null
          blog_id?: number | null
          bootcamp_id?: number | null
        }
        Update: Partial<Database['public']['Tables']['seo_fields']['Insert']>
        Relationships: []
      }
      settings: {
        Row: {
          id: number
          type: string | null
          description: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          type?: string | null
          description?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['settings']['Insert']>
        Relationships: []
      }
      team_package_members: {
        Row: {
          id: number
          leader_id: number | null
          team_package_id: number | null
          member_id: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          leader_id?: number | null
          team_package_id?: number | null
          member_id?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['team_package_members']['Insert']>
        Relationships: []
      }
      team_package_purchases: {
        Row: {
          id: number
          user_id: number | null
          package_id: number | null
          price: number | null
          tax: number | null
          payment_method: string | null
          invoice: string | null
          payment_details: string | null  /** JSON-as-text */
          instructor_revenue: number | null
          admin_revenue: number | null
          status: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          package_id?: number | null
          price?: number | null
          tax?: number | null
          payment_method?: string | null
          invoice?: string | null
          payment_details?: string | null
          instructor_revenue?: number | null
          admin_revenue?: number | null
          status?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['team_package_purchases']['Insert']>
        Relationships: []
      }
      team_training_packages: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
          user_id: number | null
          title: string | null
          slug: string | null
          course_privacy: string | null
          course_id: number | null
          allocation: number
          pricing_type: number
          price: number | null
          expiry_type: string | null
          start_date: number | null
          expiry_date: number | null
          features: string | null  /** JSON-as-text */
          thumbnail: string | null
          status: number
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
          user_id?: number | null
          title?: string | null
          slug?: string | null
          course_privacy?: string | null
          course_id?: number | null
          allocation?: number
          pricing_type?: number
          price?: number | null
          expiry_type?: string | null
          start_date?: number | null
          expiry_date?: number | null
          features?: string | null
          thumbnail?: string | null
          status?: number
        }
        Update: Partial<Database['public']['Tables']['team_training_packages']['Insert']>
        Relationships: []
      }
      tutor_bookings: {
        Row: {
          id: number
          student_id: number | null
          tutor_id: number | null
          schedule_id: number | null
          price: number | null
          tax: number | null
          payment_method: string | null
          invoice: string | null
          payment_details: string | null  /** JSON-as-text */
          instructor_revenue: number | null
          admin_revenue: number | null
          start_time: number | null
          end_time: number | null
          joining_data: string | null  /** JSON-as-text */
          status: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          student_id?: number | null
          tutor_id?: number | null
          schedule_id?: number | null
          price?: number | null
          tax?: number | null
          payment_method?: string | null
          invoice?: string | null
          payment_details?: string | null
          instructor_revenue?: number | null
          admin_revenue?: number | null
          start_time?: number | null
          end_time?: number | null
          joining_data?: string | null
          status?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['tutor_bookings']['Insert']>
        Relationships: []
      }
      tutor_can_teach: {
        Row: {
          id: number
          instructor_id: number | null
          category_id: number | null
          subject_id: number | null
          description: string | null
          price: number | null
          thumbnail: string | null
          status: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          instructor_id?: number | null
          category_id?: number | null
          subject_id?: number | null
          description?: string | null
          price?: number | null
          thumbnail?: string | null
          status?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['tutor_can_teach']['Insert']>
        Relationships: []
      }
      tutor_categories: {
        Row: {
          id: number
          name: string | null
          slug: string
          status: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          name?: string | null
          slug: string
          status?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['tutor_categories']['Insert']>
        Relationships: []
      }
      tutor_reviews: {
        Row: {
          id: number
          tutor_id: number | null
          student_id: number | null
          rating: number | null
          review: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          tutor_id?: number | null
          student_id?: number | null
          rating?: number | null
          review?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['tutor_reviews']['Insert']>
        Relationships: []
      }
      tutor_schedules: {
        Row: {
          id: number
          tutor_id: number | null
          category_id: number | null
          subject_id: number | null
          price: number | null
          start_time: number | null
          end_time: number | null
          duration: number | null
          description: string | null
          tution_type: number | null
          status: number
          booking_id: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          tutor_id?: number | null
          category_id?: number | null
          subject_id?: number | null
          price?: number | null
          start_time?: number | null
          end_time?: number | null
          duration?: number | null
          description?: string | null
          tution_type?: number | null
          status?: number
          booking_id?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['tutor_schedules']['Insert']>
        Relationships: []
      }
      tutor_subjects: {
        Row: {
          id: number
          name: string | null
          slug: string
          status: number
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          name?: string | null
          slug: string
          status?: number
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['tutor_subjects']['Insert']>
        Relationships: []
      }
      user_reviews: {
        Row: {
          id: number
          user_id: number | null
          rating: string | null
          review: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id?: number | null
          rating?: string | null
          review?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['user_reviews']['Insert']>
        Relationships: []
      }
      users: {
        Row: {
          id: number
          role: string
          email: string
          status: number | null
          name: string | null
          phone: string | null
          address: string | null
          skills: string | null  /** JSON-as-text */
          social_links: string | null  /** JSON-as-text */
          about: string | null
          photo: string | null
          facebook: string | null
          twitter: string | null
          website: string | null
          linkedin: string | null
          email_verified_at: string | null
          password: string
          remember_token: string | null
          created_at: string | null
          updated_at: string | null
          educations: string | null  /** JSON-as-text */
        }
        Insert: {
          id?: number
          role: string
          email: string
          status?: number | null
          name?: string | null
          phone?: string | null
          address?: string | null
          skills?: string | null
          social_links?: string | null
          about?: string | null
          photo?: string | null
          facebook?: string | null
          twitter?: string | null
          website?: string | null
          linkedin?: string | null
          email_verified_at?: string | null
          password: string
          remember_token?: string | null
          created_at?: string | null
          updated_at?: string | null
          educations?: string | null
        }
        Update: Partial<Database['public']['Tables']['users']['Insert']>
        Relationships: []
      }
      watch_durations: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
          watched_course_id: number
          watched_lesson_id: number
          watched_student_id: number
          current_duration: number
          watched_counter: string | null  /** JSON-as-text */
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
          watched_course_id: number
          watched_lesson_id: number
          watched_student_id: number
          current_duration?: number
          watched_counter?: string | null
        }
        Update: Partial<Database['public']['Tables']['watch_durations']['Insert']>
        Relationships: []
      }
      watch_histories: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
          course_id: number
          student_id: number
          completed_lesson: string | null  /** JSON-as-text */
          watching_lesson_id: number | null
          course_progress: number
          completed_date: number | null
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
          course_id: number
          student_id: number
          completed_lesson?: string | null
          watching_lesson_id?: number | null
          course_progress?: number
          completed_date?: number | null
        }
        Update: Partial<Database['public']['Tables']['watch_histories']['Insert']>
        Relationships: []
      }
      wishlists: {
        Row: {
          id: number
          created_at: string | null
          updated_at: string | null
          user_id: number | null
          course_id: number | null
        }
        Insert: {
          id?: number
          created_at?: string | null
          updated_at?: string | null
          user_id?: number | null
          course_id?: number | null
        }
        Update: Partial<Database['public']['Tables']['wishlists']['Insert']>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}

// ---- Row aliases ----
export type Applications = Database['public']['Tables']['applications']['Row'];
export type BlogCategories = Database['public']['Tables']['blog_categories']['Row'];
export type BlogComments = Database['public']['Tables']['blog_comments']['Row'];
export type BlogLikes = Database['public']['Tables']['blog_likes']['Row'];
export type Blogs = Database['public']['Tables']['blogs']['Row'];
export type BootcampCategories = Database['public']['Tables']['bootcamp_categories']['Row'];
export type BootcampLiveClasses = Database['public']['Tables']['bootcamp_live_classes']['Row'];
export type BootcampModules = Database['public']['Tables']['bootcamp_modules']['Row'];
export type BootcampPurchases = Database['public']['Tables']['bootcamp_purchases']['Row'];
export type BootcampResources = Database['public']['Tables']['bootcamp_resources']['Row'];
export type Bootcamps = Database['public']['Tables']['bootcamps']['Row'];
export type BuilderPages = Database['public']['Tables']['builder_pages']['Row'];
export type CartItems = Database['public']['Tables']['cart_items']['Row'];
export type Categories = Database['public']['Tables']['categories']['Row'];
export type Certificates = Database['public']['Tables']['certificates']['Row'];
export type Contacts = Database['public']['Tables']['contacts']['Row'];
export type Coupons = Database['public']['Tables']['coupons']['Row'];
export type CourseApprovalRequests = Database['public']['Tables']['course_approval_requests']['Row'];
export type Courses = Database['public']['Tables']['courses']['Row'];
export type DeviceIps = Database['public']['Tables']['device_ips']['Row'];
export type Enrollments = Database['public']['Tables']['enrollments']['Row'];
export type FailedJobs = Database['public']['Tables']['failed_jobs']['Row'];
export type Forums = Database['public']['Tables']['forums']['Row'];
export type InstructorReviews = Database['public']['Tables']['instructor_reviews']['Row'];
export type KnowledgeBaseTopicks = Database['public']['Tables']['knowledge_base_topicks']['Row'];
export type KnowledgeBases = Database['public']['Tables']['knowledge_bases']['Row'];
export type LanguagePhrases = Database['public']['Tables']['language_phrases']['Row'];
export type Languages = Database['public']['Tables']['languages']['Row'];
export type Lessons = Database['public']['Tables']['lessons']['Row'];
export type LikeDislikeReviews = Database['public']['Tables']['like_dislike_reviews']['Row'];
export type LiveClasses = Database['public']['Tables']['live_classes']['Row'];
export type MediaFiles = Database['public']['Tables']['media_files']['Row'];
export type MessageThreads = Database['public']['Tables']['message_threads']['Row'];
export type Messages = Database['public']['Tables']['messages']['Row'];
export type Migrations = Database['public']['Tables']['migrations']['Row'];
export type NewsletterSubscribers = Database['public']['Tables']['newsletter_subscribers']['Row'];
export type Newsletters = Database['public']['Tables']['newsletters']['Row'];
export type Notifications = Database['public']['Tables']['notifications']['Row'];
export type OfflinePayments = Database['public']['Tables']['offline_payments']['Row'];
export type PasswordResetTokens = Database['public']['Tables']['password_reset_tokens']['Row'];
export type PaymentGateways = Database['public']['Tables']['payment_gateways']['Row'];
export type PaymentHistories = Database['public']['Tables']['payment_histories']['Row'];
export type Payouts = Database['public']['Tables']['payouts']['Row'];
export type Permissions = Database['public']['Tables']['permissions']['Row'];
export type PersonalAccessTokens = Database['public']['Tables']['personal_access_tokens']['Row'];
export type PlayerSettings = Database['public']['Tables']['player_settings']['Row'];
export type Questions = Database['public']['Tables']['questions']['Row'];
export type QuizSubmissions = Database['public']['Tables']['quiz_submissions']['Row'];
export type Quizzes = Database['public']['Tables']['quizzes']['Row'];
export type Reviews = Database['public']['Tables']['reviews']['Row'];
export type Sections = Database['public']['Tables']['sections']['Row'];
export type SeoFields = Database['public']['Tables']['seo_fields']['Row'];
export type Settings = Database['public']['Tables']['settings']['Row'];
export type TeamPackageMembers = Database['public']['Tables']['team_package_members']['Row'];
export type TeamPackagePurchases = Database['public']['Tables']['team_package_purchases']['Row'];
export type TeamTrainingPackages = Database['public']['Tables']['team_training_packages']['Row'];
export type TutorBookings = Database['public']['Tables']['tutor_bookings']['Row'];
export type TutorCanTeach = Database['public']['Tables']['tutor_can_teach']['Row'];
export type TutorCategories = Database['public']['Tables']['tutor_categories']['Row'];
export type TutorReviews = Database['public']['Tables']['tutor_reviews']['Row'];
export type TutorSchedules = Database['public']['Tables']['tutor_schedules']['Row'];
export type TutorSubjects = Database['public']['Tables']['tutor_subjects']['Row'];
export type UserReviews = Database['public']['Tables']['user_reviews']['Row'];
export type Users = Database['public']['Tables']['users']['Row'];
export type WatchDurations = Database['public']['Tables']['watch_durations']['Row'];
export type WatchHistories = Database['public']['Tables']['watch_histories']['Row'];
export type Wishlists = Database['public']['Tables']['wishlists']['Row'];

export const TABLES = [
  'applications',
  'blog_categories',
  'blog_comments',
  'blog_likes',
  'blogs',
  'bootcamp_categories',
  'bootcamp_live_classes',
  'bootcamp_modules',
  'bootcamp_purchases',
  'bootcamp_resources',
  'bootcamps',
  'builder_pages',
  'cart_items',
  'categories',
  'certificates',
  'contacts',
  'coupons',
  'course_approval_requests',
  'courses',
  'device_ips',
  'enrollments',
  'failed_jobs',
  'forums',
  'instructor_reviews',
  'knowledge_base_topicks',
  'knowledge_bases',
  'language_phrases',
  'languages',
  'lessons',
  'like_dislike_reviews',
  'live_classes',
  'media_files',
  'message_threads',
  'messages',
  'migrations',
  'newsletter_subscribers',
  'newsletters',
  'notifications',
  'offline_payments',
  'password_reset_tokens',
  'payment_gateways',
  'payment_histories',
  'payouts',
  'permissions',
  'personal_access_tokens',
  'player_settings',
  'questions',
  'quiz_submissions',
  'quizzes',
  'reviews',
  'sections',
  'seo_fields',
  'settings',
  'team_package_members',
  'team_package_purchases',
  'team_training_packages',
  'tutor_bookings',
  'tutor_can_teach',
  'tutor_categories',
  'tutor_reviews',
  'tutor_schedules',
  'tutor_subjects',
  'user_reviews',
  'users',
  'watch_durations',
  'watch_histories',
  'wishlists',
] as const;
export type TableName = (typeof TABLES)[number];
