#!/usr/bin/env python3
"""
F-03 / F-04 / F-05 -- Schema generator.

Reads the authoritative Laravel SQLite schema and emits Postgres DDL with
EXACT parity: same table names, same column names, same column order.

Type mapping (documented in docs/ADR-002-schema-parity.md):
    INTEGER (pk)  -> bigint GENERATED BY DEFAULT AS IDENTITY
    INTEGER       -> bigint
    varchar       -> varchar(N)  (255 default; per-column overrides below)
    TEXT          -> text
    tinyint(1)    -> smallint      (NOT boolean -- preserves 0/1 semantics)
    double        -> numeric(10,2) (Laravel declared double(10,2))
    float         -> double precision
    datetime      -> timestamptz
"""
import sqlite3, sys, os, re
from laravel_source import source_db

TARGET_SCHEMA = os.environ.get("TARGET_SCHEMA", "public")

SRC = source_db(sys.argv)
OUT = os.path.join(os.path.dirname(__file__), "..", "supabase", "migrations")

# Explicit varchar lengths taken from the Laravel migrations (verified by grep).
VARCHAR_OVERRIDES = {
    ("categories", "keywords"): 400,
    ("categories", "description"): 500,
    ("users", "role"): 100,
    ("personal_access_tokens", "token"): 64,
    ("coupons", "status"): 50,
    ("bootcamp_purchases", "invoice"): 100,
    ("bootcamp_purchases", "payment_method"): 50,
    ("offline_payments", "item_type"): 50,
    ("offline_payments", "coupon"): 100,
    ("media_files", "privacy"): 200,
}

# Columns that hold JSON encoded as text. They MUST stay text (F-05).
JSON_TEXT_COLUMNS = {
    ("courses", "drip_content_settings"), ("courses", "instructor_ids"),
    ("watch_histories", "completed_lesson"), ("watch_durations", "watched_counter"),
    ("permissions", "permissions"), ("questions", "answer"), ("questions", "options"),
    ("users", "social_links"), ("users", "educations"), ("users", "skills"),
    ("team_training_packages", "features"), ("tutor_bookings", "payment_details"),
    ("team_package_purchases", "payment_details"), ("payouts", "payment_details"),
    ("payment_gateways", "keys"), ("live_classes", "additional_info"),
    ("bootcamp_live_classes", "joining_data"), ("tutor_bookings", "joining_data"),
    ("offline_payments", "items"), ("seo_fields", "json_ld"),
}


def pg_type(table, col, sqlite_type, is_pk):
    t = (sqlite_type or "").lower()
    if is_pk and t == "integer":
        return "bigint GENERATED BY DEFAULT AS IDENTITY"
    if t == "integer":
        return "bigint"
    if t.startswith("tinyint"):
        return "smallint"
    if t == "double":
        return "numeric(10,2)"
    if t == "numeric":
        return "numeric(10,2)"
    if t == "float":
        return "double precision"
    if t == "datetime":
        return "timestamptz"
    if t == "text":
        return "text"
    if t == "varchar":
        return "varchar(%d)" % VARCHAR_OVERRIDES.get((table, col), 255)
    raise SystemExit("Unmapped sqlite type %r on %s.%s" % (sqlite_type, table, col))


def quote_default(dflt, pgtype):
    if dflt is None:
        return None
    d = dflt.strip()
    if d.upper() in ("NULL", "CURRENT_TIMESTAMP"):
        return None if d.upper() == "NULL" else "now()"
    if d.startswith("'") and d.endswith("'"):
        inner = d[1:-1]
        # numeric-ish defaults written as quoted strings in sqlite
        if re.fullmatch(r"-?\d+(\.\d+)?", inner) and ("int" in pgtype or "numeric" in pgtype or "double" in pgtype or "smallint" in pgtype):
            return inner
        return "'%s'" % inner.replace("'", "''")
    return d


def main():
    con = sqlite3.connect(SRC)
    tables = [r[0] for r in con.execute(
        "select name from sqlite_master where type='table' "
        "and name not like 'sqlite_%' order by name")]

    body, jsoncols = [], []
    for tbl in tables:
        cols = list(con.execute('pragma table_info("%s")' % tbl))
        pk_cols = [c[1] for c in cols if c[5]]
        lines = []
        for _cid, name, typ, notnull, dflt, pk in cols:
            is_ident_pk = bool(pk) and (typ or "").lower() == "integer" and len(pk_cols) == 1
            pgt = pg_type(tbl, name, typ, is_ident_pk)
            if (tbl, name) in JSON_TEXT_COLUMNS:
                # These columns hold JSON, but the SQL TYPE still comes from the
                # Laravel migration -- offline_payments.items is string(255), so
                # forcing it to text here would silently widen the column.
                # The JSON list drives serialization only (see packages/types).
                jsoncols.append("%s.%s" % (tbl, name))
            seg = '    "%s" %s' % (name, pgt)
            d = quote_default(dflt, pgt)
            if d is not None:
                seg += " DEFAULT %s" % d
            if notnull and not is_ident_pk:
                seg += " NOT NULL"
            lines.append(seg)
        if pk_cols:
            lines.append('    PRIMARY KEY (%s)' % ", ".join('"%s"' % c for c in pk_cols))
        body.append('CREATE TABLE IF NOT EXISTS ' + TARGET_SCHEMA + '."%s" (\n%s\n);' % (tbl, ",\n".join(lines)))

    header = (
        "-- 0001_schema.sql -- GENERATED by tools/gen_schema.py. DO NOT EDIT BY HAND.\n"
        "-- Source of truth: the Laravel migrations (%d tables).\n"
        "-- Parity rule: identical table names, column names and column order.\n\n"
        % len(tables))
    with open(os.path.join(OUT, "0001_schema.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write(header + "\n\n".join(body) + "\n")

    # ---- indexes (F-04) ----
    idx = []
    for name, tbl, sql in con.execute(
            "select name, tbl_name, sql from sqlite_master "
            "where type='index' and sql is not null order by tbl_name, name"):
        uniq = " UNIQUE" if re.search(r"\bUNIQUE\b", sql, re.I) else ""
        m = re.search(r"\(([^)]*)\)\s*$", sql)
        if not m:
            continue
        cols = [c.strip().strip('"').strip("`").strip("[]") for c in m.group(1).split(",")]
        idx.append('CREATE%s INDEX IF NOT EXISTS "%s" ON %s."%s" (%s);'
                   % (uniq, name, TARGET_SCHEMA, tbl, ", ".join('"%s"' % c for c in cols)))
    with open(os.path.join(OUT, "0002_indexes.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("-- 0002_indexes.sql -- GENERATED. %d indexes ported 1:1 from Laravel.\n\n"
                % len(idx) + "\n".join(idx) + "\n")

    print("tables=%d indexes=%d json_text_columns=%d" % (len(tables), len(idx), len(jsoncols)))


if __name__ == "__main__":
    main()
