#!/usr/bin/env python3
"""P-07 (RLS baseline) + F-07 (seed data port) generators."""
import sqlite3, os, sys, json
from laravel_source import source_db

TARGET_SCHEMA = os.environ.get("TARGET_SCHEMA", "public")

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = source_db(sys.argv)
OUT = os.path.join(HERE, "..", "supabase")

# Tables the anon (logged-out) client may SELECT. Everything else is
# service-role only. NOTE: `settings` is deliberately EXCLUDED -- it holds
# smtp_pass, open_ai_secret_key and gateway credentials. A curated public
# subset is exposed through the API instead (see packages/core/settings).
PUBLIC_READ = {
    "categories": None,
    "courses": "status = 'active'",
    "blogs": "status = 1",
    "blog_categories": None,
    "bootcamp_categories": None,
    "bootcamps": "status = 1",
    "languages": None,
    "language_phrases": None,
    "tutor_categories": "status = 1",
    "tutor_subjects": "status = 1",
    "sections": None,
    "lessons": "is_free = 1",
    "reviews": None,
    "knowledge_bases": None,
    "knowledge_base_topicks": None,
}


def sqlq(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    con = sqlite3.connect(SRC)
    tables = [r[0] for r in con.execute(
        "select name from sqlite_master where type='table' "
        "and name not like 'sqlite_%' order by name")]

    # ---------------- RLS ----------------
    p = ["""-- 0003_rls.sql -- GENERATED by tools/gen_rls_seed.py
--
-- P-07: RLS baseline + service-role boundary.
--
-- CRITICAL: this project does NOT use Supabase Auth (see ADR-001). Our JWTs are
-- signed with the Supabase JWT secret but carry a BIGINT user id, because
-- public.users.id is bigint while auth.users.id is uuid.
--
--   * auth.uid() MUST NOT be used -- it casts sub to uuid and will throw.
--   * The app role lives in the `app_role` claim, NOT `role`; `role` must stay
--     'authenticated' so PostgREST performs the correct SET ROLE.
--
-- Use onyx.current_user_id() and onyx.current_app_role() below instead.

CREATE SCHEMA IF NOT EXISTS onyx;

CREATE OR REPLACE FUNCTION onyx.current_user_id() RETURNS bigint
  LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'user_id', '')::bigint
  $$;

CREATE OR REPLACE FUNCTION onyx.current_app_role() RETURNS text
  LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'app_role', '')
  $$;

-- Deny-all baseline: RLS on, zero policies => nothing readable or writable by
-- anon/authenticated. service_role bypasses RLS entirely and is the only path
-- for writes (all mutations go through the API).
"""]
    for t in tables:
        p.append('ALTER TABLE %s."%s" ENABLE ROW LEVEL SECURITY;' % (TARGET_SCHEMA, t))
        p.append('ALTER TABLE %s."%s" FORCE ROW LEVEL SECURITY;' % (TARGET_SCHEMA, t))

    p.append("\n-- Public catalog reads (anon + authenticated). SELECT only.")
    for t, cond in PUBLIC_READ.items():
        if t not in tables:
            continue
        using = cond if cond else "true"
        p.append('CREATE POLICY "%s_public_read" ON %s."%s" FOR SELECT '
                 'TO anon, authenticated USING (%s);' % (t, TARGET_SCHEMA, t, using))

    p.append("\n-- Owner reads for a logged-in student's own rows.")
    for t, col in [("enrollments", "user_id"), ("certificates", "user_id"),
                   ("wishlists", "user_id"), ("cart_items", "user_id"),
                   ("watch_histories", "student_id"), ("watch_durations", "watched_student_id")]:
        p.append('CREATE POLICY "%s_owner_read" ON %s."%s" FOR SELECT '
                 'TO authenticated USING ("%s" = onyx.current_user_id());' % (t, TARGET_SCHEMA, t, col))

    with open(os.path.join(OUT, "migrations", "0003_rls.sql"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write("\n".join(p) + "\n")

    # ---------------- SEED ----------------
    seed_tables = ["settings", "languages", "language_phrases", "categories",
                   "blog_categories", "bootcamp_categories", "payment_gateways"]
    s = ["-- seed.sql -- GENERATED. Ports SettingsSeeder / LanguageSeeder /",
         "-- BlogCategorySeeder / BootcampCategorySeeder + the language_phrases corpus.",
         "-- Idempotent: safe to re-run.\n"]
    counts = {}
    for t in seed_tables:
        if t not in tables:
            counts[t] = 0
            continue
        cols = [r[1] for r in con.execute('pragma table_info("%s")' % t)]
        rows = list(con.execute('select %s from "%s"' % (
            ", ".join('"%s"' % c for c in cols), t)))
        counts[t] = len(rows)
        if not rows:
            continue
        s.append("-- %s (%d rows)" % (t, len(rows)))
        collist = ", ".join('"%s"' % c for c in cols)
        for r in rows:
            s.append('INSERT INTO %s."%s" (%s) VALUES (%s) ON CONFLICT DO NOTHING;'
                     % (TARGET_SCHEMA, t, collist, ", ".join(sqlq(v) for v in r)))
        s.append("")

    s.append("-- Re-sync identity sequences after explicit-id inserts.")
    for t in seed_tables:
        if counts.get(t):
            s.append("SELECT setval(pg_get_serial_sequence('%s.%s','id'), "
                     "COALESCE((SELECT MAX(id) FROM %s.%s), 1), true);" % (TARGET_SCHEMA, t, TARGET_SCHEMA, t))

    with open(os.path.join(OUT, "seed.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(s) + "\n")

    print("rls: %d tables secured, %d public-read policies" % (len(tables), len(PUBLIC_READ)))
    print("seed:", ", ".join("%s=%d" % (k, v) for k, v in counts.items()))


if __name__ == "__main__":
    main()
