#!/usr/bin/env python3
"""F-06: generate packages/types/src/database.ts from the Laravel schema.

Mirrors the shape `supabase gen types typescript` produces, so it can be
swapped for the real CLI once a Supabase project exists (F-02) with no
downstream code changes.
"""
import sqlite3, os, sys, re
from laravel_source import source_db

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = source_db(sys.argv)
OUT = os.path.join(HERE, "..", "packages", "types", "src", "database.ts")

JSON_TEXT = {
    "courses.drip_content_settings", "courses.instructor_ids",
    "watch_histories.completed_lesson", "watch_durations.watched_counter",
    "permissions.permissions", "questions.answer", "questions.options",
    "users.social_links", "users.educations", "users.skills",
    "team_training_packages.features", "tutor_bookings.payment_details",
    "team_package_purchases.payment_details", "payouts.payment_details",
    "payment_gateways.keys", "live_classes.additional_info",
    "bootcamp_live_classes.joining_data", "tutor_bookings.joining_data",
    "offline_payments.items", "seo_fields.json_ld",
}


# Tables that exist by explicit decision rather than in the Laravel source.
# quiz_submissions: QuizSubmission.php requires it but no migration created it.
# Source of truth is supabase/migrations/0004_quiz_submissions.sql.
ADDITIONAL_TABLES = {
    "quiz_submissions": [
        ("id", "integer", 1, 1),
        ("quiz_id", "integer", 0, 0),
        ("user_id", "integer", 0, 0),
        ("correct_answer", "text", 0, 0),
        ("wrong_answer", "text", 0, 0),
        ("submits", "text", 0, 0),
        ("created_at", "datetime", 0, 0),
        ("updated_at", "datetime", 0, 0),
    ],
    "blog_comments": [
        ("id", "integer", 1, 1),
        ("blog_id", "integer", 0, 0),
        ("user_id", "integer", 0, 0),
        ("parent_id", "integer", 0, 0),
        ("check", "integer", 0, 0),
        ("comment", "text", 0, 0),
        ("likes", "text", 0, 0),
        ("created_at", "datetime", 0, 0),
        ("updated_at", "datetime", 0, 0),
    ],
    "blog_likes": [
        ("id", "integer", 1, 1),
        ("blog_id", "integer", 0, 0),
        ("user_id", "integer", 0, 0),
        ("created_at", "datetime", 0, 0),
        ("updated_at", "datetime", 0, 0),
    ],
    "user_reviews": [
        ("id", "integer", 1, 1),
        ("user_id", "integer", 0, 0),
        ("rating", "varchar", 0, 0),
        ("review", "text", 0, 0),
        ("created_at", "datetime", 0, 0),
        ("updated_at", "datetime", 0, 0),
    ],
    "bootcamp_resources": [
        ("id", "integer", 1, 1),
        ("module_id", "integer", 0, 0),
        ("title", "varchar", 0, 0),
        ("upload_type", "varchar", 0, 0),
        ("file", "varchar", 0, 0),
        ("created_at", "datetime", 0, 0),
        ("updated_at", "datetime", 0, 0),
    ],
    "applications": [
        ("id", "integer", 1, 1),
        ("user_id", "integer", 0, 0),
        ("phone", "varchar", 0, 0),
        ("description", "text", 0, 0),
        ("document", "varchar", 0, 0),
        ("status", "tinyint(1)", 0, 0),
        ("created_at", "datetime", 0, 0),
        ("updated_at", "datetime", 0, 0),
    ],
}


def ts_type(sqlite_type):
    t = (sqlite_type or "").lower()
    if t in ("integer", "double", "float", "numeric") or t.startswith("tinyint"):
        return "number"
    return "string"


def pascal(name):
    return "".join(p.capitalize() for p in name.split("_"))


def main():
    con = sqlite3.connect(SRC)
    tables = [r[0] for r in con.execute(
        "select name from sqlite_master where type='table' "
        "and name not like 'sqlite_%' order by name")]

    out = ["""// database.ts -- GENERATED by tools/gen_types.py. DO NOT EDIT BY HAND.
//
// Shape-compatible with `supabase gen types typescript`, so once the Supabase
// project exists (F-02) this file can be produced by the CLI instead with zero
// changes to consuming code.
//
// NOTE: columns that store JSON as TEXT are typed `string` here on purpose --
// that is their real storage type. Parse them with the Zod schemas in
// ./json-columns.ts, never with a bare JSON.parse.

export type Json = string | number | boolean | null | { [k: string]: Json } | Json[];
"""]

    tables = sorted(set(tables) | set(ADDITIONAL_TABLES))

    table_blocks, aliases = [], []
    for t in tables:
        if t in ADDITIONAL_TABLES:
            cols = [(i, n, ty, nn, None, pk)
                    for i, (n, ty, nn, pk) in enumerate(ADDITIONAL_TABLES[t])]
        else:
            cols = list(con.execute('pragma table_info("%s")' % t))
        row, ins = [], []
        for _cid, name, typ, notnull, dflt, pk in cols:
            tst = ts_type(typ)
            tag = "  /** JSON-as-text */" if ("%s.%s" % (t, name)) in JSON_TEXT else ""
            optional = (not notnull) or pk or (dflt is not None)
            row.append('          %s: %s%s%s' % (name, tst, "" if notnull else " | null", tag))
            ins.append('          %s%s: %s%s' % (name, "?" if optional else "",
                                                 tst, "" if notnull else " | null"))
        table_blocks.append(
            "      %s: {\n        Row: {\n%s\n        }\n"
            "        Insert: {\n%s\n        }\n"
            "        Update: Partial<Database['public']['Tables']['%s']['Insert']>\n"
            "        Relationships: []\n      }"
            % (t, "\n".join(row), "\n".join(ins), t))
        aliases.append("export type %s = Database['public']['Tables']['%s']['Row'];"
                       % (pascal(t), t))

    out.append("export interface Database {\n  public: {\n    Tables: {\n"
               + "\n".join(table_blocks)
               + "\n    }\n    Views: Record<string, never>\n"
                 "    Functions: Record<string, never>\n"
                 "    Enums: Record<string, never>\n  }\n}\n")
    out.append("// ---- Row aliases ----")
    out.extend(aliases)
    out.append("\nexport const TABLES = [\n"
               + "\n".join("  '%s'," % t for t in tables)
               + "\n] as const;\nexport type TableName = (typeof TABLES)[number];")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("types: %d tables, %d row aliases -> packages/types/src/database.ts"
          % (len(tables), len(aliases)))


if __name__ == "__main__":
    main()
