-- 0001_schema.sql -- GENERATED by tools/gen_schema.py. DO NOT EDIT BY HAND.
-- Source of truth: the Laravel migrations (61 tables).
-- Parity rule: identical table names, column names and column order.

CREATE TABLE IF NOT EXISTS public."blog_categories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "subtitle" varchar(255),
    "slug" varchar(255) NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."blogs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "category_id" bigint,
    "user_id" bigint,
    "title" varchar(255),
    "slug" varchar(255),
    "keywords" text,
    "description" text,
    "thumbnail" varchar(255),
    "banner" varchar(255),
    "is_popular" smallint DEFAULT 0 NOT NULL,
    "status" smallint DEFAULT 1 NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."bootcamp_categories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "slug" varchar(255) NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."bootcamp_live_classes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "module_id" bigint NOT NULL,
    "title" varchar(255) NOT NULL,
    "slug" varchar(255),
    "description" text,
    "start_time" bigint,
    "end_time" bigint,
    "sort" bigint DEFAULT 0 NOT NULL,
    "status" smallint DEFAULT 1 NOT NULL,
    "provider" varchar(255),
    "joining_data" text,
    "force_stop" smallint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."bootcamp_modules" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "bootcamp_id" bigint NOT NULL,
    "title" varchar(255) NOT NULL,
    "publish_date" bigint,
    "expiry_date" bigint,
    "restriction" varchar(255),
    "sort" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."bootcamp_purchases" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "bootcamp_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "price" numeric(10,2) DEFAULT 0 NOT NULL,
    "admin_revenue" numeric(10,2) DEFAULT 0 NOT NULL,
    "instructor_revenue" numeric(10,2) DEFAULT 0 NOT NULL,
    "payment_type" varchar(255),
    "payment_info" varchar(255),
    "transaction_id" varchar(255),
    "status" bigint DEFAULT 1 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "invoice" varchar(100),
    "tax" numeric(10,2) DEFAULT 0 NOT NULL,
    "payment_method" varchar(50),
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."bootcamps" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "category_id" bigint,
    "title" varchar(255),
    "slug" varchar(255),
    "short_description" text,
    "description" text,
    "is_paid" bigint DEFAULT 0 NOT NULL,
    "price" numeric(10,2),
    "discount_flag" bigint DEFAULT 0 NOT NULL,
    "discounted_price" numeric(10,2),
    "publish_date" bigint,
    "thumbnail" varchar(255),
    "faqs" text,
    "requirements" text,
    "outcomes" text,
    "meta_keywords" text,
    "meta_description" text,
    "status" bigint DEFAULT 0 NOT NULL,
    "pending" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."builder_pages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "is_permanent" bigint,
    "edit_home_id" bigint,
    "identifier" varchar(255),
    "name" varchar(255),
    "html" text,
    "status" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."cart_items" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."categories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "parent_id" bigint DEFAULT 0 NOT NULL,
    "title" varchar(255),
    "slug" varchar(255),
    "icon" varchar(255),
    "sort" bigint DEFAULT 0 NOT NULL,
    "status" bigint,
    "keywords" varchar(400),
    "description" varchar(500),
    "thumbnail" varchar(255),
    "category_logo" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."certificates" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "identifier" varchar(255) NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."contacts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "email" varchar(255),
    "phone" varchar(255),
    "address" varchar(255),
    "message" text,
    "has_read" smallint,
    "replied" smallint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."coupons" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "code" varchar(255),
    "discount" double precision,
    "expiry" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "status" varchar(50) DEFAULT 'inactive' NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."course_approval_requests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "message" text,
    "read_status" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."courses" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255),
    "slug" varchar(255),
    "short_description" text,
    "user_id" bigint,
    "category_id" bigint,
    "course_type" varchar(255),
    "status" varchar(255),
    "level" varchar(255),
    "language" varchar(255),
    "is_paid" bigint,
    "price" numeric(10,2),
    "discount_flag" bigint,
    "discounted_price" numeric(10,2),
    "meta_keywords" text,
    "meta_description" text,
    "thumbnail" varchar(255),
    "banner" varchar(255),
    "preview" varchar(255),
    "description" text,
    "requirements" text,
    "outcomes" text,
    "faqs" text,
    "instructor_ids" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "enable_drip_content" smallint DEFAULT 0 NOT NULL,
    "drip_content_settings" text,
    "expiry_period" bigint,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."device_ips" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "ip_address" varchar(255),
    "session_id" varchar(255),
    "user_agent" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."enrollments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "enrollment_type" varchar(255),
    "expiry_date" timestamptz,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "entry_date" bigint,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."failed_jobs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "uuid" varchar(255) NOT NULL,
    "connection" text NOT NULL,
    "queue" text NOT NULL,
    "payload" text NOT NULL,
    "exception" text NOT NULL,
    "failed_at" timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."forums" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "parent_id" bigint DEFAULT 0 NOT NULL,
    "title" varchar(255),
    "description" text,
    "likes" text,
    "dislikes" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."instructor_reviews" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "instructor_id" bigint,
    "rating" varchar(255),
    "review" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."knowledge_base_topicks" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "knowledge_base_id" bigint NOT NULL,
    "topic_name" varchar(255) NOT NULL,
    "description" text NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."knowledge_bases" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."language_phrases" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "language_id" bigint,
    "phrase" text,
    "translated" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."languages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "direction" varchar(255) NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."lessons" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255),
    "user_id" bigint,
    "course_id" bigint,
    "section_id" bigint,
    "lesson_type" varchar(255),
    "duration" varchar(255),
    "lesson_src" varchar(255),
    "thumbnail" varchar(255),
    "is_free" bigint,
    "sort" bigint,
    "description" text,
    "status" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "summary" text,
    "attachment" varchar(255),
    "attachment_type" varchar(255),
    "video_type" varchar(255),
    "total_mark" bigint,
    "pass_mark" bigint,
    "retake" bigint,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."like_dislike_reviews" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "review_id" bigint,
    "user_id" bigint,
    "liked" bigint DEFAULT 0 NOT NULL,
    "disliked" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."live_classes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "class_topic" varchar(255),
    "provider" varchar(255),
    "class_date_and_time" timestamptz,
    "additional_info" text,
    "note" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."media_files" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "post_id" bigint,
    "story_id" bigint,
    "album_id" bigint,
    "product_id" bigint,
    "page_id" bigint,
    "group_id" bigint,
    "chat_id" bigint,
    "file_name" varchar(255),
    "file_type" varchar(255),
    "privacy" varchar(200),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."message_threads" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(255) NOT NULL,
    "contact_one" bigint NOT NULL,
    "contact_two" bigint NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "thread_id" bigint NOT NULL,
    "sender_id" bigint NOT NULL,
    "receiver_id" bigint NOT NULL,
    "message" text,
    "read" smallint DEFAULT 0 NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."migrations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "migration" varchar(255) NOT NULL,
    "batch" bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."newsletter_subscribers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "email" varchar(255) NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."newsletters" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "subject" varchar(255),
    "description" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."offline_payments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "items" varchar(255),
    "tax" double precision,
    "total_amount" double precision,
    "phone_on" varchar(255),
    "bank_no" varchar(255),
    "doc" varchar(255),
    "status" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "item_type" varchar(50),
    "coupon" varchar(100),
    "payable_amount" double precision,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."password_reset_tokens" (
    "email" varchar(255) NOT NULL,
    "token" varchar(255) NOT NULL,
    "created_at" timestamptz,
    PRIMARY KEY ("email")
);

CREATE TABLE IF NOT EXISTS public."payment_gateways" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "identifier" varchar(255),
    "title" varchar(255),
    "keys" text,
    "description" text,
    "status" bigint DEFAULT 1 NOT NULL,
    "test_mode" bigint DEFAULT 0 NOT NULL,
    "is_addon" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."payment_histories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "payment_type" varchar(255),
    "amount" double precision,
    "admin_revenue" double precision,
    "instructor_revenue" double precision,
    "tax" double precision,
    "coupon" varchar(255),
    "invoice" varchar(255),
    "instructor_payment_status" bigint,
    "transaction_id" varchar(255),
    "session_id" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."payouts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "amount" numeric(10,2) DEFAULT 0 NOT NULL,
    "status" bigint DEFAULT 0 NOT NULL,
    "payment_method" text,
    "payment_details" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."permissions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "admin_id" bigint NOT NULL,
    "permissions" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."personal_access_tokens" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "tokenable_type" varchar(255) NOT NULL,
    "tokenable_id" bigint NOT NULL,
    "name" varchar(255) NOT NULL,
    "token" varchar(64) NOT NULL,
    "abilities" text,
    "last_used_at" timestamptz,
    "expires_at" timestamptz,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."player_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "description" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."questions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "quiz_id" bigint,
    "title" text,
    "type" varchar(255),
    "answer" text,
    "options" text,
    "sort" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."quizzes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "course_id" bigint NOT NULL,
    "section_id" varchar(255),
    "duration" bigint,
    "num_questions" bigint,
    "total_mark" bigint,
    "pass_mark" bigint,
    "drip_rule" bigint,
    "summary" bigint,
    "created_at" timestamptz DEFAULT now() NOT NULL,
    "updated_at" timestamptz DEFAULT now() NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."reviews" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "user_id" bigint,
    "course_id" bigint,
    "rating" bigint,
    "review_type" varchar(255),
    "review" text,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."sections" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "course_id" bigint,
    "title" varchar(255),
    "sort" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."seo_fields" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "route" varchar(255),
    "name_route" varchar(255),
    "meta_title" varchar(255),
    "meta_keywords" text,
    "meta_description" text,
    "meta_robot" text,
    "canonical_url" varchar(255),
    "custom_url" varchar(255),
    "json_ld" text,
    "og_title" varchar(255),
    "og_description" text,
    "og_image" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "course_id" bigint,
    "blog_id" bigint,
    "bootcamp_id" bigint,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "type" varchar(255),
    "description" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."team_package_members" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "leader_id" bigint,
    "team_package_id" bigint,
    "member_id" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."team_package_purchases" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "package_id" bigint,
    "price" numeric(10,2),
    "tax" numeric(10,2),
    "payment_method" varchar(255),
    "invoice" varchar(255),
    "payment_details" text,
    "instructor_revenue" numeric(10,2),
    "admin_revenue" numeric(10,2),
    "status" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."team_training_packages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "user_id" bigint,
    "title" varchar(255),
    "slug" varchar(255),
    "course_privacy" varchar(255),
    "course_id" bigint,
    "allocation" bigint DEFAULT 0 NOT NULL,
    "pricing_type" bigint DEFAULT 0 NOT NULL,
    "price" numeric(10,2),
    "expiry_type" varchar(255),
    "start_date" bigint,
    "expiry_date" bigint,
    "features" text,
    "thumbnail" varchar(255),
    "status" bigint DEFAULT 0 NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."tutor_bookings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint,
    "tutor_id" bigint,
    "schedule_id" bigint,
    "price" numeric(10,2),
    "tax" numeric(10,2),
    "payment_method" varchar(255),
    "invoice" varchar(255),
    "payment_details" text,
    "instructor_revenue" numeric(10,2),
    "admin_revenue" numeric(10,2),
    "start_time" bigint,
    "end_time" bigint,
    "joining_data" text,
    "status" bigint DEFAULT 1 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."tutor_can_teach" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "instructor_id" bigint,
    "category_id" bigint,
    "subject_id" bigint,
    "description" text,
    "price" numeric(10,2),
    "thumbnail" varchar(255),
    "status" bigint DEFAULT 1 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."tutor_categories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "slug" varchar(255) NOT NULL,
    "status" bigint DEFAULT 1 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."tutor_reviews" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "tutor_id" bigint,
    "student_id" bigint,
    "rating" bigint,
    "review" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."tutor_schedules" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "tutor_id" bigint,
    "category_id" bigint,
    "subject_id" bigint,
    "price" numeric(10,2),
    "start_time" bigint,
    "end_time" bigint,
    "duration" bigint,
    "description" text,
    "tution_type" bigint,
    "status" bigint DEFAULT 1 NOT NULL,
    "booking_id" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."tutor_subjects" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255),
    "slug" varchar(255) NOT NULL,
    "status" bigint DEFAULT 1 NOT NULL,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "role" varchar(100) NOT NULL,
    "email" varchar(255) NOT NULL,
    "status" bigint,
    "name" varchar(255),
    "phone" varchar(255),
    "address" text,
    "skills" text,
    "social_links" text,
    "about" text,
    "photo" varchar(255),
    "facebook" varchar(255),
    "twitter" varchar(255),
    "website" varchar(255),
    "linkedin" varchar(255),
    "email_verified_at" timestamptz,
    "password" varchar(255) NOT NULL,
    "remember_token" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "educations" text,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."watch_durations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "watched_course_id" bigint NOT NULL,
    "watched_lesson_id" bigint NOT NULL,
    "watched_student_id" bigint NOT NULL,
    "current_duration" bigint DEFAULT 0 NOT NULL,
    "watched_counter" text,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."watch_histories" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "course_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "completed_lesson" text,
    "watching_lesson_id" bigint,
    "course_progress" numeric(10,2) DEFAULT 0 NOT NULL,
    "completed_date" bigint,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."wishlists" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "user_id" bigint,
    "course_id" bigint,
    PRIMARY KEY ("id")
);
