-- 0002_indexes.sql -- GENERATED. 75 indexes ported 1:1 from Laravel.

CREATE UNIQUE INDEX IF NOT EXISTS "blog_categories_slug_unique" ON public."blog_categories" ("slug");
CREATE INDEX IF NOT EXISTS "blogs_category_id_index" ON public."blogs" ("category_id");
CREATE INDEX IF NOT EXISTS "blogs_slug_index" ON public."blogs" ("slug");
CREATE INDEX IF NOT EXISTS "blogs_user_id_index" ON public."blogs" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "bootcamp_categories_slug_unique" ON public."bootcamp_categories" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "bootcamp_categories_title_unique" ON public."bootcamp_categories" ("title");
CREATE INDEX IF NOT EXISTS "bootcamp_live_classes_module_id_index" ON public."bootcamp_live_classes" ("module_id");
CREATE INDEX IF NOT EXISTS "bootcamp_modules_bootcamp_id_index" ON public."bootcamp_modules" ("bootcamp_id");
CREATE INDEX IF NOT EXISTS "bootcamp_purchases_bootcamp_id_index" ON public."bootcamp_purchases" ("bootcamp_id");
CREATE INDEX IF NOT EXISTS "bootcamp_purchases_status_index" ON public."bootcamp_purchases" ("status");
CREATE INDEX IF NOT EXISTS "bootcamp_purchases_user_id_index" ON public."bootcamp_purchases" ("user_id");
CREATE INDEX IF NOT EXISTS "bootcamps_category_id_index" ON public."bootcamps" ("category_id");
CREATE INDEX IF NOT EXISTS "bootcamps_slug_index" ON public."bootcamps" ("slug");
CREATE INDEX IF NOT EXISTS "bootcamps_user_id_index" ON public."bootcamps" ("user_id");
CREATE INDEX IF NOT EXISTS "cart_items_course_id_index" ON public."cart_items" ("course_id");
CREATE INDEX IF NOT EXISTS "cart_items_user_id_index" ON public."cart_items" ("user_id");
CREATE INDEX IF NOT EXISTS "categories_parent_id_index" ON public."categories" ("parent_id");
CREATE INDEX IF NOT EXISTS "certificates_course_id_index" ON public."certificates" ("course_id");
CREATE UNIQUE INDEX IF NOT EXISTS "certificates_identifier_unique" ON public."certificates" ("identifier");
CREATE INDEX IF NOT EXISTS "certificates_user_id_index" ON public."certificates" ("user_id");
CREATE INDEX IF NOT EXISTS "contacts_email_index" ON public."contacts" ("email");
CREATE INDEX IF NOT EXISTS "contacts_has_read_index" ON public."contacts" ("has_read");
CREATE INDEX IF NOT EXISTS "contacts_replied_index" ON public."contacts" ("replied");
CREATE INDEX IF NOT EXISTS "course_approval_requests_course_id_index" ON public."course_approval_requests" ("course_id");
CREATE INDEX IF NOT EXISTS "course_approval_requests_user_id_index" ON public."course_approval_requests" ("user_id");
CREATE INDEX IF NOT EXISTS "courses_category_id_index" ON public."courses" ("category_id");
CREATE INDEX IF NOT EXISTS "courses_user_id_index" ON public."courses" ("user_id");
CREATE INDEX IF NOT EXISTS "device_ips_user_agent_index" ON public."device_ips" ("user_agent");
CREATE INDEX IF NOT EXISTS "device_ips_user_id_index" ON public."device_ips" ("user_id");
CREATE INDEX IF NOT EXISTS "enrollments_course_id_index" ON public."enrollments" ("course_id");
CREATE INDEX IF NOT EXISTS "enrollments_user_id_index" ON public."enrollments" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "failed_jobs_uuid_unique" ON public."failed_jobs" ("uuid");
CREATE INDEX IF NOT EXISTS "forums_parent_id_index" ON public."forums" ("parent_id");
CREATE INDEX IF NOT EXISTS "forums_user_id_course_id_index" ON public."forums" ("user_id", "course_id");
CREATE UNIQUE INDEX IF NOT EXISTS "knowledge_bases_title_unique" ON public."knowledge_bases" ("title");
CREATE INDEX IF NOT EXISTS "language_phrases_language_id_index" ON public."language_phrases" ("language_id");
CREATE INDEX IF NOT EXISTS "lessons_course_id_index" ON public."lessons" ("course_id");
CREATE INDEX IF NOT EXISTS "lessons_section_id_index" ON public."lessons" ("section_id");
CREATE INDEX IF NOT EXISTS "lessons_user_id_index" ON public."lessons" ("user_id");
CREATE INDEX IF NOT EXISTS "live_classes_course_id_index" ON public."live_classes" ("course_id");
CREATE INDEX IF NOT EXISTS "live_classes_user_id_index" ON public."live_classes" ("user_id");
CREATE INDEX IF NOT EXISTS "media_files_chat_id_index" ON public."media_files" ("chat_id");
CREATE UNIQUE INDEX IF NOT EXISTS "message_threads_code_unique" ON public."message_threads" ("code");
CREATE UNIQUE INDEX IF NOT EXISTS "newsletter_subscribers_email_unique" ON public."newsletter_subscribers" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "personal_access_tokens_token_unique" ON public."personal_access_tokens" ("token");
CREATE INDEX IF NOT EXISTS "personal_access_tokens_tokenable_type_tokenable_id_index" ON public."personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE INDEX IF NOT EXISTS "player_settings_title_index" ON public."player_settings" ("title");
CREATE UNIQUE INDEX IF NOT EXISTS "player_settings_title_unique" ON public."player_settings" ("title");
CREATE INDEX IF NOT EXISTS "sections_course_id_index" ON public."sections" ("course_id");
CREATE INDEX IF NOT EXISTS "sections_user_id_index" ON public."sections" ("user_id");
CREATE INDEX IF NOT EXISTS "team_package_members_leader_id_index" ON public."team_package_members" ("leader_id");
CREATE INDEX IF NOT EXISTS "team_package_members_member_id_index" ON public."team_package_members" ("member_id");
CREATE INDEX IF NOT EXISTS "team_package_members_team_package_id_index" ON public."team_package_members" ("team_package_id");
CREATE INDEX IF NOT EXISTS "team_package_purchases_package_id_index" ON public."team_package_purchases" ("package_id");
CREATE INDEX IF NOT EXISTS "team_package_purchases_user_id_index" ON public."team_package_purchases" ("user_id");
CREATE INDEX IF NOT EXISTS "team_training_packages_slug_index" ON public."team_training_packages" ("slug");
CREATE INDEX IF NOT EXISTS "team_training_packages_user_id_course_id_index" ON public."team_training_packages" ("user_id", "course_id");
CREATE INDEX IF NOT EXISTS "tutor_bookings_schedule_id_index" ON public."tutor_bookings" ("schedule_id");
CREATE INDEX IF NOT EXISTS "tutor_bookings_student_id_index" ON public."tutor_bookings" ("student_id");
CREATE INDEX IF NOT EXISTS "tutor_bookings_tutor_id_index" ON public."tutor_bookings" ("tutor_id");
CREATE INDEX IF NOT EXISTS "tutor_can_teach_instructor_id_category_id_subject_id_index" ON public."tutor_can_teach" ("instructor_id", "category_id", "subject_id");
CREATE INDEX IF NOT EXISTS "tutor_categories_slug_index" ON public."tutor_categories" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "tutor_categories_slug_unique" ON public."tutor_categories" ("slug");
CREATE INDEX IF NOT EXISTS "tutor_categories_status_index" ON public."tutor_categories" ("status");
CREATE INDEX IF NOT EXISTS "tutor_reviews_tutor_id_student_id_index" ON public."tutor_reviews" ("tutor_id", "student_id");
CREATE INDEX IF NOT EXISTS "tutor_schedules_start_time_index" ON public."tutor_schedules" ("start_time");
CREATE INDEX IF NOT EXISTS "tutor_schedules_tutor_id_category_id_subject_id_index" ON public."tutor_schedules" ("tutor_id", "category_id", "subject_id");
CREATE INDEX IF NOT EXISTS "tutor_subjects_slug_index" ON public."tutor_subjects" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "tutor_subjects_slug_unique" ON public."tutor_subjects" ("slug");
CREATE INDEX IF NOT EXISTS "tutor_subjects_status_index" ON public."tutor_subjects" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_unique" ON public."users" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "watch_duration_unique" ON public."watch_durations" ("watched_course_id", "watched_lesson_id", "watched_student_id");
CREATE INDEX IF NOT EXISTS "watch_durations_watched_lesson_id_index" ON public."watch_durations" ("watched_lesson_id");
CREATE INDEX IF NOT EXISTS "wishlists_course_id_index" ON public."wishlists" ("course_id");
CREATE INDEX IF NOT EXISTS "wishlists_user_id_index" ON public."wishlists" ("user_id");
