-- 0003_rls.sql -- GENERATED by tools/gen_rls_seed.py
--
-- P-07: RLS baseline + service-role boundary.
--
-- CRITICAL: this project does NOT use Supabase Auth (see ADR-001). Our JWTs are
-- signed with the Supabase JWT secret but carry a BIGINT user id, because
-- public.users.id is bigint while auth.users.id is uuid.
--
--   * auth.uid() MUST NOT be used -- it casts sub to uuid and will throw.
--   * The app role lives in the `app_role` claim, NOT `role`; `role` must stay
--     'authenticated' so PostgREST performs the correct SET ROLE.
--
-- Use onyx.current_user_id() and onyx.current_app_role() below instead.

CREATE SCHEMA IF NOT EXISTS onyx;

CREATE OR REPLACE FUNCTION onyx.current_user_id() RETURNS bigint
  LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'user_id', '')::bigint
  $$;

CREATE OR REPLACE FUNCTION onyx.current_app_role() RETURNS text
  LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'app_role', '')
  $$;

-- Deny-all baseline: RLS on, zero policies => nothing readable or writable by
-- anon/authenticated. service_role bypasses RLS entirely and is the only path
-- for writes (all mutations go through the API).

ALTER TABLE public."blog_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."blog_categories" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."blogs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."blogs" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_categories" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_live_classes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_live_classes" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_modules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_modules" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_purchases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_purchases" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamps" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."builder_pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."builder_pages" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."cart_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."cart_items" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."categories" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."certificates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."certificates" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."contacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."contacts" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."coupons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."coupons" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."course_approval_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."course_approval_requests" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."courses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."courses" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."device_ips" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."device_ips" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."enrollments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."enrollments" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."failed_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."failed_jobs" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."forums" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."forums" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."instructor_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."instructor_reviews" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."knowledge_base_topicks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."knowledge_base_topicks" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."knowledge_bases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."knowledge_bases" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."language_phrases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."language_phrases" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."languages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."languages" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."lessons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."lessons" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."like_dislike_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."like_dislike_reviews" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."live_classes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."live_classes" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."media_files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."media_files" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."message_threads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."message_threads" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."messages" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."migrations" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."newsletter_subscribers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."newsletter_subscribers" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."newsletters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."newsletters" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."notifications" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."offline_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."offline_payments" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."password_reset_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."password_reset_tokens" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."payment_gateways" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."payment_gateways" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."payment_histories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."payment_histories" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."payouts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."payouts" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."permissions" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."personal_access_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."personal_access_tokens" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."player_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."player_settings" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."questions" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."quizzes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quizzes" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."reviews" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."sections" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."seo_fields" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."seo_fields" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."settings" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."team_package_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."team_package_members" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."team_package_purchases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."team_package_purchases" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."team_training_packages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."team_training_packages" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_bookings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_bookings" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_can_teach" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_can_teach" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_categories" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_reviews" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_schedules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_schedules" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_subjects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."tutor_subjects" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."users" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."watch_durations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."watch_durations" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."watch_histories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."watch_histories" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."wishlists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."wishlists" FORCE ROW LEVEL SECURITY;

-- Public catalog reads (anon + authenticated). SELECT only.
CREATE POLICY "categories_public_read" ON public."categories" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "courses_public_read" ON public."courses" FOR SELECT TO anon, authenticated USING (status = 'active');
CREATE POLICY "blogs_public_read" ON public."blogs" FOR SELECT TO anon, authenticated USING (status = 1);
CREATE POLICY "blog_categories_public_read" ON public."blog_categories" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "bootcamp_categories_public_read" ON public."bootcamp_categories" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "bootcamps_public_read" ON public."bootcamps" FOR SELECT TO anon, authenticated USING (status = 1);
CREATE POLICY "languages_public_read" ON public."languages" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "language_phrases_public_read" ON public."language_phrases" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "tutor_categories_public_read" ON public."tutor_categories" FOR SELECT TO anon, authenticated USING (status = 1);
CREATE POLICY "tutor_subjects_public_read" ON public."tutor_subjects" FOR SELECT TO anon, authenticated USING (status = 1);
CREATE POLICY "sections_public_read" ON public."sections" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "lessons_public_read" ON public."lessons" FOR SELECT TO anon, authenticated USING (is_free = 1);
CREATE POLICY "reviews_public_read" ON public."reviews" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "knowledge_bases_public_read" ON public."knowledge_bases" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "knowledge_base_topicks_public_read" ON public."knowledge_base_topicks" FOR SELECT TO anon, authenticated USING (true);

-- Owner reads for a logged-in student's own rows.
CREATE POLICY "enrollments_owner_read" ON public."enrollments" FOR SELECT TO authenticated USING ("user_id" = onyx.current_user_id());
CREATE POLICY "certificates_owner_read" ON public."certificates" FOR SELECT TO authenticated USING ("user_id" = onyx.current_user_id());
CREATE POLICY "wishlists_owner_read" ON public."wishlists" FOR SELECT TO authenticated USING ("user_id" = onyx.current_user_id());
CREATE POLICY "cart_items_owner_read" ON public."cart_items" FOR SELECT TO authenticated USING ("user_id" = onyx.current_user_id());
CREATE POLICY "watch_histories_owner_read" ON public."watch_histories" FOR SELECT TO authenticated USING ("student_id" = onyx.current_user_id());
CREATE POLICY "watch_durations_owner_read" ON public."watch_durations" FOR SELECT TO authenticated USING ("watched_student_id" = onyx.current_user_id());
