-- 0004_quiz_submissions.sql
--
-- NOT PART OF THE 61-TABLE PARITY SET. Apply only after an explicit decision.
--
-- app/Models/QuizSubmission.php exists and student/QuizController.php calls
-- QuizSubmission::insert() on every quiz submit -- but NO Laravel migration
-- ever creates this table. Quiz submission is therefore broken in the source
-- application: it throws "table not found" the first time a student submits.
--
-- Columns below match exactly what the Laravel code reads and writes:
--   quiz_id        lessons.id of the quiz-type lesson (NOT quizzes.id)
--   correct_answer JSON array of question ids answered correctly
--   wrong_answer   JSON array of question ids answered incorrectly
--   submits        JSON map of question id -> submitted value
--
-- Types follow the same mapping as every other table (see ADR-002).

CREATE TABLE IF NOT EXISTS public."quiz_submissions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "quiz_id" bigint,
    "user_id" bigint,
    "correct_answer" text,
    "wrong_answer" text,
    "submits" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "quiz_submissions_quiz_id_index"
  ON public."quiz_submissions" ("quiz_id");
CREATE INDEX IF NOT EXISTS "quiz_submissions_user_id_index"
  ON public."quiz_submissions" ("user_id");

ALTER TABLE public."quiz_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."quiz_submissions" FORCE ROW LEVEL SECURITY;

CREATE POLICY "quiz_submissions_owner_read" ON public."quiz_submissions"
  FOR SELECT TO authenticated USING ("user_id" = onyx.current_user_id());
