-- 0005_blog_engagement.sql
--
-- NOT PART OF THE 61-TABLE PARITY SET. Same situation as 0004.
--
-- app/Models/BlogComment.php and app/Models/BlogLike.php exist, and
-- student/BlogCommentController + BlogController::blog_like write to them on
-- every comment and like -- but NO Laravel migration creates either table.
-- Blog comments and likes throw "table not found" in the source application.
--
-- Columns match exactly what the Laravel models declare fillable:
--   blog_comments: blog_id, user_id, parent_id, check, comment, likes
--   blog_likes:    blog_id, user_id
--
-- "check" is a reserved word in SQL, hence the quoting. Types follow the same
-- mapping as every other table (ADR-002).

CREATE TABLE IF NOT EXISTS public."blog_comments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "blog_id" bigint,
    "user_id" bigint,
    "parent_id" bigint DEFAULT 0,
    "check" smallint DEFAULT 0,
    "comment" text,
    "likes" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS public."blog_likes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "blog_id" bigint,
    "user_id" bigint,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "blog_comments_blog_id_index" ON public."blog_comments" ("blog_id");
CREATE INDEX IF NOT EXISTS "blog_comments_parent_id_index" ON public."blog_comments" ("parent_id");
CREATE INDEX IF NOT EXISTS "blog_likes_blog_id_index" ON public."blog_likes" ("blog_id");
-- One like per person per post is a data rule, not just app logic.
CREATE UNIQUE INDEX IF NOT EXISTS "blog_likes_blog_user_unique"
  ON public."blog_likes" ("blog_id", "user_id");

ALTER TABLE public."blog_comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."blog_comments" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."blog_likes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."blog_likes" FORCE ROW LEVEL SECURITY;

-- Comments are part of a public blog post, so anonymous readers may see them.
CREATE POLICY "blog_comments_public_read" ON public."blog_comments"
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "blog_likes_public_read" ON public."blog_likes"
  FOR SELECT TO anon, authenticated USING (true);
