-- 0006_user_reviews.sql
--
-- R-03: admin-managed testimonials.
--
-- App\Models\UserReview exists and SettingController writes to it, but no
-- Laravel migration ever created `user_reviews` -- the same defect class as
-- quiz_submissions and blog_comments/blog_likes. The admin screens in the
-- original therefore fail at runtime. Columns are taken from what the
-- controller assigns (user_id, rating, review) plus Eloquent's timestamps.
--
-- rating is varchar to match instructor_reviews.rating, which is the column the
-- <select> in user_review_create.blade.php mirrors.

CREATE TABLE IF NOT EXISTS public."user_reviews" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "rating" varchar(255),
    "review" text,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "user_reviews_user_id_index"
  ON public."user_reviews" ("user_id");

ALTER TABLE public."user_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_reviews" FORCE ROW LEVEL SECURITY;

-- Testimonials are homepage content, so anonymous visitors may read them.
-- Writes stay service-role only, like every other table.
CREATE POLICY "user_reviews_public_read" ON public."user_reviews"
  FOR SELECT TO anon, authenticated USING (true);

NOTIFY pgrst, 'reload schema';
