-- 0008_bootcamp_resources.sql
--
-- BC-04: files and recordings attached to a bootcamp module.
--
-- `App\Models\BootcampResource` exists and `Admin\BootcampResourceController`
-- writes to it on every upload, but no Laravel migration ever creates the
-- table -- the fifth instance of that defect in this codebase, after
-- quiz_submissions (0004), blog_comments/blog_likes (0005) and user_reviews
-- (0006). Resource upload therefore throws "table not found" in the original.
--
-- Columns come from the model's $fillable plus Eloquent's timestamps.
-- upload_type is 'resource' or 'record', as the controller's validation rule
-- says; it stays varchar rather than becoming an enum, to match how every
-- other status-like column in this schema is typed.

CREATE TABLE IF NOT EXISTS public."bootcamp_resources" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "module_id" bigint,
    "title" varchar(255),
    "upload_type" varchar(255),
    "file" varchar(255),
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "bootcamp_resources_module_id_index"
  ON public."bootcamp_resources" ("module_id");

ALTER TABLE public."bootcamp_resources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."bootcamp_resources" FORCE ROW LEVEL SECURITY;

-- No policy: deny-all, like every other table that is not public catalogue.
-- Access is decided by the API, which checks the purchase before serving a
-- signed URL -- a resource is paid-for content.

NOTIFY pgrst, 'reload schema';
