-- 0009_applications.sql
--
-- SET-09: become-an-instructor applications.
--
-- `App\Models\Application` exists and `student/BecomeInstructorController`
-- inserts into it on every submission, but no Laravel migration ever creates
-- the table -- the sixth instance of that defect, after quiz_submissions
-- (0004), blog_comments/blog_likes (0005), user_reviews (0006) and
-- bootcamp_resources (0008). Applying to teach therefore throws in the original.
--
-- Columns come from the model's $fillable plus Eloquent's timestamps. `status`
-- is 0 pending / 1 approved, matching instructor_application_approve().

CREATE TABLE IF NOT EXISTS public."applications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint,
    "phone" varchar(255),
    "description" text,
    "document" varchar(255),
    "status" smallint DEFAULT 0,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    PRIMARY KEY ("id")
);

-- One open application per person is the rule the controller enforces; the
-- index makes the lookup that enforces it cheap.
CREATE INDEX IF NOT EXISTS "applications_user_id_index"
  ON public."applications" ("user_id");

ALTER TABLE public."applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."applications" FORCE ROW LEVEL SECURITY;

-- No policy: deny-all. An application carries a phone number and an uploaded
-- document, so it is only ever read through the API, by its author or an admin.

NOTIFY pgrst, 'reload schema';
