import type { Field } from '@/components/settings-form';

export const SETTING_TABS = ['system', 'website', 'player', 'notification', 'api'] as const;
export type SettingTab = (typeof SETTING_TABS)[number];

export const TAB_LABEL: Record<SettingTab, string> = {
  system: 'System', website: 'Website', player: 'Player and drip',
  notification: 'Notifications', api: 'API credentials',
};

const yesNo = [{ value: '1', label: 'On' }, { value: '0', label: 'Off' }];

/** The fields each screen shows. Keys must match SETTING_GROUPS on the server. */
export const SETTING_FIELDS: Record<SettingTab, Field[]> = {
  system: [
    { key: 'system_title', label: 'Site title' },
    { key: 'system_email', label: 'Site email', type: 'email' },
    { key: 'timezone', label: 'Timezone', hint: 'e.g. Europe/London' },
    { key: 'language', label: 'Default language' },
    { key: 'theme', label: 'Theme' },
    { key: 'system_currency', label: 'Currency', hint: 'e.g. USD' },
    { key: 'currency_position', label: 'Currency position', type: 'select',
      options: [{ value: 'left', label: 'Before the amount' },
                { value: 'right', label: 'After the amount' }] },
    { key: 'phone', label: 'Phone' },
    { key: 'address', label: 'Address' },
    { key: 'logo', label: 'Logo path' },
    { key: 'favicon', label: 'Favicon path' },
    { key: 'meta_title', label: 'Default meta title' },
    { key: 'meta_keywords', label: 'Default meta keywords' },
    { key: 'meta_description', label: 'Default meta description', type: 'textarea' },
    { key: 'footer_text', label: 'Footer text', type: 'textarea' },
  ],
  website: [
    { key: 'banner_title', label: 'Banner title' },
    { key: 'banner_subtitle', label: 'Banner subtitle' },
    { key: 'banner_image', label: 'Banner image path' },
    { key: 'course_per_page', label: 'Courses per page', type: 'number' },
    { key: 'blog_visibility_on_the_home_page', label: 'Blog module', type: 'select',
      options: yesNo, hint: 'Off hides every blog page' },
    { key: 'instructors_blog_permission', label: 'Instructors may blog',
      type: 'select', options: yesNo },
    { key: 'instructor_can_publish_course', label: 'Instructors may publish courses',
      type: 'select', options: yesNo },
    { key: 'instructor_application', label: 'Accept instructor applications',
      type: 'select', options: yesNo },
    { key: 'facebook', label: 'Facebook' },
    { key: 'twitter', label: 'Twitter' },
    { key: 'linkedin', label: 'LinkedIn' },
    { key: 'instagram', label: 'Instagram' },
    { key: 'youtube', label: 'YouTube' },
    { key: 'about_us', label: 'About us', type: 'textarea' },
    { key: 'instructor_application_note', label: 'Note on the application form',
      type: 'textarea' },
  ],
  player: [
    { key: 'drip_content', label: 'Drip content', type: 'select', options: yesNo },
    { key: 'lesson_completion_role', label: 'Lesson counts as complete by', type: 'select',
      options: [{ value: 'duration', label: 'Watched duration' },
                { value: 'percentage', label: 'Watched percentage' }] },
    { key: 'minimum_duration', label: 'Minimum duration (seconds)', type: 'number' },
    { key: 'minimum_percentage', label: 'Minimum percentage', type: 'number' },
    { key: 'disable_download', label: 'Block attachment downloads', type: 'select',
      options: yesNo },
    { key: 'watermark_type', label: 'Watermark', type: 'select',
      options: [{ value: 'none', label: 'None' }, { value: 'js', label: 'Overlay' },
                { value: 'ffmpeg', label: 'Burned in (not implemented)' }] },
    { key: 'watermark_text', label: 'Watermark text' },
    { key: 'watermark_opacity', label: 'Opacity', type: 'number' },
  ],
  notification: [
    { key: 'notify_on_enrolment', label: 'On enrolment', type: 'select', options: yesNo },
    { key: 'notify_on_purchase', label: 'On purchase', type: 'select', options: yesNo },
    { key: 'notify_on_course_approval', label: 'On course approval', type: 'select',
      options: yesNo },
    { key: 'notify_on_payout', label: 'On payout', type: 'select', options: yesNo },
    { key: 'notify_on_message', label: 'On new message', type: 'select', options: yesNo },
    { key: 'notify_on_new_user', label: 'On new user', type: 'select', options: yesNo },
  ],
  api: [
    { key: 'protocol', label: 'Mail protocol', hint: 'smtp or mail' },
    { key: 'smtp_host', label: 'SMTP host' },
    { key: 'smtp_port', label: 'SMTP port', type: 'number' },
    { key: 'smtp_user', label: 'SMTP user' },
    { key: 'smtp_pass', label: 'SMTP password', type: 'password' },
    { key: 'smtp_encryption', label: 'SMTP encryption' },
    { key: 'zoom_account_id', label: 'Zoom account id' },
    { key: 'zoom_client_id', label: 'Zoom client id' },
    { key: 'zoom_client_secret', label: 'Zoom client secret', type: 'password' },
    { key: 'zoom_sdk_client_id', label: 'Zoom SDK key' },
    { key: 'zoom_sdk_client_secret', label: 'Zoom SDK secret', type: 'password' },
    { key: 'open_ai_model', label: 'OpenAI model' },
    { key: 'open_ai_secret_key', label: 'OpenAI key', type: 'password' },
    { key: 'recaptcha_site_key', label: 'reCAPTCHA site key' },
    { key: 'recaptcha_secret_key', label: 'reCAPTCHA secret', type: 'password' },
    { key: 'instructor_revenue', label: 'Instructor revenue share (%)', type: 'number' },
    { key: 'tax', label: 'Tax (%)', type: 'number' },
  ],
};
